#!/usr/bin/env bash

# Options
options=(
  " Capture Desktop"
  "󰩭 Capture Area"
  " Capture Window"
  " Capture in 5s"
  "󱑈 Capture in 10s"
)

# Screenshot directory & filename
dir="$HOME/Pictures/screenshot/"
timestamp=$(date +%Y-%m-%d-%H-%M-%S)
geometry=$(xrandr | grep 'current' | head -n1 | cut -d',' -f2 | tr -d '[:blank:],current')
file="Screenshot_${timestamp}_${geometry}.png"

# Notify and view
notify_view() {
  dunstify -u low --replace=699 "Copied to clipboard."
  nsxiv "${dir}/${file}"
  if [[ -f "${dir}/${file}" ]]; then
    dunstify -u low --replace=699 "Screenshot Saved."
  else
    dunstify -u low --replace=699 "Screenshot Deleted."
  fi
}

# Copy screenshot to clipboard
copy_shot() {
  tee "$file" | xclip -selection clipboard -t image/png
}

# Countdown
countdown() {
  for sec in $(seq "$1" -1 1); do
    dunstify -t 1000 --replace=699 "Taking shot in: $sec"
    sleep 1
  done
}

# Screenshot functions
shotnow() { cd "$dir" && sleep 0.5 && maim -u -f png | copy_shot && notify_view; }
shot5() { countdown 5; cd "$dir" && maim -u -f png | copy_shot && notify_view; }
shot10() { countdown 10; cd "$dir" && maim -u -f png | copy_shot && notify_view; }
shotwin() { cd "$dir" && maim -u -f png -i "$(xdotool getactivewindow)" | copy_shot && notify_view; }
shotarea() { cd "$dir" && maim -u -f png -s -b 2 -c 0.35,0.55,0.85,0.25 -l | copy_shot && notify_view; }

# Run chosen command
run_cmd() {
  case "$1" in
    "--opt1") shotnow ;;
    "--opt2") shotarea ;;
    "--opt3") shotwin ;;
    "--opt4") shot5 ;;
    "--opt5") shot10 ;;
  esac
}

# dmenu
chosen=$(printf '%s\n' "${options[@]}" | dmenu -l 7 -g 1 -i -p "Screenshot which area?")
case "$chosen" in
  "${options[0]}") run_cmd --opt1 ;;
  "${options[1]}") run_cmd --opt2 ;;
  "${options[2]}") run_cmd --opt3 ;;
  "${options[3]}") run_cmd --opt4 ;;
  "${options[4]}") run_cmd --opt5 ;;
esac
