[colors.primary]
background = "#002B36"
foreground = "#839496"

[colors.cursor]
text   = "#002B36"
cursor = "#586E75"

[colors.selection]
text       = "#93A1A1"
background = "#073642"

[colors.normal]
black   = "#073642"
red     = "#DC322F"
green   = "#859900"
yellow  = "#B58900"
blue    = "#268BD2"
magenta = "#D33682"
cyan    = "#2AA198"
white   = "#eee8d5"

[colors.bright]
black   = "#002731"
red     = "#CB4B16"
green   = "#364725"
yellow  = "#3C342C"
blue    = "#0B4764"
magenta = "#6C71C4"
cyan    = "#0C4E53"
white   = "#fdf6e3"
