$background = rgb(002B36)
$foreground = rgb(839496)
$accent     = rgb(268BD2)
$bg_subtle  = rgb(133a44)
$bg_muted   = rgb(274a52)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
