foreground            #839496
background            #002B36
selection_foreground  #93A1A1
selection_background  #073642

cursor                #586E75
cursor_text_color     #002B36

# Black / Gray
color0  #073642
color8  #002731

# Red
color1  #DC322F
color9  #CB4B16

# Green
color2  #859900
color10 #364725

# Yellow
color3  #B58900
color11 #3C342C

# Blue
color4  #268BD2
color12 #0B4764

# Magenta
color5  #D33682
color13 #6C71C4

# Cyan
color6  #2AA198
color14 #0C4E53

# White
color7  #eee8d5
color15 #fdf6e3

# Tab bar styling
active_tab_foreground   #fdf6e3
active_tab_background   #073642
inactive_tab_foreground #93A1A1
inactive_tab_background #002731
