[palettes.solarized-dark]
bg               = '#002B36'
bg_subtle        = '#133a44'
bg_muted         = '#274a52'
fg               = '#839496'
fg_dim           = '#4e6a6f'
sel_bg           = '#073642'
sel_fg           = '#93A1A1'
error            = '#DC322F'
accent           = '#268BD2'
fg_on_accent     = '#839496'
success          = '#859900'
warning          = '#B58900'
cursor           = '#586E75'
