[mgr]
cwd = { fg = "#839496" }
find_keyword = { fg = "#DC322F", bold = true, italic = true, underline = true }
find_position = { fg = "#DC322F", bold = true, italic = true }
marker_copied = { fg = "#D33682", bg = "#D33682" }
marker_cut = { fg = "#4e6a6f", bg = "#4e6a6f" }
marker_marked = { fg = "#268BD2", bg = "#268BD2" }
marker_selected = { fg = "#859900", bg = "#859900" }
count_copied = { fg = "#002B36", bg = "#4e6a6f" }
count_cut = { fg = "#002B36", bg = "#4e6a6f" }
count_selected = { fg = "#002B36", bg = "#859900" }
border_symbol = " "
border_style = { fg = "#268BD2" }

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }
perm_type = { fg = "#268BD2" }
perm_read = { fg = "#839496" }
perm_write = { fg = "#859900" }
perm_exec = { fg = "#D33682" }
perm_sep = { fg = "#4e6a6f" }
progress_label = { bold = true }
progress_normal = { fg = "#268BD2", bg = "#133a44" }
progress_error = { fg = "#D33682", bg = "#133a44" }

[mode]
normal_main = { bg = "#268BD2", fg = "#002B36", bold = true }
normal_alt  = { bg = "#133a44", fg = "#839496" }
select_main = { bg = "#4e6a6f", fg = "#002B36", bold = true }
select_alt  = { bg = "#133a44", fg = "#839496" }
unset_main = { bg = "#859900", fg = "#002B36", bold = true }
unset_alt  = { bg = "#133a44", fg = "#839496" }

[select]
border = { fg = "#268BD2" }
active = { fg = "#859900", bold = true }

[input]
border = { fg = "#268BD2" }
value = { fg = "#839496" }

[tabs]
active = { fg = "#268BD2", bold = true, bg = "#002B36" }
inactive = { fg = "#4e6a6f", bg = "#002B36" }
sep_inner = { open = "[", close = "]" }

[cmp]
border = { fg = "#268BD2", bg = "#133a44" }

[tasks]
border = { fg = "#268BD2" }
title = {}
hovered = { fg = "#4e6a6f", underline = true }

[which]
cols = 3
mask = { bg = "#133a44" }
cand = { fg = "#268BD2" }
rest = { fg = "#002B36" }
desc = { fg = "#839496" }
separator = " ▶ "
separator_style = { fg = "#839496" }

[help]
on = { fg = "#839496" }
run = { fg = "#839496" }
footer = { fg = "#002B36", bg = "#4e6a6f" }

[notify]
title_info = { fg = "#859900" }
title_warn = { fg = "#268BD2" }
title_error = { fg = "#D33682" }

[filetype]
rules = [
    { mime = "image/*", fg = "#859900" },
    { mime = "{audio,video}/*", fg = "#268BD2" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#4e6a6f" },
    { mime = "application/{pdf,doc,rtf}", fg = "#839496" },
    { url = "*", is = "orphan", bg = "#D33682" },
    { url = "*", is = "exec", fg = "#4e6a6f" },
    { url = "*", fg = "#839496" },
    { url = "*/", fg = "#268BD2" },
]
