[palettes.tokyonight]
base             = '#1a1b26'
crust            = '#4b4f64'
on_sig1          = '#1a1b26'
on_sig2          = '#c0caf5'
on_sigbg         = '#c0caf5'
red              = '#f7768e'
sig1             = '#7aa2f7'
sig2             = '#bb9af7'
sig_bg           = '#1a1b26'
sig_surface_high = '#323545'
text             = '#c0caf5'
