name = Dune

ghostty   = Dune
wezterm   = Dune
gtk       = Orchis-Dark
icons     = Colloid-Dark
wallpaper = dune_desert.png

# Waybar / rofi / swaync / yazi palette
bg        = #20201d
bg_alt    = #7d7a68
fg        = #fefbec
primary   = #ae9513
secondary = #60ac39
disabled  = #a6a28c
alert     = #d73737
