name = Catppuccin

ghostty   = Catppuccin Mocha
wezterm   = Catppuccin Mocha
gtk       = Orchis-Purple-Dark
icons     = Colloid-Catppuccin-Dark
wallpaper = catppuccin.png
nvim 			= catppuccin-mocha

# Waybar / rofi / swaync palette
bg        = #232634
bg_alt    = #51576d
fg        = #c6d0f5
primary   = #ef9f76
secondary = #8caaee
disabled  = #a6d189
alert     = #e5c890
