exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = dbus-update-activation-environment --systemd --all
exec-once = dbus-update-activation-environment --systemd XDG_CURRENT_DESKTOP=Hyprland
exec-once = mako
exec-once = hypridle
exec-once = swaybg -o "*" -i ~/Pictures/wallpapers/gruvbox/camera.png -m fill
