$background = rgba(40, 40, 40, ff)
$foreground = rgba(212, 190, 152, ff)
$accent     = rgba(69, 133, 136, ff)
$bg_subtle  = rgba(65, 62, 56, ff)
$bg_muted   = rgba(91, 85, 73, ff)

$active_border   = rgba(69, 133, 136, ff)
$inactive_border = rgba(91, 85, 73, ff)
$focus_border    = rgba(69, 133, 136, ff)

$shadow_color    = rgba(0 0 0 55)

# Optional: Add transparency variants
$background_transparent = rgba(40, 40, 40, 99)  # 60% opacity
$accent_transparent     = rgba(69, 133, 136, 66)  # 40% opacity
