# =============================================================================
# variables.conf — shared variables
# Override any of these in _variables.conf without touching this file.
# =============================================================================

$mod            = SUPER
$screenshot_dir = ~/Pictures/screenshots

# $opacity  = 0.9
$term     = foot
$term2    = kitty
$launcher = rofi -show drun -theme ~/.config/rofi/launcher.rasi
$browser  = zen-browser
$files    = thunar
$fm       = $term -e superb
$tfm      = $term -e broot
$editor   = $term -e nvim

$menu       = $launcher
$lockscreen = hyprlock
