[skin]
default = "#d9d9d9 #0c0c0c / #d9d9d9 #2a2a2a"
tree = "#494949 None / #2a2a2a None"
parent = "#9d65ff None / #878787 None"
file = "#d9d9d9 None / #9d65ff None"
directory = "#9d65ff None Bold / #9d65ff None Bold"
exe = "#9d65ff None Bold"
link = "#9d65ff None Italic"
pruning = "#494949 None Italic"
perm__ = "#2a2a2a None"
perm_r = "#9d65ff None"
perm_w = "#9d65ff None"
perm_x = "#9d65ff None"
owner = "#878787 None"
group = "#494949 None"
count = "#9d65ff #0c0c0c"
dates = "#494949 None"
sparse = "#9d65ff None"
content_extract = "#878787 None Italic"
content_match = "#d9d9d9 None Bold"
device_id_major = "#9d65ff None"
device_id_sep = "#494949 None"
device_id_minor = "#9d65ff None"
git_branch = "#d9d9d9 None Bold"
git_insertions = "#9d65ff None"
git_deletions = "#9d65ff None"
git_status_current = "#2a2a2a None"
git_status_modified = "#9d65ff None"
git_status_new = "#d9d9d9 None Bold"
git_status_ignored = "#2a2a2a None"
git_status_conflicted = "#9d65ff None Bold"
git_status_other = "#9d65ff None"
selected_line = "None #2a2a2a / None #494949"
char_match = "#d9d9d9 None Bold"
file_error = "#f4005f None Bold"
flag_label = "#878787 None"
flag_value = "#d9d9d9 None Bold"
input = "#d9d9d9 None / #d9d9d9 #2a2a2a"
status_error = "#d9d9d9 #f4005f"
status_job = "#d9d9d9 #2a2a2a"
status_normal = "#d9d9d9 #0c0c0c / #ffffff #2a2a2a"
status_italic = "#9d65ff #0c0c0c Italic / #ffffff #2a2a2a"
status_bold = "#9d65ff #0c0c0c Bold / #ffffff #2a2a2a"
status_code = "#d9d9d9 #0c0c0c / #ffffff #2a2a2a"
status_ellipsis = "#878787 #0c0c0c / #ffffff #2a2a2a"
purpose_normal = "#d9d9d9 #2a2a2a"
purpose_italic = "#9d65ff #2a2a2a Italic"
purpose_bold = "#9d65ff #2a2a2a Bold"
purpose_ellipsis = "#878787 #2a2a2a"
scrollbar_track = "#0c0c0c None / #0c0c0c None"
scrollbar_thumb = "#494949 None / #2a2a2a None"
help_paragraph = "#d9d9d9 None"
help_bold = "#9d65ff None Bold"
help_italic = "#9d65ff None Italic"
help_code = "#d9d9d9 #2a2a2a"
help_headers = "#9d65ff None Bold"
help_table_border = "#494949 None"
preview_title = "#d9d9d9 None Bold / #9d65ff None"
preview = "#d9d9d9 #0c0c0c / #9d65ff #2a2a2a"
preview_separator = "#494949 None / #2a2a2a None"
preview_line_number = "#494949 #0c0c0c"
preview_match = "None #494949"
hex_null = "#2a2a2a None"
hex_ascii_graphic = "#d9d9d9 None"
hex_ascii_whitespace = "#9d65ff None"
hex_ascii_other = "#9d65ff None"
hex_non_ascii = "#9d65ff None"
staging_area_title = "#d9d9d9 None Bold / #9d65ff None"
mode_command_mark = "#ffffff #9d65ff Bold"
good_to_bad_0 = "#98e024"
good_to_bad_1 = "#98e024"
good_to_bad_2 = "#98e024"
good_to_bad_3 = "#878787"
good_to_bad_4 = "#878787"
good_to_bad_5 = "#494949"
good_to_bad_6 = "#fd971f"
good_to_bad_7 = "#fd971f"
good_to_bad_8 = "#f4005f"
good_to_bad_9 = "#f4005f"
