$background = rgb(0c0c0c)
$foreground = rgb(d9d9d9)
$accent     = rgb(9d65ff)
$bg_subtle  = rgb(2a2a2a)
$bg_muted   = rgb(494949)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
