name = Everforest

ghostty   = Everforest Dark Hard
wezterm   = Everforest Dark Hard (Gogh)
gtk       = Orchis-Green-Dark
icons     = Colloid-Everforest-Dark
wallpaper = forest_stairs.jpg
nvim 			= everforest

# Waybar / rofi / swaync palette
bg        = #2B3339
bg_alt    = #414b50
fg        = #D5C9AB
primary   = #DBBC7F
secondary = #7FBBB3
disabled  = #7C8377
alert     = #E69875
