[skin]
default = "#cdcecf #192330 / #cdcecf #343c47"
tree = "#4f565f None / #343c47 None"
parent = "#719cd6 None / #85898f None"
file = "#cdcecf None / #719cd6 None"
directory = "#719cd6 None Bold / #719cd6 None Bold"
exe = "#719cd6 None Bold"
link = "#719cd6 None Italic"
pruning = "#4f565f None Italic"
perm__ = "#343c47 None"
perm_r = "#719cd6 None"
perm_w = "#719cd6 None"
perm_x = "#719cd6 None"
owner = "#85898f None"
group = "#4f565f None"
count = "#719cd6 #192330"
dates = "#4f565f None"
sparse = "#719cd6 None"
content_extract = "#85898f None Italic"
content_match = "#cdcecf None Bold"
device_id_major = "#719cd6 None"
device_id_sep = "#4f565f None"
device_id_minor = "#719cd6 None"
git_branch = "#cdcecf None Bold"
git_insertions = "#719cd6 None"
git_deletions = "#719cd6 None"
git_status_current = "#343c47 None"
git_status_modified = "#719cd6 None"
git_status_new = "#cdcecf None Bold"
git_status_ignored = "#343c47 None"
git_status_conflicted = "#719cd6 None Bold"
git_status_other = "#719cd6 None"
selected_line = "None #343c47 / None #4f565f"
char_match = "#cdcecf None Bold"
file_error = "#c94f6d None Bold"
flag_label = "#85898f None"
flag_value = "#cdcecf None Bold"
input = "#cdcecf None / #cdcecf #343c47"
status_error = "#cdcecf #c94f6d"
status_job = "#cdcecf #343c47"
status_normal = "#cdcecf #192330 / #cdcecf #343c47"
status_italic = "#719cd6 #192330 Italic / #cdcecf #343c47"
status_bold = "#719cd6 #192330 Bold / #cdcecf #343c47"
status_code = "#cdcecf #192330 / #cdcecf #343c47"
status_ellipsis = "#85898f #192330 / #cdcecf #343c47"
purpose_normal = "#cdcecf #343c47"
purpose_italic = "#719cd6 #343c47 Italic"
purpose_bold = "#719cd6 #343c47 Bold"
purpose_ellipsis = "#85898f #343c47"
scrollbar_track = "#192330 None / #192330 None"
scrollbar_thumb = "#4f565f None / #343c47 None"
help_paragraph = "#cdcecf None"
help_bold = "#719cd6 None Bold"
help_italic = "#719cd6 None Italic"
help_code = "#cdcecf #343c47"
help_headers = "#719cd6 None Bold"
help_table_border = "#4f565f None"
preview_title = "#cdcecf None Bold / #719cd6 None"
preview = "#cdcecf #192330 / #719cd6 #343c47"
preview_separator = "#4f565f None / #343c47 None"
preview_line_number = "#4f565f #192330"
preview_match = "None #4f565f"
hex_null = "#343c47 None"
hex_ascii_graphic = "#cdcecf None"
hex_ascii_whitespace = "#719cd6 None"
hex_ascii_other = "#719cd6 None"
hex_non_ascii = "#719cd6 None"
staging_area_title = "#cdcecf None Bold / #719cd6 None"
mode_command_mark = "#cdcecf #719cd6 Bold"
good_to_bad_0 = "#81b29a"
good_to_bad_1 = "#81b29a"
good_to_bad_2 = "#81b29a"
good_to_bad_3 = "#85898f"
good_to_bad_4 = "#85898f"
good_to_bad_5 = "#4f565f"
good_to_bad_6 = "#dbc074"
good_to_bad_7 = "#dbc074"
good_to_bad_8 = "#c94f6d"
good_to_bad_9 = "#c94f6d"
