$background = rgb(192330)
$foreground = rgb(cdcecf)
$accent     = rgb(719cd6)
$bg_subtle  = rgb(343c47)
$bg_muted   = rgb(4f565f)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
