[palettes.nightfox]
base             = '#192330'
crust            = '#4f565f'
on_sig1          = '#192330'
on_sig2          = '#cdcecf'
on_sigbg         = '#cdcecf'
red              = '#c94f6d'
sig1             = '#719cd6'
sig2             = '#9d79d6'
sig_bg           = '#192330'
sig_surface_high = '#343c47'
text             = '#cdcecf'
