[palettes.nightfox]
bg               = '#192330'
bg_subtle        = '#343c47'
bg_muted         = '#4f565f'
fg               = '#cdcecf'
fg_dim           = '#85898f'
sel_bg           = '#2b3b51'
sel_fg           = '#cdcecf'
error            = '#c94f6d'
accent           = '#719cd6'
fg_on_accent     = '#cdcecf'
success          = '#81b29a'
warning          = '#dbc074'
cursor           = '#cdcecf'
