[mgr]
cwd = { fg = "#cdcecf" }
find_keyword = { fg = "#c94f6d", bold = true, italic = true, underline = true }
find_position = { fg = "#c94f6d", bold = true, italic = true }
marker_copied = { fg = "#9d79d6", bg = "#9d79d6" }
marker_cut = { fg = "#85898f", bg = "#85898f" }
marker_marked = { fg = "#719cd6", bg = "#719cd6" }
marker_selected = { fg = "#81b29a", bg = "#81b29a" }
count_copied = { fg = "#192330", bg = "#85898f" }
count_cut = { fg = "#192330", bg = "#85898f" }
count_selected = { fg = "#192330", bg = "#81b29a" }
border_symbol = " "
border_style = { fg = "#719cd6" }

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }
perm_type = { fg = "#719cd6" }
perm_read = { fg = "#cdcecf" }
perm_write = { fg = "#81b29a" }
perm_exec = { fg = "#9d79d6" }
perm_sep = { fg = "#85898f" }
progress_label = { bold = true }
progress_normal = { fg = "#719cd6", bg = "#343c47" }
progress_error = { fg = "#9d79d6", bg = "#343c47" }

[mode]
normal_main = { bg = "#719cd6", fg = "#192330", bold = true }
normal_alt  = { bg = "#343c47", fg = "#cdcecf" }
select_main = { bg = "#85898f", fg = "#192330", bold = true }
select_alt  = { bg = "#343c47", fg = "#cdcecf" }
unset_main = { bg = "#81b29a", fg = "#192330", bold = true }
unset_alt  = { bg = "#343c47", fg = "#cdcecf" }

[select]
border = { fg = "#719cd6" }
active = { fg = "#81b29a", bold = true }

[input]
border = { fg = "#719cd6" }
value = { fg = "#cdcecf" }

[tabs]
active = { fg = "#719cd6", bold = true, bg = "#192330" }
inactive = { fg = "#85898f", bg = "#192330" }
sep_inner = { open = "[", close = "]" }

[cmp]
border = { fg = "#719cd6", bg = "#343c47" }

[tasks]
border = { fg = "#719cd6" }
title = {}
hovered = { fg = "#85898f", underline = true }

[which]
cols = 3
mask = { bg = "#343c47" }
cand = { fg = "#719cd6" }
rest = { fg = "#192330" }
desc = { fg = "#cdcecf" }
separator = " ▶ "
separator_style = { fg = "#cdcecf" }

[help]
on = { fg = "#cdcecf" }
run = { fg = "#cdcecf" }
footer = { fg = "#192330", bg = "#85898f" }

[notify]
title_info = { fg = "#81b29a" }
title_warn = { fg = "#719cd6" }
title_error = { fg = "#9d79d6" }

[filetype]
rules = [
    { mime = "image/*", fg = "#81b29a" },
    { mime = "{audio,video}/*", fg = "#719cd6" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#85898f" },
    { mime = "application/{pdf,doc,rtf}", fg = "#cdcecf" },
    { url = "*", is = "orphan", bg = "#9d79d6" },
    { url = "*", is = "exec", fg = "#85898f" },
    { url = "*", fg = "#cdcecf" },
    { url = "*/", fg = "#719cd6" },
]
