[skin]
default = "#575279 #faf4ed / #575279 #e1dbdb"
tree = "#c9c3ca None / #e1dbdb None"
parent = "#56949f None / #9892a7 None"
file = "#575279 None / #56949f None"
directory = "#56949f None Bold / #56949f None Bold"
exe = "#56949f None Bold"
link = "#56949f None Italic"
pruning = "#c9c3ca None Italic"
perm__ = "#e1dbdb None"
perm_r = "#56949f None"
perm_w = "#56949f None"
perm_x = "#56949f None"
owner = "#9892a7 None"
group = "#c9c3ca None"
count = "#56949f #faf4ed"
dates = "#c9c3ca None"
sparse = "#56949f None"
content_extract = "#9892a7 None Italic"
content_match = "#575279 None Bold"
device_id_major = "#56949f None"
device_id_sep = "#c9c3ca None"
device_id_minor = "#56949f None"
git_branch = "#575279 None Bold"
git_insertions = "#56949f None"
git_deletions = "#56949f None"
git_status_current = "#e1dbdb None"
git_status_modified = "#56949f None"
git_status_new = "#575279 None Bold"
git_status_ignored = "#e1dbdb None"
git_status_conflicted = "#56949f None Bold"
git_status_other = "#56949f None"
selected_line = "None #e1dbdb / None #c9c3ca"
char_match = "#575279 None Bold"
file_error = "#b4637a None Bold"
flag_label = "#9892a7 None"
flag_value = "#575279 None Bold"
input = "#575279 None / #575279 #e1dbdb"
status_error = "#575279 #b4637a"
status_job = "#575279 #e1dbdb"
status_normal = "#575279 #faf4ed / #575279 #e1dbdb"
status_italic = "#56949f #faf4ed Italic / #575279 #e1dbdb"
status_bold = "#56949f #faf4ed Bold / #575279 #e1dbdb"
status_code = "#575279 #faf4ed / #575279 #e1dbdb"
status_ellipsis = "#9892a7 #faf4ed / #575279 #e1dbdb"
purpose_normal = "#575279 #e1dbdb"
purpose_italic = "#56949f #e1dbdb Italic"
purpose_bold = "#56949f #e1dbdb Bold"
purpose_ellipsis = "#9892a7 #e1dbdb"
scrollbar_track = "#faf4ed None / #faf4ed None"
scrollbar_thumb = "#c9c3ca None / #e1dbdb None"
help_paragraph = "#575279 None"
help_bold = "#56949f None Bold"
help_italic = "#56949f None Italic"
help_code = "#575279 #e1dbdb"
help_headers = "#56949f None Bold"
help_table_border = "#c9c3ca None"
preview_title = "#575279 None Bold / #56949f None"
preview = "#575279 #faf4ed / #56949f #e1dbdb"
preview_separator = "#c9c3ca None / #e1dbdb None"
preview_line_number = "#c9c3ca #faf4ed"
preview_match = "None #c9c3ca"
hex_null = "#e1dbdb None"
hex_ascii_graphic = "#575279 None"
hex_ascii_whitespace = "#56949f None"
hex_ascii_other = "#56949f None"
hex_non_ascii = "#56949f None"
staging_area_title = "#575279 None Bold / #56949f None"
mode_command_mark = "#575279 #56949f Bold"
good_to_bad_0 = "#286983"
good_to_bad_1 = "#286983"
good_to_bad_2 = "#286983"
good_to_bad_3 = "#9892a7"
good_to_bad_4 = "#9892a7"
good_to_bad_5 = "#c9c3ca"
good_to_bad_6 = "#ea9d34"
good_to_bad_7 = "#ea9d34"
good_to_bad_8 = "#b4637a"
good_to_bad_9 = "#b4637a"
