$background = rgb(faf4ed)
$foreground = rgb(575279)
$accent     = rgb(56949f)
$bg_subtle  = rgb(e1dbdb)
$bg_muted   = rgb(c9c3ca)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
