[palettes.rosepine]
base             = '#faf4ed'
crust            = '#c9c3ca'
on_sig1          = '#faf4ed'
on_sig2          = '#575279'
on_sigbg         = '#575279'
red              = '#b4637a'
sig1             = '#56949f'
sig2             = '#907aa9'
sig_bg           = '#faf4ed'
sig_surface_high = '#e1dbdb'
text             = '#575279'
