[palettes.rosepine]
bg               = '#faf4ed'
bg_subtle        = '#e1dbdb'
bg_muted         = '#c9c3ca'
fg               = '#575279'
fg_dim           = '#9892a7'
sel_bg           = '#dfdad9'
sel_fg           = '#575279'
error            = '#b4637a'
accent           = '#56949f'
fg_on_accent     = '#575279'
success          = '#286983'
warning          = '#ea9d34'
cursor           = '#cecacd'
