[colors.primary]
background = "#161616"
foreground = "#f2f4f8"

[colors.cursor]
text   = "#161616"
cursor = "#f2f4f8"

[colors.selection]
text       = "#161616"
background = "#f2f4f8"

[colors.normal]
black   = "#262626"
red     = "#ee5396"
green   = "#42be65"
yellow  = "#82cfff"
blue    = "#33b1ff"
magenta = "#ff7eb6"
cyan    = "#3ddbd9"
white   = "#dde1e6"

[colors.bright]
black   = "#393939"
red     = "#ee5396"
green   = "#42be65"
yellow  = "#82cfff"
blue    = "#33b1ff"
magenta = "#ff7eb6"
cyan    = "#3ddbd9"
white   = "#ffffff"
