[skin]
default = "#f2f4f8 #161616 / #f2f4f8 #373737"
tree = "#585859 None / #373737 None"
parent = "#33b1ff None / #9a9b9d None"
file = "#f2f4f8 None / #33b1ff None"
directory = "#33b1ff None Bold / #33b1ff None Bold"
exe = "#33b1ff None Bold"
link = "#33b1ff None Italic"
pruning = "#585859 None Italic"
perm__ = "#373737 None"
perm_r = "#33b1ff None"
perm_w = "#33b1ff None"
perm_x = "#33b1ff None"
owner = "#9a9b9d None"
group = "#585859 None"
count = "#33b1ff #161616"
dates = "#585859 None"
sparse = "#33b1ff None"
content_extract = "#9a9b9d None Italic"
content_match = "#f2f4f8 None Bold"
device_id_major = "#33b1ff None"
device_id_sep = "#585859 None"
device_id_minor = "#33b1ff None"
git_branch = "#f2f4f8 None Bold"
git_insertions = "#33b1ff None"
git_deletions = "#33b1ff None"
git_status_current = "#373737 None"
git_status_modified = "#33b1ff None"
git_status_new = "#f2f4f8 None Bold"
git_status_ignored = "#373737 None"
git_status_conflicted = "#33b1ff None Bold"
git_status_other = "#33b1ff None"
selected_line = "None #373737 / None #585859"
char_match = "#f2f4f8 None Bold"
file_error = "#ee5396 None Bold"
flag_label = "#9a9b9d None"
flag_value = "#f2f4f8 None Bold"
input = "#f2f4f8 None / #f2f4f8 #373737"
status_error = "#f2f4f8 #ee5396"
status_job = "#f2f4f8 #373737"
status_normal = "#f2f4f8 #161616 / #161616 #373737"
status_italic = "#33b1ff #161616 Italic / #161616 #373737"
status_bold = "#33b1ff #161616 Bold / #161616 #373737"
status_code = "#f2f4f8 #161616 / #161616 #373737"
status_ellipsis = "#9a9b9d #161616 / #161616 #373737"
purpose_normal = "#f2f4f8 #373737"
purpose_italic = "#33b1ff #373737 Italic"
purpose_bold = "#33b1ff #373737 Bold"
purpose_ellipsis = "#9a9b9d #373737"
scrollbar_track = "#161616 None / #161616 None"
scrollbar_thumb = "#585859 None / #373737 None"
help_paragraph = "#f2f4f8 None"
help_bold = "#33b1ff None Bold"
help_italic = "#33b1ff None Italic"
help_code = "#f2f4f8 #373737"
help_headers = "#33b1ff None Bold"
help_table_border = "#585859 None"
preview_title = "#f2f4f8 None Bold / #33b1ff None"
preview = "#f2f4f8 #161616 / #33b1ff #373737"
preview_separator = "#585859 None / #373737 None"
preview_line_number = "#585859 #161616"
preview_match = "None #585859"
hex_null = "#373737 None"
hex_ascii_graphic = "#f2f4f8 None"
hex_ascii_whitespace = "#33b1ff None"
hex_ascii_other = "#33b1ff None"
hex_non_ascii = "#33b1ff None"
staging_area_title = "#f2f4f8 None Bold / #33b1ff None"
mode_command_mark = "#161616 #33b1ff Bold"
good_to_bad_0 = "#42be65"
good_to_bad_1 = "#42be65"
good_to_bad_2 = "#42be65"
good_to_bad_3 = "#9a9b9d"
good_to_bad_4 = "#9a9b9d"
good_to_bad_5 = "#585859"
good_to_bad_6 = "#82cfff"
good_to_bad_7 = "#82cfff"
good_to_bad_8 = "#ee5396"
good_to_bad_9 = "#ee5396"
