$background = rgb(161616)
$foreground = rgb(f2f4f8)
$accent     = rgb(33b1ff)
$bg_subtle  = rgb(373737)
$bg_muted   = rgb(585859)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
