[palettes.oxocarbon]
bg               = '#161616'
bg_subtle        = '#373737'
bg_muted         = '#585859'
fg               = '#f2f4f8'
fg_dim           = '#9a9b9d'
sel_bg           = '#f2f4f8'
sel_fg           = '#161616'
error            = '#ee5396'
accent           = '#33b1ff'
fg_on_accent     = '#f2f4f8'
success          = '#42be65'
warning          = '#82cfff'
cursor           = '#f2f4f8'
