# : Manager [[[

[mgr]
cwd = { fg = "#f2f4f8" }

# Find
find_keyword = { fg = "#ee5396", bold = true, italic = true, underline = true }
find_position = { fg = "#ee5396", bold = true, italic = true }

# Marker
marker_copied = { fg = "#3ddbd9", bg = "#3ddbd9" }
marker_cut = { fg = "#ffffff", bg = "#ffffff" }
marker_marked = { fg = "#33b1ff", bg = "#33b1ff" }
marker_selected = { fg = "#515151", bg = "#515151" }

# Count
count_copied = { fg = "#161616", bg = "#ffffff" }
count_cut = { fg = "#161616", bg = "#ffffff" }
count_selected = { fg = "#262626", bg = "#515151" }

# Border
border_symbol = " "
border_style = { fg = "#33b1ff" }

# : ]]]


# : Status [[[

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }

# Permissions
perm_type = { fg = "#33b1ff" }
perm_read = { fg = "#f2f4f8" }
perm_write = { fg = "#515151" }
perm_exec = { fg = "#3ddbd9" }
perm_sep = { fg = "#ffffff" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#33b1ff", bg = "#262626" }
progress_error = { fg = "#3ddbd9", bg = "#262626" }

[mode]
normal_main = { bg = "#33b1ff", fg = "#262626", bold = true }
normal_alt  = { bg = "#262626", fg = "#f2f4f8" }

select_main = { bg = "#ffffff", fg = "#262626", bold = true }
select_alt  = { bg = "#262626", fg = "#f2f4f8" }

unset_main = { bg = "#515151", fg = "#262626", bold = true }
unset_alt  = { bg = "#262626", fg = "#f2f4f8" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#33b1ff" }
active = { fg = "#515151", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#33b1ff" }
value = { fg = "#f2f4f8" }

# : ]]]


# : Tabs [[[

[tabs]
active = { fg = "#33b1ff", bold = true, bg = "#161616" }
inactive = { fg = "#ffffff", bg = "#161616" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#33b1ff", bg = "#393939" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#33b1ff" }
title = {}
hovered = { fg = "#ffffff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#262626" }
cand = { fg = "#33b1ff" }
rest = { fg = "#262626" }
desc = { fg = "#f2f4f8" }
separator = " ▶ "
separator_style = { fg = "#f2f4f8" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f2f4f8" }
run = { fg = "#f2f4f8" }
footer = { fg = "#262626", bg = "#ffffff" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#515151" }
title_warn = { fg = "#33b1ff" }
title_error = { fg = "#3ddbd9" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    { mime = "image/*", fg = "#515151" },
    { mime = "{audio,video}/*", fg = "#33b1ff" },

    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#ffffff" },

    { mime = "application/{pdf,doc,rtf}", fg = "#f2f4f8" },

    { url = "*", is = "orphan", bg = "#3ddbd9" },
    { url = "*", is = "exec", fg = "#ffffff" },

    { url = "*", fg = "#f2f4f8" },
    { url = "*/", fg = "#33b1ff" },
]

# : ]]]
