name = Nord

ghostty   = Nord
wezterm   = Nord (Gogh)
gtk       = Orchis-Dark-Nord
icons     = Colloid-Nord-Dark
wallpaper = ign_unsplash7.png
nvim			= nordfox
btop			= nord

# Waybar / rofi / swaync palette
bg        = #2e3440
bg_alt    = #3b4252
fg        = #d8dee9
primary   = #ebcb8b
secondary = #81a1c1
disabled  = #4c566a
alert     = #d08770
