#!/usr/bin/env bash

# Monitor switcher for:
# - Sway
# - Hyprland
# - Qtile Wayland


# Detect compositor
if hyprctl monitors >/dev/null 2>&1; then

    COMPOSITOR="hyprland"

elif swaymsg -t get_outputs >/dev/null 2>&1; then

    COMPOSITOR="sway"

elif qtile cmd-obj -o cmd -f status >/dev/null 2>&1; then

    COMPOSITOR="qtile"

else
    echo "No supported Wayland compositor detected" >&2
    exit 1
fi


CHOICE=$(printf \
"1. HDMI Only\n2. Laptop Only\n3. Both Displays" \
| rofi -dmenu -p "Select:")


[ -z "$CHOICE" ] && exit 0



qtile_refresh() {

    if [ "$COMPOSITOR" = "qtile" ]; then
        sleep 3

        qtile cmd-obj \
            -o cmd \
            -f reconfigure_screens \
            >/dev/null 2>&1
    fi

}

apply_sway() {

    case "$CHOICE" in

        "1. HDMI Only")

            swaymsg output eDP-1 disable
            swaymsg output HDMI-A-1 enable mode 1920x1080@60Hz

            ;;


        "2. Laptop Only")

            swaymsg output HDMI-A-1 disable
            swaymsg output eDP-1 enable mode 1920x1080@120Hz

            ;;


        "3. Both Displays")

            swaymsg output eDP-1 enable mode 1920x1080@120Hz
            swaymsg output HDMI-A-1 enable \
                mode 1920x1080@60Hz \
                position 1920,0

            ;;

    esac

}



apply_hyprland() {

    case "$CHOICE" in

        "1. HDMI Only")

            hyprctl keyword monitor "eDP-1,disable"
            hyprctl keyword monitor \
                "HDMI-A-1,1920x1080@60,0x0,1"

            ;;


        "2. Laptop Only")

            hyprctl keyword monitor "HDMI-A-1,disable"
            hyprctl keyword monitor \
                "eDP-1,1920x1080@120,0x0,1"

            ;;


        "3. Both Displays")

            hyprctl keyword monitor \
                "eDP-1,1920x1080@120,0x0,1"

            hyprctl keyword monitor \
                "HDMI-A-1,1920x1080@60,1920x0,1"

            ;;

    esac

}



apply_qtile() {

    case "$CHOICE" in


        "1. HDMI Only")

					wlr-randr --output eDP-1 --off
          wlr-randr --output HDMI-A-1 --on
            ;;



        "2. Laptop Only")
					wlr-randr --output eDP-1 --on
          wlr-randr --output HDMI-A-1 --off

            ;;



        "3. Both Displays")
					wlr-randr --output eDP-1 --on
          wlr-randr --output HDMI-A-1 --on

            ;;

    esac


    qtile_refresh

}



case "$COMPOSITOR" in


    sway)

        apply_sway

        ;;


    hyprland)

        apply_hyprland

        ;;


    qtile)

        apply_qtile

        ;;


esac
