vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "destiny"
vim.o.termguicolors = true
vim.o.background = "dark"

-- ─── Palette ─────────────────────────────────────────────────────────────────
local c = {
  bg          = "#0C1319",  -- ink black
  bg_subtle   = "#1A242D",  -- slightly lifted dark
  bg_muted    = "#443E39",  -- taupe, mid-dark
  bg_sel      = "#2A2420",  -- selection bg (between bg and bg_muted)
  fg          = "#D1D2D7",  -- pale slate
  fg_dim      = "#748496",  -- slate grey
  fg_faint    = "#6D675F",  -- dim grey
  accent      = "#F5C993",  -- apricot cream / Traveler light
  accent_dim  = "#ECD5BB",  -- almond cream / softer warm
  copper      = "#B8845C",  -- faded copper
  ash         = "#725E4E",  -- ash brown
  denim       = "#698CAF",  -- dusty denim
  none        = "NONE",
}

-- ─── Helper ───────────────────────────────────────────────────────────────────
local hi = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- ─── Editor UI ────────────────────────────────────────────────────────────────
hi("Normal",          { fg = c.fg,        bg = c.bg })
hi("NormalFloat",     { fg = c.fg,        bg = c.bg_subtle })
hi("NormalNC",        { fg = c.fg_dim,    bg = c.bg })
hi("SignColumn",      { fg = c.fg_dim,    bg = c.bg })
hi("ColorColumn",     {                   bg = c.bg_subtle })
hi("CursorLine",      {                   bg = c.bg_subtle })
hi("CursorLineNr",    { fg = c.accent,    bg = c.bg_subtle, bold = true })
hi("CursorColumn",    {                   bg = c.bg_subtle })
hi("LineNr",          { fg = c.bg_muted })
hi("Cursor",          { fg = c.bg,        bg = c.accent_dim })
hi("TermCursor",      { fg = c.bg,        bg = c.accent })
hi("Visual",          { fg = c.bg,        bg = c.denim })
hi("VisualNOS",       { fg = c.bg,        bg = c.denim })
hi("IncSearch",       { fg = c.bg,        bg = c.accent, bold = true })
hi("Search",          { fg = c.bg,        bg = c.accent_dim })
hi("Substitute",      { fg = c.bg,        bg = c.copper })
hi("MatchParen",      { fg = c.accent,    bg = c.none, bold = true, underline = true })
hi("StatusLine",      { fg = c.fg,        bg = c.bg_muted })
hi("StatusLineNC",    { fg = c.fg_faint,  bg = c.bg_subtle })
hi("WinSeparator",    { fg = c.bg_muted })
hi("VertSplit",       { fg = c.bg_muted })
hi("TabLine",         { fg = c.fg_dim,    bg = c.bg_subtle })
hi("TabLineFill",     {                   bg = c.bg })
hi("TabLineSel",      { fg = c.accent,    bg = c.bg_muted, bold = true })
hi("Pmenu",           { fg = c.fg,        bg = c.bg_subtle })
hi("PmenuSel",        { fg = c.bg,        bg = c.denim, bold = true })
hi("PmenuSbar",       {                   bg = c.bg_muted })
hi("PmenuThumb",      {                   bg = c.fg_dim })
hi("WildMenu",        { fg = c.bg,        bg = c.accent })
hi("Folded",          { fg = c.fg_dim,    bg = c.bg_subtle, italic = true })
hi("FoldColumn",      { fg = c.bg_muted,  bg = c.bg })
hi("EndOfBuffer",     { fg = c.bg_subtle })
hi("NonText",         { fg = c.bg_muted })
hi("SpecialKey",      { fg = c.bg_muted })
hi("Whitespace",      { fg = c.bg_muted })
hi("Directory",       { fg = c.denim })
hi("Title",           { fg = c.accent,    bold = true })
hi("Question",        { fg = c.denim })
hi("MoreMsg",         { fg = c.denim })
hi("ModeMsg",         { fg = c.accent,    bold = true })
hi("MsgArea",         { fg = c.fg })
hi("ErrorMsg",        { fg = c.copper,    bold = true })
hi("WarningMsg",      { fg = c.accent })
hi("QuickFixLine",    { fg = c.bg,        bg = c.denim })
hi("SpellBad",        { undercurl = true, sp = c.copper })
hi("SpellCap",        { undercurl = true, sp = c.denim })
hi("SpellLocal",      { undercurl = true, sp = c.accent })
hi("SpellRare",       { undercurl = true, sp = c.ash })

-- ─── Syntax ───────────────────────────────────────────────────────────────────
hi("Comment",         { fg = c.fg_faint,  italic = true })
hi("Constant",        { fg = c.accent_dim })
hi("String",          { fg = c.accent })
hi("Character",       { fg = c.accent })
hi("Number",          { fg = c.copper })
hi("Boolean",         { fg = c.copper,    bold = true })
hi("Float",           { fg = c.copper })
hi("Identifier",      { fg = c.fg })
hi("Function",        { fg = c.denim,     bold = true })
hi("Statement",       { fg = c.accent_dim, bold = true })
hi("Conditional",     { fg = c.accent_dim, bold = true })
hi("Repeat",          { fg = c.accent_dim, bold = true })
hi("Label",           { fg = c.accent_dim })
hi("Operator",        { fg = c.fg_dim })
hi("Keyword",         { fg = c.accent_dim, bold = true })
hi("Exception",       { fg = c.copper,    bold = true })
hi("PreProc",         { fg = c.denim })
hi("Include",         { fg = c.denim })
hi("Define",          { fg = c.denim })
hi("Macro",           { fg = c.denim })
hi("PreCondit",       { fg = c.denim })
hi("Type",            { fg = c.accent,    bold = true })
hi("StorageClass",    { fg = c.accent })
hi("Structure",       { fg = c.accent })
hi("Typedef",         { fg = c.accent })
hi("Special",         { fg = c.copper })
hi("SpecialChar",     { fg = c.copper })
hi("Tag",             { fg = c.denim })
hi("Delimiter",       { fg = c.fg_dim })
hi("SpecialComment",  { fg = c.fg_dim,    italic = true })
hi("Debug",           { fg = c.copper })
hi("Underlined",      { underline = true })
hi("Ignore",          { fg = c.bg_muted })
hi("Error",           { fg = c.copper,    bold = true })
hi("Todo",            { fg = c.bg,        bg = c.accent, bold = true })

-- ─── Treesitter ───────────────────────────────────────────────────────────────
hi("@variable",               { fg = c.fg })
hi("@variable.builtin",       { fg = c.copper,     italic = true })
hi("@variable.parameter",     { fg = c.fg_dim })
hi("@variable.member",        { fg = c.fg })
hi("@constant",               { fg = c.accent_dim })
hi("@constant.builtin",       { fg = c.copper,     bold = true })
hi("@constant.macro",         { fg = c.denim })
hi("@module",                 { fg = c.denim })
hi("@string",                 { fg = c.accent })
hi("@string.escape",          { fg = c.copper })
hi("@string.special",         { fg = c.copper })
hi("@character",              { fg = c.accent })
hi("@number",                 { fg = c.copper })
hi("@float",                  { fg = c.copper })
hi("@boolean",                { fg = c.copper,     bold = true })
hi("@function",               { fg = c.denim,      bold = true })
hi("@function.builtin",       { fg = c.denim,      italic = true })
hi("@function.macro",         { fg = c.denim })
hi("@function.call",          { fg = c.denim })
hi("@function.method",        { fg = c.denim,      bold = true })
hi("@function.method.call",   { fg = c.denim })
hi("@constructor",            { fg = c.accent,     bold = true })
hi("@operator",               { fg = c.fg_dim })
hi("@keyword",                { fg = c.accent_dim, bold = true })
hi("@keyword.function",       { fg = c.accent_dim, bold = true })
hi("@keyword.return",         { fg = c.copper,     bold = true })
hi("@keyword.operator",       { fg = c.fg_dim })
hi("@keyword.import",         { fg = c.denim })
hi("@keyword.conditional",    { fg = c.accent_dim, bold = true })
hi("@keyword.repeat",         { fg = c.accent_dim, bold = true })
hi("@keyword.exception",      { fg = c.copper,     bold = true })
hi("@type",                   { fg = c.accent,     bold = true })
hi("@type.builtin",           { fg = c.accent })
hi("@type.definition",        { fg = c.accent,     bold = true })
hi("@attribute",              { fg = c.denim })
hi("@property",               { fg = c.fg })
hi("@comment",                { fg = c.fg_faint,   italic = true })
hi("@comment.documentation",  { fg = c.fg_dim,     italic = true })
hi("@punctuation",            { fg = c.fg_dim })
hi("@punctuation.bracket",    { fg = c.fg_dim })
hi("@punctuation.delimiter",  { fg = c.fg_dim })
hi("@tag",                    { fg = c.denim })
hi("@tag.attribute",          { fg = c.accent })
hi("@tag.delimiter",          { fg = c.fg_dim })
hi("@markup.heading",         { fg = c.accent,     bold = true })
hi("@markup.link",            { fg = c.denim,      underline = true })
hi("@markup.link.label",      { fg = c.denim })
hi("@markup.raw",             { fg = c.copper })
hi("@markup.strong",          { bold = true })
hi("@markup.italic",          { italic = true })
hi("@diff.plus",              { fg = c.denim })
hi("@diff.minus",             { fg = c.copper })
hi("@diff.delta",             { fg = c.accent })

-- ─── LSP ──────────────────────────────────────────────────────────────────────
hi("DiagnosticError",         { fg = c.copper })
hi("DiagnosticWarn",          { fg = c.accent })
hi("DiagnosticInfo",          { fg = c.denim })
hi("DiagnosticHint",          { fg = c.fg_dim })
hi("DiagnosticOk",            { fg = c.denim })
hi("DiagnosticUnderlineError",{ undercurl = true, sp = c.copper })
hi("DiagnosticUnderlineWarn", { undercurl = true, sp = c.accent })
hi("DiagnosticUnderlineInfo", { undercurl = true, sp = c.denim })
hi("DiagnosticUnderlineHint", { undercurl = true, sp = c.fg_dim })
hi("DiagnosticVirtualTextError",{ fg = c.copper,  italic = true })
hi("DiagnosticVirtualTextWarn", { fg = c.accent,  italic = true })
hi("DiagnosticVirtualTextInfo", { fg = c.denim,   italic = true })
hi("DiagnosticVirtualTextHint", { fg = c.fg_dim,  italic = true })
hi("LspReferenceText",        { bg = c.bg_sel })
hi("LspReferenceRead",        { bg = c.bg_sel })
hi("LspReferenceWrite",       { bg = c.bg_sel, underline = true })
hi("LspInlayHint",            { fg = c.fg_faint,   italic = true, bg = c.bg_subtle })

-- ─── nvim-cmp ─────────────────────────────────────────────────────────────────
hi("CmpItemAbbr",             { fg = c.fg })
hi("CmpItemAbbrMatch",        { fg = c.accent,  bold = true })
hi("CmpItemAbbrMatchFuzzy",   { fg = c.accent_dim })
hi("CmpItemKind",             { fg = c.denim })
hi("CmpItemMenu",             { fg = c.fg_faint })

-- ─── Telescope ────────────────────────────────────────────────────────────────
hi("TelescopeBorder",         { fg = c.bg_muted })
hi("TelescopeNormal",         { fg = c.fg,      bg = c.bg_subtle })
hi("TelescopePromptBorder",   { fg = c.denim })
hi("TelescopePromptNormal",   { fg = c.fg,      bg = c.bg_subtle })
hi("TelescopePromptPrefix",   { fg = c.accent })
hi("TelescopeSelection",      { fg = c.bg,      bg = c.denim })
hi("TelescopeSelectionCaret", { fg = c.accent })
hi("TelescopeMatching",       { fg = c.accent,  bold = true })
hi("TelescopePreviewTitle",   { fg = c.bg,      bg = c.denim })
hi("TelescopePromptTitle",    { fg = c.bg,      bg = c.accent })
hi("TelescopeResultsTitle",   { fg = c.bg,      bg = c.bg_muted })

-- ─── GitSigns ─────────────────────────────────────────────────────────────────
hi("GitSignsAdd",             { fg = c.denim })
hi("GitSignsChange",          { fg = c.accent })
hi("GitSignsDelete",          { fg = c.copper })

-- ─── Indent Blankline ─────────────────────────────────────────────────────────
hi("IblIndent",               { fg = c.bg_subtle })
hi("IblScope",                { fg = c.bg_muted })

-- ─── Which-key ────────────────────────────────────────────────────────────────
hi("WhichKey",                { fg = c.accent })
hi("WhichKeyDesc",            { fg = c.fg })
hi("WhichKeyGroup",           { fg = c.denim,   bold = true })
hi("WhichKeySeparator",       { fg = c.fg_faint })
hi("WhichKeyFloat",           { bg = c.bg_subtle })

-- ─── Diff ─────────────────────────────────────────────────────────────────────
hi("DiffAdd",                 { fg = c.denim,   bg = "#0d1e28" })
hi("DiffChange",              { fg = c.accent,  bg = "#211d0f" })
hi("DiffDelete",              { fg = c.copper,  bg = "#1e100a" })
hi("DiffText",                { fg = c.accent,  bg = "#2e260f", bold = true })
hi("Added",                   { fg = c.denim })
hi("Changed",                 { fg = c.accent })
hi("Removed",                 { fg = c.copper })

-- ─── Misc plugins ─────────────────────────────────────────────────────────────
hi("NvimTreeNormal",          { fg = c.fg,      bg = c.bg_subtle })
hi("NvimTreeFolderIcon",      { fg = c.denim })
hi("NvimTreeRootFolder",      { fg = c.accent,  bold = true })
hi("NvimTreeGitDirty",        { fg = c.accent })
hi("NvimTreeGitNew",          { fg = c.denim })
hi("NvimTreeGitDeleted",      { fg = c.copper })
hi("NeoTreeNormal",           { fg = c.fg,      bg = c.bg_subtle })
hi("NeoTreeRootName",         { fg = c.accent,  bold = true })
hi("NeoTreeGitModified",      { fg = c.accent })
hi("NeoTreeGitAdded",         { fg = c.denim })
hi("NeoTreeGitDeleted",       { fg = c.copper })
hi("FlashLabel",              { fg = c.bg,      bg = c.accent,  bold = true })
hi("FlashCurrent",            { fg = c.bg,      bg = c.copper })
hi("MiniStatuslineFilename",  { fg = c.fg,      bg = c.bg_muted })
hi("MiniStatuslineModeNormal",{ fg = c.bg,      bg = c.accent,  bold = true })
hi("MiniStatuslineModeInsert",{ fg = c.bg,      bg = c.denim,   bold = true })
hi("MiniStatuslineModeVisual",{ fg = c.bg,      bg = c.copper,  bold = true })
hi("NotifyERRORBorder",       { fg = c.copper })
hi("NotifyERRORTitle",        { fg = c.copper,  bold = true })
hi("NotifyWARNBorder",        { fg = c.accent })
hi("NotifyWARNTitle",         { fg = c.accent,  bold = true })
hi("NotifyINFOBorder",        { fg = c.denim })
hi("NotifyINFOTitle",         { fg = c.denim,   bold = true })
