[colors.primary]
background = "#282828"
foreground = "#d4be98"

[colors.cursor]
text   = "#282828"
cursor = "#b8a383"

[colors.selection]
text       = "#d4be98"
background = "#e78a4e"

[colors.normal]
black   = "#2c2620"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#458588"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#a9b665"

[colors.bright]
black   = "#6e6a68"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#fbf1c7"
