$background = rgb(282828)
$foreground = rgb(d4be98)
$accent     = rgb(458588)
$bg_subtle  = rgb(413e38)
$bg_muted   = rgb(5b5549)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
