[palettes.gruvbox-material]
base             = '#282828'
crust            = '#5b5549'
on_sig1          = '#282828'
on_sig2          = '#d4be98'
on_sigbg         = '#d4be98'
red              = '#ea6962'
sig1             = '#458588'
sig2             = '#d3869b'
sig_bg           = '#282828'
sig_surface_high = '#413e38'
text             = '#d4be98'
