# : Manager [[[

[mgr]
cwd = { fg = "#d4be98" }

# Tab
tab_active = { fg = "#2c2620", bg = "#7daea3", bold = true }
tab_inactive = { fg = "#d4be98", bg = "#6e6a68" }
tab_width = 1

# Find
find_keyword = { fg = "#ea6962", bold = true, italic = true, underline = true }
find_position = { fg = "#ea6962", bold = true, italic = true }

# Marker
marker_copied = { fg = "#d8a657", bg = "#d8a657" }
marker_cut = { fg = "#fbf1c7", bg = "#fbf1c7" }
marker_marked = { fg = "#7daea3", bg = "#7daea3" }
marker_selected = { fg = "#8b8786", bg = "#8b8786" }

# Count
count_copied = { fg = "#282828", bg = "#fbf1c7" }
count_cut = { fg = "#282828", bg = "#fbf1c7" }
count_selected = { fg = "#2c2620", bg = "#8b8786" }

# Border
border_symbol = " "
border_style  = { fg = "#7daea3" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#6e6a68", fg = "#7daea3" }

[mode]
# Mode
normal_main = { bg = "#7daea3", fg = "#2c2620", bold = true }
normal_alt  = { bg = "#6e6a68", fg = "#d4be98" }

# Select mode
select_main = { bg = "#fbf1c7", fg = "#2c2620", bold = true }
select_alt  = { bg = "#6e6a68", fg = "#d4be98" }

# Unset mode
unset_main = { bg = "#8b8786", fg = "#2c2620", bold = true }
unset_alt  = { bg = "#6e6a68", fg = "#d4be98" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#7daea3", bg = "#6e6a68" }
progress_error = { fg = "#d8a657", bg = "#6e6a68" }

# Permissions
permissions_t = { fg = "#7daea3" }
permissions_w = { fg = "#8b8786" }
permissions_x = { fg = "#d8a657" }
permissions_r = { fg = "#d4be98" }
permissions_s = { fg = "#fbf1c7" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#7daea3" }
active = { fg = "#8b8786", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#7daea3" }
value = { fg = "#d4be98" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#7daea3", bold = true, bg = "#282828" }
inactive = { fg = "#fbf1c7", bg = "#282828" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#7daea3", bg = "#6e6a68" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#7daea3" }
title = {}
hovered = { fg = "#fbf1c7", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#6e6a68" }
cand = { fg = "#7daea3" }
rest = { fg = "#2c2620" }
desc = { fg = "#d4be98" }
separator = " ▶ "
separator_style = { fg = "#d4be98" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#d4be98" }
run = { fg = "#d4be98" }
footer = { fg = "#2c2620", bg = "#fbf1c7" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#8b8786" }
title_warn = { fg = "#7daea3" }
title_error = { fg = "#d8a657" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#8b8786" },

    # Media
    { mime = "{audio,video}/*", fg = "#7daea3" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#fbf1c7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#d4be98" },

    # Special files
    { name = "*", is = "orphan", bg = "#d8a657" },
    { name = "*", is = "exec", fg = "#fbf1c7" },

    # Fallback
    { name = "*", fg = "#d4be98" },
    { name = "*/", fg = "#7daea3" },
]

# : ]]]
