#!/bin/bash

# Detect which compositor is running
if pgrep -x "Hyprland" > /dev/null; then
    COMPOSITOR="hyprland"
elif pgrep -x "sway" > /dev/null; then
    COMPOSITOR="sway"
elif pgrep -x "qtile" > /dev/null; then
    COMPOSITOR="qtile"
else
    exit 0
fi


# Hide layout indicator on Qtile Wayland
if [ "$COMPOSITOR" = "qtile" ]; then
    exit 0
fi


get_layout_sway() {
    # Auto-detect first keyboard device identifier
    ID=$(swaymsg -t get_inputs | jq -r '.[] | select(.type=="keyboard") | .identifier' | head -n1)

    if [ -z "$ID" ]; then
        exit 0
    fi

    swaymsg -t get_inputs | jq -r \
        --arg id "$ID" \
        '.[] | select(.identifier == $id) | .xkb_active_layout_name'
}


get_layout_hyprland() {
    # Get active keyboard layout from Hyprland
    hyprctl devices -j | jq -r '.keyboards[] | select(.main == true) | .active_keymap'
}


# Get layout based on compositor
case "$COMPOSITOR" in
    sway)
        layout=$(get_layout_sway)
        ;;
    hyprland)
        layout=$(get_layout_hyprland)
        ;;
esac


# Normalize to short codes
if [[ "$layout" == *"English"* ]] || [[ "$layout" == *"US"* ]] || [[ "$layout" == "us" ]]; then
    echo "US"
elif [[ "$layout" == *"German"* ]] || [[ "$layout" == *"DE"* ]] || [[ "$layout" == "de" ]]; then
    echo "DE"
else
    echo "$layout"
fi
