conky.config = {
    background = true,
    update_interval = 1,  -- Update every second
    total_run_times = 0,  -- Keep running indefinitely
    minimum_width = 300,  -- Adjust the width to fit your needs
    maximum_width = 500,  -- Adjust the width to fit your needs
    alignment = 'top_right',  -- Position it where you want on the screen
    gap_x = 10,
    gap_y = 10,

 -- Windows (same as above)
  own_window = true,
  own_window_argb_value = 150,
  own_window_argb_visual = true,
  own_window_class = 'Conky',
  own_window_colour = '#2E3440',
  own_window_transparent = true,
  own_window_title = 'qtile_conky_left',
  own_window_type = 'override',
   font = 'monospace:size=10',  -- Set font size and type
    draw_shades = false,  -- Remove background shading
    use_xft = true,  -- Enable Xft for better font rendering
    double_buffer = true,  -- Prevent flickering
};

conky.text = [[
${execi 1 journalctl -p crit -f -n 5}
]];

