$background = rgb(282828)
$foreground = rgb(ebdbb2)
$accent     = rgb(458588)
$bg_subtle  = rgb(45423c)
$bg_muted   = rgb(625d51)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
