[palettes.gruvbox]
bg               = '#282828'
bg_subtle        = '#45423c'
bg_muted         = '#625d51'
fg               = '#ebdbb2'
fg_dim           = '#9d937a'
sel_bg           = '#d65d0e'
sel_fg           = '#ebdbb2'
error            = '#cc241d'
accent           = '#458588'
fg_on_accent     = '#ebdbb2'
success          = '#98971a'
warning          = '#d79921'
cursor           = '#bdae93'
