# : Manager [[[

[mgr]
cwd = { fg = "#ebdbb2" }

# Tab
tab_active = { fg = "#3c3836", bg = "#458588", bold = true }
tab_inactive = { fg = "#ebdbb2", bg = "#928374" }
tab_width = 1

# Find
find_keyword = { fg = "#cc241d", bold = true, italic = true, underline = true }
find_position = { fg = "#cc241d", bold = true, italic = true }

# Marker
marker_copied = { fg = "#d79921", bg = "#d79921" }
marker_cut = { fg = "#3c3836", bg = "#3c3836" }
marker_marked = { fg = "#458588", bg = "#458588" }
marker_selected = { fg = "#b9ad9c", bg = "#b9ad9c" }

# Count
count_copied = { fg = "#282828", bg = "#3c3836" }
count_cut = { fg = "#282828", bg = "#3c3836" }
count_selected = { fg = "#3c3836", bg = "#b9ad9c" }

# Border
border_symbol = " "
border_style  = { fg = "#458588" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#928374", fg = "#458588" }

[mode]
# Mode
normal_main = { bg = "#458588", fg = "#3c3836", bold = true }
normal_alt  = { bg = "#a89984", fg = "#ebdbb2" }

# Select mode
select_main = { bg = "#3c3836", fg = "#3c3836", bold = true }
select_alt  = { bg = "#a89984", fg = "#ebdbb2" }

# Unset mode
unset_main = { bg = "#b9ad9c", fg = "#3c3836", bold = true }
unset_alt  = { bg = "#a89984", fg = "#ebdbb2" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#458588", bg = "#a89984" }
progress_error = { fg = "#d79921", bg = "#a89984" }

# Permissions
permissions_t = { fg = "#458588" }
permissions_w = { fg = "#b9ad9c" }
permissions_x = { fg = "#d79921" }
permissions_r = { fg = "#ebdbb2" }
permissions_s = { fg = "#3c3836" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#458588" }
active = { fg = "#b9ad9c", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#458588" }
value = { fg = "#ebdbb2" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#458588", bold = true, bg = "#282828" }
inactive = { fg = "#3c3836", bg = "#282828" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#458588", bg = "#928374" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#458588" }
title = {}
hovered = { fg = "#3c3836", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#a89984" }
cand = { fg = "#458588" }
rest = { fg = "#3c3836" }
desc = { fg = "#ebdbb2" }
separator = " ▶ "
separator_style = { fg = "#ebdbb2" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ebdbb2" }
run = { fg = "#ebdbb2" }
footer = { fg = "#3c3836", bg = "#3c3836" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#b9ad9c" }
title_warn = { fg = "#458588" }
title_error = { fg = "#d79921" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#b9ad9c" },

    # Media
    { mime = "{audio,video}/*", fg = "#458588" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#3c3836" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#ebdbb2" },

    # Special files
    { name = "*", is = "orphan", bg = "#d79921" },
    { name = "*", is = "exec", fg = "#3c3836" },

    # Fallback
    { name = "*", fg = "#ebdbb2" },
    { name = "*/", fg = "#458588" },
]

# : ]]]
