[skin]
default = "#f0eaed #0d0509 / #f0eaed #2f272b"
tree = "#51494d None / #2f272b None"
parent = "#D9A56C None / #958e91 None"
file = "#f0eaed None / #D9A56C None"
directory = "#D9A56C None Bold / #D9A56C None Bold"
exe = "#D9A56C None Bold"
link = "#D9A56C None Italic"
pruning = "#51494d None Italic"
perm__ = "#2f272b None"
perm_r = "#D9A56C None"
perm_w = "#D9A56C None"
perm_x = "#D9A56C None"
owner = "#958e91 None"
group = "#51494d None"
count = "#D9A56C #0d0509"
dates = "#51494d None"
sparse = "#D9A56C None"
content_extract = "#958e91 None Italic"
content_match = "#f0eaed None Bold"
device_id_major = "#D9A56C None"
device_id_sep = "#51494d None"
device_id_minor = "#D9A56C None"
git_branch = "#f0eaed None Bold"
git_insertions = "#D9A56C None"
git_deletions = "#D9A56C None"
git_status_current = "#2f272b None"
git_status_modified = "#D9A56C None"
git_status_new = "#f0eaed None Bold"
git_status_ignored = "#2f272b None"
git_status_conflicted = "#D9A56C None Bold"
git_status_other = "#D9A56C None"
selected_line = "None #2f272b / None #51494d"
char_match = "#f0eaed None Bold"
file_error = "#E85F6F None Bold"
flag_label = "#958e91 None"
flag_value = "#f0eaed None Bold"
input = "#f0eaed None / #f0eaed #2f272b"
status_error = "#f0eaed #E85F6F"
status_job = "#f0eaed #2f272b"
status_normal = "#f0eaed #0d0509 / #0d0509 #2f272b"
status_italic = "#D9A56C #0d0509 Italic / #0d0509 #2f272b"
status_bold = "#D9A56C #0d0509 Bold / #0d0509 #2f272b"
status_code = "#f0eaed #0d0509 / #0d0509 #2f272b"
status_ellipsis = "#958e91 #0d0509 / #0d0509 #2f272b"
purpose_normal = "#f0eaed #2f272b"
purpose_italic = "#D9A56C #2f272b Italic"
purpose_bold = "#D9A56C #2f272b Bold"
purpose_ellipsis = "#958e91 #2f272b"
scrollbar_track = "#0d0509 None / #0d0509 None"
scrollbar_thumb = "#51494d None / #2f272b None"
help_paragraph = "#f0eaed None"
help_bold = "#D9A56C None Bold"
help_italic = "#D9A56C None Italic"
help_code = "#f0eaed #2f272b"
help_headers = "#D9A56C None Bold"
help_table_border = "#51494d None"
preview_title = "#f0eaed None Bold / #D9A56C None"
preview = "#f0eaed #0d0509 / #D9A56C #2f272b"
preview_separator = "#51494d None / #2f272b None"
preview_line_number = "#51494d #0d0509"
preview_match = "None #51494d"
hex_null = "#2f272b None"
hex_ascii_graphic = "#f0eaed None"
hex_ascii_whitespace = "#D9A56C None"
hex_ascii_other = "#D9A56C None"
hex_non_ascii = "#D9A56C None"
staging_area_title = "#f0eaed None Bold / #D9A56C None"
mode_command_mark = "#0d0509 #D9A56C Bold"
good_to_bad_0 = "#F29B9A"
good_to_bad_1 = "#F29B9A"
good_to_bad_2 = "#F29B9A"
good_to_bad_3 = "#958e91"
good_to_bad_4 = "#958e91"
good_to_bad_5 = "#51494d"
good_to_bad_6 = "#D4A882"
good_to_bad_7 = "#D4A882"
good_to_bad_8 = "#E85F6F"
good_to_bad_9 = "#E85F6F"
