$background = rgb(0d0509)
$foreground = rgb(f0eaed)
$accent     = rgb(D9A56C)
$bg_subtle  = rgb(2f272b)
$bg_muted   = rgb(51494d)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
