[palettes.sakura]
bg               = '#0d0509'
bg_subtle        = '#2f272b'
bg_muted         = '#51494d'
fg               = '#f0eaed'
fg_dim           = '#958e91'
sel_bg           = '#f0eaed'
sel_fg           = '#0d0509'
error            = '#E85F6F'
accent           = '#D9A56C'
fg_on_accent     = '#f0eaed'
success          = '#F29B9A'
warning          = '#D4A882'
cursor           = '#f0eaed'
