[palettes.zorro]
base             = '#0d0509'
crust            = '#51494d'
on_sig1          = '#0d0509'
on_sig2          = '#f0eaed'
on_sigbg         = '#f0eaed'
red              = '#E85F6F'
sig1             = '#D9A56C'
sig2             = '#D1B399'
sig_bg           = '#0d0509'
sig_surface_high = '#2f272b'
text             = '#f0eaed'
