[mgr]
cwd = { fg = "#f0eaed" }
find_keyword = { fg = "#E85F6F", bold = true, italic = true, underline = true }
find_position = { fg = "#E85F6F", bold = true, italic = true }
marker_copied = { fg = "#D1B399", bg = "#D1B399" }
marker_cut = { fg = "#958e91", bg = "#958e91" }
marker_marked = { fg = "#D9A56C", bg = "#D9A56C" }
marker_selected = { fg = "#F29B9A", bg = "#F29B9A" }
count_copied = { fg = "#0d0509", bg = "#958e91" }
count_cut = { fg = "#0d0509", bg = "#958e91" }
count_selected = { fg = "#0d0509", bg = "#F29B9A" }
border_symbol = " "
border_style = { fg = "#D9A56C" }

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }
perm_type = { fg = "#D9A56C" }
perm_read = { fg = "#f0eaed" }
perm_write = { fg = "#F29B9A" }
perm_exec = { fg = "#D1B399" }
perm_sep = { fg = "#958e91" }
progress_label = { bold = true }
progress_normal = { fg = "#D9A56C", bg = "#2f272b" }
progress_error = { fg = "#D1B399", bg = "#2f272b" }

[mode]
normal_main = { bg = "#D9A56C", fg = "#0d0509", bold = true }
normal_alt  = { bg = "#2f272b", fg = "#f0eaed" }
select_main = { bg = "#958e91", fg = "#0d0509", bold = true }
select_alt  = { bg = "#2f272b", fg = "#f0eaed" }
unset_main = { bg = "#F29B9A", fg = "#0d0509", bold = true }
unset_alt  = { bg = "#2f272b", fg = "#f0eaed" }

[select]
border = { fg = "#D9A56C" }
active = { fg = "#F29B9A", bold = true }

[input]
border = { fg = "#D9A56C" }
value = { fg = "#f0eaed" }

[tabs]
active = { fg = "#D9A56C", bold = true, bg = "#0d0509" }
inactive = { fg = "#958e91", bg = "#0d0509" }
sep_inner = { open = "[", close = "]" }

[cmp]
border = { fg = "#D9A56C", bg = "#2f272b" }

[tasks]
border = { fg = "#D9A56C" }
title = {}
hovered = { fg = "#958e91", underline = true }

[which]
cols = 3
mask = { bg = "#2f272b" }
cand = { fg = "#D9A56C" }
rest = { fg = "#0d0509" }
desc = { fg = "#f0eaed" }
separator = " ▶ "
separator_style = { fg = "#f0eaed" }

[help]
on = { fg = "#f0eaed" }
run = { fg = "#f0eaed" }
footer = { fg = "#0d0509", bg = "#958e91" }

[notify]
title_info = { fg = "#F29B9A" }
title_warn = { fg = "#D9A56C" }
title_error = { fg = "#D1B399" }

[filetype]
rules = [
    { mime = "image/*", fg = "#F29B9A" },
    { mime = "{audio,video}/*", fg = "#D9A56C" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#958e91" },
    { mime = "application/{pdf,doc,rtf}", fg = "#f0eaed" },
    { url = "*", is = "orphan", bg = "#D1B399" },
    { url = "*", is = "exec", fg = "#958e91" },
    { url = "*", fg = "#f0eaed" },
    { url = "*/", fg = "#D9A56C" },
]
