# : Manager [[[

[mgr]
cwd = { fg = "#f0eaed" }

# Find
find_keyword = { fg = "#E85F6F", bold = true, italic = true, underline = true }
find_position = { fg = "#E85F6F", bold = true, italic = true }

# Marker
marker_copied = { fg = "#FF7A8A", bg = "#FF7A8A" }
marker_cut = { fg = "#ffffff", bg = "#ffffff" }
marker_marked = { fg = "#D1B399", bg = "#D1B399" }
marker_selected = { fg = "#856c7c", bg = "#856c7c" }

# Count
count_copied = { fg = "#0d0509", bg = "#ffffff" }
count_cut = { fg = "#0d0509", bg = "#ffffff" }
count_selected = { fg = "#0d0509", bg = "#856c7c" }

# Border
border_symbol = " "
border_style = { fg = "#D1B399" }

# : ]]]


# : Status [[[

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }

# Permissions
perm_type = { fg = "#D1B399" }
perm_read = { fg = "#f0eaed" }
perm_write = { fg = "#856c7c" }
perm_exec = { fg = "#FF7A8A" }
perm_sep = { fg = "#ffffff" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#D1B399", bg = "#4a3c45" }
progress_error = { fg = "#FF7A8A", bg = "#4a3c45" }

[mode]
normal_main = { bg = "#D1B399", fg = "#0d0509", bold = true }
normal_alt  = { bg = "#4a3c45", fg = "#f0eaed" }

select_main = { bg = "#ffffff", fg = "#0d0509", bold = true }
select_alt  = { bg = "#4a3c45", fg = "#f0eaed" }

unset_main = { bg = "#856c7c", fg = "#0d0509", bold = true }
unset_alt  = { bg = "#4a3c45", fg = "#f0eaed" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#D1B399" }
active = { fg = "#856c7c", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#D1B399" }
value = { fg = "#f0eaed" }

# : ]]]


# : Tabs [[[

[tabs]
active = { fg = "#D1B399", bold = true, bg = "#0d0509" }
inactive = { fg = "#ffffff", bg = "#0d0509" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#D1B399", bg = "#4a3c45" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#D1B399" }
title = {}
hovered = { fg = "#ffffff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#4a3c45" }
cand = { fg = "#D1B399" }
rest = { fg = "#0d0509" }
desc = { fg = "#f0eaed" }
separator = " ▶ "
separator_style = { fg = "#f0eaed" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f0eaed" }
run = { fg = "#f0eaed" }
footer = { fg = "#0d0509", bg = "#ffffff" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#856c7c" }
title_warn = { fg = "#D1B399" }
title_error = { fg = "#FF7A8A" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    { mime = "image/*", fg = "#856c7c" },
    { mime = "{audio,video}/*", fg = "#D1B399" },

    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#ffffff" },

    { mime = "application/{pdf,doc,rtf}", fg = "#f0eaed" },

    { url = "*", is = "orphan", bg = "#FF7A8A" },
    { url = "*", is = "exec", fg = "#ffffff" },

    { url = "*", fg = "#f0eaed" },
    { url = "*/", fg = "#D1B399" },
]

# : ]]]
