#!/bin/bash

# Handle click: toggle power profile
if [ "$BLOCK_BUTTON" == "1" ]; then
    ~/.config/i3blocks/scripts/power-profiles
fi

# Always show the current status
~/.config/i3blocks/scripts/pp-status

