#!/bin/bash
# Generated by osyx — do not edit directly

# ── Backgrounds ───────────────────────────────────────────────────────────────
export BG=0xff0B0B0C
export BG_SUBTLE=0xff131316
export BG_MUTED=0xff2A2A31

# ── Foregrounds ───────────────────────────────────────────────────────────────
export FG=0xffC3B285
export FG_DIM=0xff6A6249
export FG_FAINT=0xff5A5443

# ── Accent / semantic ─────────────────────────────────────────────────────────
export ACCENT=0xffD4AF37
export SUCCESS=0xffA88C46
export WARNING=0xffE0C158
export ERROR=0xff8C4A32

# ── ANSI slots (for plugins that need named hues) ─────────────────────────────
export RED=0xff8C4A32
export GREEN=0xffA88C46
export YELLOW=0xffD4AF37
export BLUE=0xff8C7738
export MAGENTA=0xff9A8452
export CYAN=0xffC3B285
export BRIGHT_RED=0xffA0603E
export BRIGHT_GREEN=0xffC3B285
export BRIGHT_YELLOW=0xffE0C158

# ── Fixed ─────────────────────────────────────────────────────────────────────
export TRANSPARENT=0x00000000

# ── Bar chrome ────────────────────────────────────────────────────────────────
export BAR_COLOR=$TRANSPARENT
export BAR_BORDER_COLOR=$TRANSPARENT

# ── Pill surfaces (alpha-composited over wallpaper) ───────────────────────────
# 40 = ~25%  60 = ~37%  99 = ~60%  cc = ~80%
export PILL_BG=0x402A2A31
export PILL_BORDER=0x606A6249
export PILL_BG_ACTIVE=0xffD4AF37
export PILL_BORDER_ACTIVE=0xffD4AF37

# ── Popup ─────────────────────────────────────────────────────────────────────
export POPUP_BG=0xee131316
export POPUP_BORDER=0xffD4AF37

# ── Icon / label ──────────────────────────────────────────────────────────────
export ICON_COLOR=$FG
export LABEL_COLOR=$FG
export ICON_DIM=$FG_DIM
export LABEL_DIM=$FG_DIM
export DIVIDER_COLOR=0x506A6249

# ── Battery ───────────────────────────────────────────────────────────────────
export BATTERY_FULL=$SUCCESS
export BATTERY_HIGH=$SUCCESS
export BATTERY_MED=$WARNING
export BATTERY_LOW=$ERROR
export BATTERY_CRITICAL=$ERROR

# ── Workspace pills ───────────────────────────────────────────────────────────
export WS_ACTIVE_BG=$PILL_BG_ACTIVE
export WS_ACTIVE_BORDER=$PILL_BORDER_ACTIVE
export WS_ACTIVE_FG=0xff0B0B0C
export WS_INACTIVE_BG=0x402A2A31
export WS_INACTIVE_BORDER=0x606A6249
export WS_INACTIVE_FG=$FG
