foreground              #d7ccc8
background              #3e2723

cursor                  #bcaaa4
cursor_text_color       #3e2723

selection_foreground    #3e2723
selection_background    #d7ccc8

color0                  #3e2723
color1                  #bcaaa4
color2                  #d7ccc8
color3                  #d7ccc8
color4                  #bcaaa4
color5                  #8d6e63
color6                  #6d4c41
color7                  #d7ccc8

color8                  #3e2723
color9                  #bcaaa4
color10                 #d7ccc8
color11                 #d7ccc8
color12                 #bcaaa4
color13                 #8d6e63
color14                 #6d4c41
color15                 #d7ccc8

url_color               #bcaaa4

active_tab_foreground   #3e2723
active_tab_background   #bcaaa4

inactive_tab_foreground #d7ccc8
inactive_tab_background #6d4c41

active_border_color     #bcaaa4
inactive_border_color   #6d4c41
