$background = rgb(1E1E2E)
$foreground = rgb(CDD6F4)
$accent     = rgb(87B0F9)
$bg_subtle  = rgb(38394b)
$bg_muted   = rgb(525569)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
