[palettes.catppuccin]
base             = '#1E1E2E'
crust            = '#525569'
on_sig1          = '#1E1E2E'
on_sig2          = '#CDD6F4'
on_sigbg         = '#CDD6F4'
red              = '#F38BA8'
sig1             = '#87B0F9'
sig2             = '#F5C2E7'
sig_bg           = '#1E1E2E'
sig_surface_high = '#38394b'
text             = '#CDD6F4'
