$background = rgb(3e2723)
$foreground = rgb(d7ccc8)
$accent     = rgb(bcaaa4)

$bg_subtle  = rgb(543f3b)
$bg_muted   = rgb(6b5854)

$active_border   = $accent
$inactive_border = $bg_muted

$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
