$background = rgb(rgb(62 39 35))
$foreground = rgb(rgb(215 204 200))
$accent     = rgb(rgb(188 170 164))

$bg_subtle  = rgb(rgb(84 63 59))
$bg_muted   = rgb(rgb(107 88 84))

$active_border   = $accent
$inactive_border = $bg_muted

$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
