[palettes.versailles]
bg               = '#3e2723'
bg_subtle        = '#543f3b'
bg_muted         = '#6b5854'
fg               = '#d7ccc8'
fg_dim           = '#998a86'
sel_bg           = '#d7ccc8'
sel_fg           = '#3e2723'
error            = '#bcaaa4'
accent           = '#bcaaa4'
fg_on_accent     = '#d7ccc8'
success          = '#d7ccc8'
warning          = '#d7ccc8'
cursor           = '#bcaaa4'
