[palettes.zorro]
base             = '#3e2723'
crust            = '#6b5854'
on_sig1          = '#3e2723'
on_sig2          = '#d7ccc8'
on_sigbg         = '#d7ccc8'
red              = '#bcaaa4'
sig1             = '#bcaaa4'
sig2             = '#8d6e63'
sig_bg           = '#3e2723'
sig_surface_high = '#543f3b'
text             = '#d7ccc8'
