[skin]
default = "#cdd6f4 #11111b / #cdd6f4 #2d2e3b"
tree = "#494c5c None / #2d2e3b None"
parent = "#89b4fa None / #81879d None"
file = "#cdd6f4 None / #89b4fa None"
directory = "#89b4fa None Bold / #89b4fa None Bold"
exe = "#89b4fa None Bold"
link = "#89b4fa None Italic"
pruning = "#494c5c None Italic"
perm__ = "#2d2e3b None"
perm_r = "#89b4fa None"
perm_w = "#89b4fa None"
perm_x = "#89b4fa None"
owner = "#81879d None"
group = "#494c5c None"
count = "#89b4fa #11111b"
dates = "#494c5c None"
sparse = "#89b4fa None"
content_extract = "#81879d None Italic"
content_match = "#cdd6f4 None Bold"
device_id_major = "#89b4fa None"
device_id_sep = "#494c5c None"
device_id_minor = "#89b4fa None"
git_branch = "#cdd6f4 None Bold"
git_insertions = "#89b4fa None"
git_deletions = "#89b4fa None"
git_status_current = "#2d2e3b None"
git_status_modified = "#89b4fa None"
git_status_new = "#cdd6f4 None Bold"
git_status_ignored = "#2d2e3b None"
git_status_conflicted = "#89b4fa None Bold"
git_status_other = "#89b4fa None"
selected_line = "None #2d2e3b / None #494c5c"
char_match = "#cdd6f4 None Bold"
file_error = "#f38ba8 None Bold"
flag_label = "#81879d None"
flag_value = "#cdd6f4 None Bold"
input = "#cdd6f4 None / #cdd6f4 #2d2e3b"
status_error = "#cdd6f4 #f38ba8"
status_job = "#cdd6f4 #2d2e3b"
status_normal = "#cdd6f4 #11111b / #cdd6f4 #2d2e3b"
status_italic = "#89b4fa #11111b Italic / #cdd6f4 #2d2e3b"
status_bold = "#89b4fa #11111b Bold / #cdd6f4 #2d2e3b"
status_code = "#cdd6f4 #11111b / #cdd6f4 #2d2e3b"
status_ellipsis = "#81879d #11111b / #cdd6f4 #2d2e3b"
purpose_normal = "#cdd6f4 #2d2e3b"
purpose_italic = "#89b4fa #2d2e3b Italic"
purpose_bold = "#89b4fa #2d2e3b Bold"
purpose_ellipsis = "#81879d #2d2e3b"
scrollbar_track = "#11111b None / #11111b None"
scrollbar_thumb = "#494c5c None / #2d2e3b None"
help_paragraph = "#cdd6f4 None"
help_bold = "#89b4fa None Bold"
help_italic = "#89b4fa None Italic"
help_code = "#cdd6f4 #2d2e3b"
help_headers = "#89b4fa None Bold"
help_table_border = "#494c5c None"
preview_title = "#cdd6f4 None Bold / #89b4fa None"
preview = "#cdd6f4 #11111b / #89b4fa #2d2e3b"
preview_separator = "#494c5c None / #2d2e3b None"
preview_line_number = "#494c5c #11111b"
preview_match = "None #494c5c"
hex_null = "#2d2e3b None"
hex_ascii_graphic = "#cdd6f4 None"
hex_ascii_whitespace = "#89b4fa None"
hex_ascii_other = "#89b4fa None"
hex_non_ascii = "#89b4fa None"
staging_area_title = "#cdd6f4 None Bold / #89b4fa None"
mode_command_mark = "#cdd6f4 #89b4fa Bold"
good_to_bad_0 = "#a6e3a1"
good_to_bad_1 = "#a6e3a1"
good_to_bad_2 = "#a6e3a1"
good_to_bad_3 = "#81879d"
good_to_bad_4 = "#81879d"
good_to_bad_5 = "#494c5c"
good_to_bad_6 = "#f9e2af"
good_to_bad_7 = "#f9e2af"
good_to_bad_8 = "#f38ba8"
good_to_bad_9 = "#f38ba8"
