$background = rgb(11111b)
$foreground = rgb(cdd6f4)
$accent     = rgb(89b4fa)
$bg_subtle  = rgb(2d2e3b)
$bg_muted   = rgb(494c5c)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
