[palettes.lavender]
base             = '#11111b'
crust            = '#494c5c'
on_sig1          = '#11111b'
on_sig2          = '#cdd6f4'
on_sigbg         = '#cdd6f4'
red              = '#f38ba8'
sig1             = '#89b4fa'
sig2             = '#cba6f7'
sig_bg           = '#11111b'
sig_surface_high = '#2d2e3b'
text             = '#cdd6f4'
