[palettes.lavender]
bg               = '#11111b'
bg_subtle        = '#2d2e3b'
bg_muted         = '#494c5c'
fg               = '#cdd6f4'
fg_dim           = '#81879d'
sel_bg           = '#cba6f7'
sel_fg           = '#cdd6f4'
error            = '#f38ba8'
accent           = '#89b4fa'
fg_on_accent     = '#cdd6f4'
success          = '#a6e3a1'
warning          = '#f9e2af'
cursor           = '#cba6f7'
