[skin]
default = "#100F0F #FFFCF0 / #100F0F #dbd8ce"
tree = "#b7b4ac None / #dbd8ce None"
parent = "#4385BE None / #6f6d69 None"
file = "#100F0F None / #4385BE None"
directory = "#4385BE None Bold / #4385BE None Bold"
exe = "#4385BE None Bold"
link = "#4385BE None Italic"
pruning = "#b7b4ac None Italic"
perm__ = "#dbd8ce None"
perm_r = "#4385BE None"
perm_w = "#4385BE None"
perm_x = "#4385BE None"
owner = "#6f6d69 None"
group = "#b7b4ac None"
count = "#4385BE #FFFCF0"
dates = "#b7b4ac None"
sparse = "#4385BE None"
content_extract = "#6f6d69 None Italic"
content_match = "#100F0F None Bold"
device_id_major = "#4385BE None"
device_id_sep = "#b7b4ac None"
device_id_minor = "#4385BE None"
git_branch = "#100F0F None Bold"
git_insertions = "#4385BE None"
git_deletions = "#4385BE None"
git_status_current = "#dbd8ce None"
git_status_modified = "#4385BE None"
git_status_new = "#100F0F None Bold"
git_status_ignored = "#dbd8ce None"
git_status_conflicted = "#4385BE None Bold"
git_status_other = "#4385BE None"
selected_line = "None #dbd8ce / None #b7b4ac"
char_match = "#100F0F None Bold"
file_error = "#D14D41 None Bold"
flag_label = "#6f6d69 None"
flag_value = "#100F0F None Bold"
input = "#100F0F None / #100F0F #dbd8ce"
status_error = "#100F0F #D14D41"
status_job = "#100F0F #dbd8ce"
status_normal = "#100F0F #FFFCF0 / #100F0F #dbd8ce"
status_italic = "#4385BE #FFFCF0 Italic / #100F0F #dbd8ce"
status_bold = "#4385BE #FFFCF0 Bold / #100F0F #dbd8ce"
status_code = "#100F0F #FFFCF0 / #100F0F #dbd8ce"
status_ellipsis = "#6f6d69 #FFFCF0 / #100F0F #dbd8ce"
purpose_normal = "#100F0F #dbd8ce"
purpose_italic = "#4385BE #dbd8ce Italic"
purpose_bold = "#4385BE #dbd8ce Bold"
purpose_ellipsis = "#6f6d69 #dbd8ce"
scrollbar_track = "#FFFCF0 None / #FFFCF0 None"
scrollbar_thumb = "#b7b4ac None / #dbd8ce None"
help_paragraph = "#100F0F None"
help_bold = "#4385BE None Bold"
help_italic = "#4385BE None Italic"
help_code = "#100F0F #dbd8ce"
help_headers = "#4385BE None Bold"
help_table_border = "#b7b4ac None"
preview_title = "#100F0F None Bold / #4385BE None"
preview = "#100F0F #FFFCF0 / #4385BE #dbd8ce"
preview_separator = "#b7b4ac None / #dbd8ce None"
preview_line_number = "#b7b4ac #FFFCF0"
preview_match = "None #b7b4ac"
hex_null = "#dbd8ce None"
hex_ascii_graphic = "#100F0F None"
hex_ascii_whitespace = "#4385BE None"
hex_ascii_other = "#4385BE None"
hex_non_ascii = "#4385BE None"
staging_area_title = "#100F0F None Bold / #4385BE None"
mode_command_mark = "#100F0F #4385BE Bold"
good_to_bad_0 = "#879A39"
good_to_bad_1 = "#879A39"
good_to_bad_2 = "#879A39"
good_to_bad_3 = "#6f6d69"
good_to_bad_4 = "#6f6d69"
good_to_bad_5 = "#b7b4ac"
good_to_bad_6 = "#D0A215"
good_to_bad_7 = "#D0A215"
good_to_bad_8 = "#D14D41"
good_to_bad_9 = "#D14D41"
