$background = rgb(FFFCF0)
$foreground = rgb(100F0F)
$accent     = rgb(4385BE)
$bg_subtle  = rgb(dbd8ce)
$bg_muted   = rgb(b7b4ac)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
