[mgr]
cwd = { fg = "#100F0F" }
find_keyword = { fg = "#D14D41", bold = true, italic = true, underline = true }
find_position = { fg = "#D14D41", bold = true, italic = true }
marker_copied = { fg = "#CE5D97", bg = "#CE5D97" }
marker_cut = { fg = "#6f6d69", bg = "#6f6d69" }
marker_marked = { fg = "#4385BE", bg = "#4385BE" }
marker_selected = { fg = "#879A39", bg = "#879A39" }
count_copied = { fg = "#FFFCF0", bg = "#6f6d69" }
count_cut = { fg = "#FFFCF0", bg = "#6f6d69" }
count_selected = { fg = "#FFFCF0", bg = "#879A39" }
border_symbol = " "
border_style = { fg = "#4385BE" }

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }
perm_type = { fg = "#4385BE" }
perm_read = { fg = "#100F0F" }
perm_write = { fg = "#879A39" }
perm_exec = { fg = "#CE5D97" }
perm_sep = { fg = "#6f6d69" }
progress_label = { bold = true }
progress_normal = { fg = "#4385BE", bg = "#dbd8ce" }
progress_error = { fg = "#CE5D97", bg = "#dbd8ce" }

[mode]
normal_main = { bg = "#4385BE", fg = "#FFFCF0", bold = true }
normal_alt  = { bg = "#dbd8ce", fg = "#100F0F" }
select_main = { bg = "#6f6d69", fg = "#FFFCF0", bold = true }
select_alt  = { bg = "#dbd8ce", fg = "#100F0F" }
unset_main = { bg = "#879A39", fg = "#FFFCF0", bold = true }
unset_alt  = { bg = "#dbd8ce", fg = "#100F0F" }

[select]
border = { fg = "#4385BE" }
active = { fg = "#879A39", bold = true }

[input]
border = { fg = "#4385BE" }
value = { fg = "#100F0F" }

[tabs]
active = { fg = "#4385BE", bold = true, bg = "#FFFCF0" }
inactive = { fg = "#6f6d69", bg = "#FFFCF0" }
sep_inner = { open = "[", close = "]" }

[cmp]
border = { fg = "#4385BE", bg = "#dbd8ce" }

[tasks]
border = { fg = "#4385BE" }
title = {}
hovered = { fg = "#6f6d69", underline = true }

[which]
cols = 3
mask = { bg = "#dbd8ce" }
cand = { fg = "#4385BE" }
rest = { fg = "#FFFCF0" }
desc = { fg = "#100F0F" }
separator = " ▶ "
separator_style = { fg = "#100F0F" }

[help]
on = { fg = "#100F0F" }
run = { fg = "#100F0F" }
footer = { fg = "#FFFCF0", bg = "#6f6d69" }

[notify]
title_info = { fg = "#879A39" }
title_warn = { fg = "#4385BE" }
title_error = { fg = "#CE5D97" }

[filetype]
rules = [
    { mime = "image/*", fg = "#879A39" },
    { mime = "{audio,video}/*", fg = "#4385BE" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#6f6d69" },
    { mime = "application/{pdf,doc,rtf}", fg = "#100F0F" },
    { url = "*", is = "orphan", bg = "#CE5D97" },
    { url = "*", is = "exec", fg = "#6f6d69" },
    { url = "*", fg = "#100F0F" },
    { url = "*/", fg = "#4385BE" },
]
