# : Manager [[[

[mgr]
cwd = { fg = "#100F0F" }

# Find
find_keyword = { fg = "#D14D41", bold = true, italic = true, underline = true }
find_position = { fg = "#D14D41", bold = true, italic = true }

# Marker
marker_copied = { fg = "#AD8301", bg = "#AD8301" }
marker_cut = { fg = "#100F0F", bg = "#100F0F" }
marker_marked = { fg = "#205EA6", bg = "#205EA6" }
marker_selected = { fg = "#f4f3ea", bg = "#f4f3ea" }

# Count
count_copied = { fg = "#FFFCF0", bg = "#100F0F" }
count_cut = { fg = "#FFFCF0", bg = "#100F0F" }
count_selected = { fg = "#F2F0E5", bg = "#f4f3ea" }

# Border
border_symbol = " "
border_style = { fg = "#205EA6" }

# : ]]]


# : Status [[[

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }

# Permissions
perm_type = { fg = "#205EA6" }
perm_read = { fg = "#100F0F" }
perm_write = { fg = "#f4f3ea" }
perm_exec = { fg = "#AD8301" }
perm_sep = { fg = "#100F0F" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#205EA6", bg = "#F2F0E5" }
progress_error = { fg = "#AD8301", bg = "#F2F0E5" }

[mode]
normal_main = { bg = "#205EA6", fg = "#F2F0E5", bold = true }
normal_alt  = { bg = "#F2F0E5", fg = "#100F0F" }

select_main = { bg = "#100F0F", fg = "#100F0F", bold = true }
select_alt  = { bg = "#F2F0E5", fg = "#100F0F" }

unset_main = { bg = "#f4f3ea", fg = "#100F0F", bold = true }
unset_alt  = { bg = "#F2F0E5", fg = "#100F0F" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#205EA6" }
active = { fg = "#f4f3ea", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#205EA6" }
value = { fg = "#100F0F" }

# : ]]]


# : Tabs [[[

[tabs]
active = { fg = "#205EA6", bold = true, bg = "#FFFCF0" }
inactive = { fg = "#100F0F", bg = "#FFFCF0" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#205EA6", bg = "#6F6E69" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#205EA6" }
title = {}
hovered = { fg = "#100F0F", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#F2F0E5" }
cand = { fg = "#205EA6" }
rest = { fg = "#F2F0E5" }
desc = { fg = "#100F0F" }
separator = " ▶ "
separator_style = { fg = "#100F0F" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#100F0F" }
run = { fg = "#100F0F" }
footer = { fg = "#100F0F", bg = "#100F0F" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#f4f3ea" }
title_warn = { fg = "#205EA6" }
title_error = { fg = "#AD8301" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    { mime = "image/*", fg = "#f4f3ea" },
    { mime = "{audio,video}/*", fg = "#205EA6" },

    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#100F0F" },

    { mime = "application/{pdf,doc,rtf}", fg = "#100F0F" },

    { url = "*", is = "orphan", bg = "#AD8301" },
    { url = "*", is = "exec", fg = "#100F0F" },

    { url = "*", fg = "#100F0F" },
    { url = "*/", fg = "#205EA6" },
]

# : ]]]
