[skin]
default = "#4C4F69 #EFF1F5 / #4C4F69 #d6d8e0"
tree = "#bec0cb None / #d6d8e0 None"
parent = "#1E66F5 None / #8d8fa1 None"
file = "#4C4F69 None / #1E66F5 None"
directory = "#1E66F5 None Bold / #1E66F5 None Bold"
exe = "#1E66F5 None Bold"
link = "#1E66F5 None Italic"
pruning = "#bec0cb None Italic"
perm__ = "#d6d8e0 None"
perm_r = "#1E66F5 None"
perm_w = "#1E66F5 None"
perm_x = "#1E66F5 None"
owner = "#8d8fa1 None"
group = "#bec0cb None"
count = "#1E66F5 #EFF1F5"
dates = "#bec0cb None"
sparse = "#1E66F5 None"
content_extract = "#8d8fa1 None Italic"
content_match = "#4C4F69 None Bold"
device_id_major = "#1E66F5 None"
device_id_sep = "#bec0cb None"
device_id_minor = "#1E66F5 None"
git_branch = "#4C4F69 None Bold"
git_insertions = "#1E66F5 None"
git_deletions = "#1E66F5 None"
git_status_current = "#d6d8e0 None"
git_status_modified = "#1E66F5 None"
git_status_new = "#4C4F69 None Bold"
git_status_ignored = "#d6d8e0 None"
git_status_conflicted = "#1E66F5 None Bold"
git_status_other = "#1E66F5 None"
selected_line = "None #d6d8e0 / None #bec0cb"
char_match = "#4C4F69 None Bold"
file_error = "#D20F39 None Bold"
flag_label = "#8d8fa1 None"
flag_value = "#4C4F69 None Bold"
input = "#4C4F69 None / #4C4F69 #d6d8e0"
status_error = "#4C4F69 #D20F39"
status_job = "#4C4F69 #d6d8e0"
status_normal = "#4C4F69 #EFF1F5 / #EFF1F5 #d6d8e0"
status_italic = "#1E66F5 #EFF1F5 Italic / #EFF1F5 #d6d8e0"
status_bold = "#1E66F5 #EFF1F5 Bold / #EFF1F5 #d6d8e0"
status_code = "#4C4F69 #EFF1F5 / #EFF1F5 #d6d8e0"
status_ellipsis = "#8d8fa1 #EFF1F5 / #EFF1F5 #d6d8e0"
purpose_normal = "#4C4F69 #d6d8e0"
purpose_italic = "#1E66F5 #d6d8e0 Italic"
purpose_bold = "#1E66F5 #d6d8e0 Bold"
purpose_ellipsis = "#8d8fa1 #d6d8e0"
scrollbar_track = "#EFF1F5 None / #EFF1F5 None"
scrollbar_thumb = "#bec0cb None / #d6d8e0 None"
help_paragraph = "#4C4F69 None"
help_bold = "#1E66F5 None Bold"
help_italic = "#1E66F5 None Italic"
help_code = "#4C4F69 #d6d8e0"
help_headers = "#1E66F5 None Bold"
help_table_border = "#bec0cb None"
preview_title = "#4C4F69 None Bold / #1E66F5 None"
preview = "#4C4F69 #EFF1F5 / #1E66F5 #d6d8e0"
preview_separator = "#bec0cb None / #d6d8e0 None"
preview_line_number = "#bec0cb #EFF1F5"
preview_match = "None #bec0cb"
hex_null = "#d6d8e0 None"
hex_ascii_graphic = "#4C4F69 None"
hex_ascii_whitespace = "#1E66F5 None"
hex_ascii_other = "#1E66F5 None"
hex_non_ascii = "#1E66F5 None"
staging_area_title = "#4C4F69 None Bold / #1E66F5 None"
mode_command_mark = "#EFF1F5 #1E66F5 Bold"
good_to_bad_0 = "#40A02B"
good_to_bad_1 = "#40A02B"
good_to_bad_2 = "#40A02B"
good_to_bad_3 = "#8d8fa1"
good_to_bad_4 = "#8d8fa1"
good_to_bad_5 = "#bec0cb"
good_to_bad_6 = "#DF8E1D"
good_to_bad_7 = "#DF8E1D"
good_to_bad_8 = "#D20F39"
good_to_bad_9 = "#D20F39"
