[palettes.catppuccin-latte]
bg               = '#EFF1F5'
bg_subtle        = '#d6d8e0'
bg_muted         = '#bec0cb'
fg               = '#4C4F69'
fg_dim           = '#8d8fa1'
sel_bg           = '#DC8A78'
sel_fg           = '#EFF1F5'
error            = '#D20F39'
accent           = '#1E66F5'
fg_on_accent     = '#4C4F69'
success          = '#40A02B'
warning          = '#DF8E1D'
cursor           = '#DC8A78'
