[palettes.lumon]
bg               = '#16242d'
bg_subtle        = '#324049'
bg_muted         = '#4f5d66'
fg               = '#d6e2ee'
fg_dim           = '#8996a0'
sel_bg           = '#4d9ed3'
sel_fg           = '#1b2d40'
error            = '#4d86b0'
accent           = '#6fb8e3'
fg_on_accent     = '#d6e2ee'
success          = '#5e95bc'
warning          = '#6fa4c9'
cursor           = '#f2fcff'
