# : Manager [[[

[mgr]
cwd = { fg = "#d6e2ee" }

# Tab
tab_active = { fg = "#1b2d40", bg = "#f2fcff", bold = true }
tab_inactive = { fg = "#d6e2ee", bg = "#304860" }
tab_width = 1

# Find
find_keyword = { fg = "#4d86b0", bold = true, italic = true, underline = true }
find_position = { fg = "#4d86b0", bold = true, italic = true }

# Marker
marker_copied = { fg = "#5e95bc", bg = "#5e95bc" }
marker_cut = { fg = "#1b2d40", bg = "#1b2d40" }
marker_marked = { fg = "#f2fcff", bg = "#f2fcff" }
marker_selected = { fg = "#8bc6e8", bg = "#8bc6e8" }

# Count
count_copied = { fg = "#16242d", bg = "#1b2d40" }
count_cut = { fg = "#16242d", bg = "#1b2d40" }
count_selected = { fg = "#1b2d40", bg = "#8bc6e8" }

# Border
border_symbol = " "
border_style  = { fg = "#f2fcff" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#304860", fg = "#f2fcff" }

[mode]
# Mode
normal_main = { bg = "#f2fcff", fg = "#1b2d40", bold = true }
normal_alt  = { bg = "#6fb8e3", fg = "#d6e2ee" }

# Select mode
select_main = { bg = "#1b2d40", fg = "#1b2d40", bold = true }
select_alt  = { bg = "#6fb8e3", fg = "#d6e2ee" }

# Unset mode
unset_main = { bg = "#8bc6e8", fg = "#1b2d40", bold = true }
unset_alt  = { bg = "#6fb8e3", fg = "#d6e2ee" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#f2fcff", bg = "#6fb8e3" }
progress_error = { fg = "#5e95bc", bg = "#6fb8e3" }

# Permissions
permissions_t = { fg = "#f2fcff" }
permissions_w = { fg = "#8bc6e8" }
permissions_x = { fg = "#5e95bc" }
permissions_r = { fg = "#d6e2ee" }
permissions_s = { fg = "#1b2d40" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#f2fcff" }
active = { fg = "#8bc6e8", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#f2fcff" }
value = { fg = "#d6e2ee" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#f2fcff", bold = true, bg = "#16242d" }
inactive = { fg = "#1b2d40", bg = "#16242d" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#f2fcff", bg = "#304860" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#f2fcff" }
title = {}
hovered = { fg = "#1b2d40", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#6fb8e3" }
cand = { fg = "#f2fcff" }
rest = { fg = "#1b2d40" }
desc = { fg = "#d6e2ee" }
separator = " ▶ "
separator_style = { fg = "#d6e2ee" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#d6e2ee" }
run = { fg = "#d6e2ee" }
footer = { fg = "#1b2d40", bg = "#1b2d40" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#8bc6e8" }
title_warn = { fg = "#f2fcff" }
title_error = { fg = "#5e95bc" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#8bc6e8" },

    # Media
    { mime = "{audio,video}/*", fg = "#f2fcff" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#1b2d40" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#d6e2ee" },

    # Special files
    { name = "*", is = "orphan", bg = "#5e95bc" },
    { name = "*", is = "exec", fg = "#1b2d40" },

    # Fallback
    { name = "*", fg = "#d6e2ee" },
    { name = "*/", fg = "#f2fcff" },
]

# : ]]]
