$background = rgb(2c2525)
$foreground = rgb(e6d9db)
$accent     = rgb(f38d70)
$bg_subtle  = rgb(474040)
$bg_muted   = rgb(635b5b)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
