[palettes.ristretto]
bg               = '#2c2525'
bg_subtle        = '#474040'
bg_muted         = '#635b5b'
fg               = '#e6d9db'
fg_dim           = '#9b9192'
sel_bg           = '#403e41'
sel_fg           = '#e6d9db'
error            = '#fd6883'
accent           = '#f38d70'
fg_on_accent     = '#e6d9db'
success          = '#adda78'
warning          = '#f9cc6c'
cursor           = '#c3b7b8'
