[palettes.ristretto]
base             = '#2c2525'
crust            = '#635b5b'
on_sig1          = '#2c2525'
on_sig2          = '#e6d9db'
on_sigbg         = '#e6d9db'
red              = '#fd6883'
sig1             = '#f38d70'
sig2             = '#a8a9eb'
sig_bg           = '#2c2525'
sig_surface_high = '#474040'
text             = '#e6d9db'
