gui:
  theme:
    activeBorderColor:
      - '6fb8e3'
      - bold
    inactiveBorderColor:
      - '4f5d66'
    optionsTextColor:
      - 'b4e4f6'
    selectedLineBgColor:
      - '324049'
    cherryPickedCommitBgColor:
      - '16242d'
    cherryPickedCommitFgColor:
      - '6fb8e3'
    unstagedChangesColor:
      - '4d86b0'
    defaultFgColor:
      - 'd6e2ee'
    searchingActiveBorderColor:
      - '6fa4c9'

  authorColors:
    '*': '5e95bc'

  nerdFontsVersion: "3"
  showFileTree: true
  showIcons: true
  skipRewordInEditorWarning: true
  expandFocusedSidePanel: true
  mouseEvents: true
  editor: "nvim"

  git:
    paging:
      colorArg: always
      pager: delta --dark --paging=never
    merging:
      manualCommit: false
    commit:
      signOff: false
    log:
      showGraph: true

notARepository: "quit"
