gui:
  theme:
    activeBorderColor:
      - 'f38d70'
      - bold
    inactiveBorderColor:
      - '635b5b'
    optionsTextColor:
      - '85dacc'
    selectedLineBgColor:
      - '474040'
    cherryPickedCommitBgColor:
      - '2c2525'
    cherryPickedCommitFgColor:
      - 'f38d70'
    unstagedChangesColor:
      - 'fd6883'
    defaultFgColor:
      - 'e6d9db'
    searchingActiveBorderColor:
      - 'f9cc6c'

  authorColors:
    '*': 'adda78'

  nerdFontsVersion: "3"
  showFileTree: true
  showIcons: true
  skipRewordInEditorWarning: true
  expandFocusedSidePanel: true
  mouseEvents: true
  editor: "nvim"

  git:
    paging:
      colorArg: always
      pager: delta --dark --paging=never
    merging:
      manualCommit: false
    commit:
      signOff: false
    log:
      showGraph: true

notARepository: "quit"
