gui:
  theme:
    activeBorderColor:
      - 'bd93f9'
      - bold
    inactiveBorderColor:
      - '66676e'
    optionsTextColor:
      - '8be9fd'
    selectedLineBgColor:
      - '474852'
    cherryPickedCommitBgColor:
      - '282a36'
    cherryPickedCommitFgColor:
      - 'bd93f9'
    unstagedChangesColor:
      - 'ff5555'
    defaultFgColor:
      - 'f8f8f2'
    searchingActiveBorderColor:
      - 'f1fa8c'

  authorColors:
    '*': '50fa7b'

  nerdFontsVersion: "3"
  showFileTree: true
  showIcons: true
  skipRewordInEditorWarning: true
  expandFocusedSidePanel: true
  mouseEvents: true
  editor: "nvim"

  git:
    paging:
      colorArg: always
      pager: delta --dark --paging=never
    merging:
      manualCommit: false
    commit:
      signOff: false
    log:
      showGraph: true

notARepository: "quit"
