[skin]
default = "#d6e2ee #16242d / #d6e2ee #324049"
tree = "#4f5d66 None / #324049 None"
parent = "#6fb8e3 None / #8996a0 None"
file = "#d6e2ee None / #6fb8e3 None"
directory = "#6fb8e3 None Bold / #6fb8e3 None Bold"
exe = "#6fb8e3 None Bold"
link = "#6fb8e3 None Italic"
pruning = "#4f5d66 None Italic"
perm__ = "#324049 None"
perm_r = "#6fb8e3 None"
perm_w = "#6fb8e3 None"
perm_x = "#6fb8e3 None"
owner = "#8996a0 None"
group = "#4f5d66 None"
count = "#6fb8e3 #16242d"
dates = "#4f5d66 None"
sparse = "#6fb8e3 None"
content_extract = "#8996a0 None Italic"
content_match = "#d6e2ee None Bold"
device_id_major = "#6fb8e3 None"
device_id_sep = "#4f5d66 None"
device_id_minor = "#6fb8e3 None"
git_branch = "#d6e2ee None Bold"
git_insertions = "#6fb8e3 None"
git_deletions = "#6fb8e3 None"
git_status_current = "#324049 None"
git_status_modified = "#6fb8e3 None"
git_status_new = "#d6e2ee None Bold"
git_status_ignored = "#324049 None"
git_status_conflicted = "#6fb8e3 None Bold"
git_status_other = "#6fb8e3 None"
selected_line = "None #324049 / None #4f5d66"
char_match = "#d6e2ee None Bold"
file_error = "#4d86b0 None Bold"
flag_label = "#8996a0 None"
flag_value = "#d6e2ee None Bold"
input = "#d6e2ee None / #d6e2ee #324049"
status_error = "#d6e2ee #4d86b0"
status_job = "#d6e2ee #324049"
status_normal = "#d6e2ee #16242d / #1b2d40 #324049"
status_italic = "#6fb8e3 #16242d Italic / #1b2d40 #324049"
status_bold = "#6fb8e3 #16242d Bold / #1b2d40 #324049"
status_code = "#d6e2ee #16242d / #1b2d40 #324049"
status_ellipsis = "#8996a0 #16242d / #1b2d40 #324049"
purpose_normal = "#d6e2ee #324049"
purpose_italic = "#6fb8e3 #324049 Italic"
purpose_bold = "#6fb8e3 #324049 Bold"
purpose_ellipsis = "#8996a0 #324049"
scrollbar_track = "#16242d None / #16242d None"
scrollbar_thumb = "#4f5d66 None / #324049 None"
help_paragraph = "#d6e2ee None"
help_bold = "#6fb8e3 None Bold"
help_italic = "#6fb8e3 None Italic"
help_code = "#d6e2ee #324049"
help_headers = "#6fb8e3 None Bold"
help_table_border = "#4f5d66 None"
preview_title = "#d6e2ee None Bold / #6fb8e3 None"
preview = "#d6e2ee #16242d / #6fb8e3 #324049"
preview_separator = "#4f5d66 None / #324049 None"
preview_line_number = "#4f5d66 #16242d"
preview_match = "None #4f5d66"
hex_null = "#324049 None"
hex_ascii_graphic = "#d6e2ee None"
hex_ascii_whitespace = "#6fb8e3 None"
hex_ascii_other = "#6fb8e3 None"
hex_non_ascii = "#6fb8e3 None"
staging_area_title = "#d6e2ee None Bold / #6fb8e3 None"
mode_command_mark = "#1b2d40 #6fb8e3 Bold"
good_to_bad_0 = "#5e95bc"
good_to_bad_1 = "#5e95bc"
good_to_bad_2 = "#5e95bc"
good_to_bad_3 = "#8996a0"
good_to_bad_4 = "#8996a0"
good_to_bad_5 = "#4f5d66"
good_to_bad_6 = "#6fa4c9"
good_to_bad_7 = "#6fa4c9"
good_to_bad_8 = "#4d86b0"
good_to_bad_9 = "#4d86b0"
