[skin]
default = "#e6d9db #2c2525 / #e6d9db #474040"
tree = "#635b5b None / #474040 None"
parent = "#f38d70 None / #9b9192 None"
file = "#e6d9db None / #f38d70 None"
directory = "#f38d70 None Bold / #f38d70 None Bold"
exe = "#f38d70 None Bold"
link = "#f38d70 None Italic"
pruning = "#635b5b None Italic"
perm__ = "#474040 None"
perm_r = "#f38d70 None"
perm_w = "#f38d70 None"
perm_x = "#f38d70 None"
owner = "#9b9192 None"
group = "#635b5b None"
count = "#f38d70 #2c2525"
dates = "#635b5b None"
sparse = "#f38d70 None"
content_extract = "#9b9192 None Italic"
content_match = "#e6d9db None Bold"
device_id_major = "#f38d70 None"
device_id_sep = "#635b5b None"
device_id_minor = "#f38d70 None"
git_branch = "#e6d9db None Bold"
git_insertions = "#f38d70 None"
git_deletions = "#f38d70 None"
git_status_current = "#474040 None"
git_status_modified = "#f38d70 None"
git_status_new = "#e6d9db None Bold"
git_status_ignored = "#474040 None"
git_status_conflicted = "#f38d70 None Bold"
git_status_other = "#f38d70 None"
selected_line = "None #474040 / None #635b5b"
char_match = "#e6d9db None Bold"
file_error = "#fd6883 None Bold"
flag_label = "#9b9192 None"
flag_value = "#e6d9db None Bold"
input = "#e6d9db None / #e6d9db #474040"
status_error = "#e6d9db #fd6883"
status_job = "#e6d9db #474040"
status_normal = "#e6d9db #2c2525 / #e6d9db #474040"
status_italic = "#f38d70 #2c2525 Italic / #e6d9db #474040"
status_bold = "#f38d70 #2c2525 Bold / #e6d9db #474040"
status_code = "#e6d9db #2c2525 / #e6d9db #474040"
status_ellipsis = "#9b9192 #2c2525 / #e6d9db #474040"
purpose_normal = "#e6d9db #474040"
purpose_italic = "#f38d70 #474040 Italic"
purpose_bold = "#f38d70 #474040 Bold"
purpose_ellipsis = "#9b9192 #474040"
scrollbar_track = "#2c2525 None / #2c2525 None"
scrollbar_thumb = "#635b5b None / #474040 None"
help_paragraph = "#e6d9db None"
help_bold = "#f38d70 None Bold"
help_italic = "#f38d70 None Italic"
help_code = "#e6d9db #474040"
help_headers = "#f38d70 None Bold"
help_table_border = "#635b5b None"
preview_title = "#e6d9db None Bold / #f38d70 None"
preview = "#e6d9db #2c2525 / #f38d70 #474040"
preview_separator = "#635b5b None / #474040 None"
preview_line_number = "#635b5b #2c2525"
preview_match = "None #635b5b"
hex_null = "#474040 None"
hex_ascii_graphic = "#e6d9db None"
hex_ascii_whitespace = "#f38d70 None"
hex_ascii_other = "#f38d70 None"
hex_non_ascii = "#f38d70 None"
staging_area_title = "#e6d9db None Bold / #f38d70 None"
mode_command_mark = "#e6d9db #f38d70 Bold"
good_to_bad_0 = "#adda78"
good_to_bad_1 = "#adda78"
good_to_bad_2 = "#adda78"
good_to_bad_3 = "#9b9192"
good_to_bad_4 = "#9b9192"
good_to_bad_5 = "#635b5b"
good_to_bad_6 = "#f9cc6c"
good_to_bad_7 = "#f9cc6c"
good_to_bad_8 = "#fd6883"
good_to_bad_9 = "#fd6883"
