[skin]
default = "#d0c8b6 #1b1a17 / #d0c8b6 #36342e"
tree = "#514e46 None / #36342e None"
parent = "#6f8fa3 None / #878276 None"
file = "#d0c8b6 None / #6f8fa3 None"
directory = "#6f8fa3 None Bold / #6f8fa3 None Bold"
exe = "#6f8fa3 None Bold"
link = "#6f8fa3 None Italic"
pruning = "#514e46 None Italic"
perm__ = "#36342e None"
perm_r = "#6f8fa3 None"
perm_w = "#6f8fa3 None"
perm_x = "#6f8fa3 None"
owner = "#878276 None"
group = "#514e46 None"
count = "#6f8fa3 #1b1a17"
dates = "#514e46 None"
sparse = "#6f8fa3 None"
content_extract = "#878276 None Italic"
content_match = "#d0c8b6 None Bold"
device_id_major = "#6f8fa3 None"
device_id_sep = "#514e46 None"
device_id_minor = "#6f8fa3 None"
git_branch = "#d0c8b6 None Bold"
git_insertions = "#6f8fa3 None"
git_deletions = "#6f8fa3 None"
git_status_current = "#36342e None"
git_status_modified = "#6f8fa3 None"
git_status_new = "#d0c8b6 None Bold"
git_status_ignored = "#36342e None"
git_status_conflicted = "#6f8fa3 None Bold"
git_status_other = "#6f8fa3 None"
selected_line = "None #36342e / None #514e46"
char_match = "#d0c8b6 None Bold"
file_error = "#c26a4a None Bold"
flag_label = "#878276 None"
flag_value = "#d0c8b6 None Bold"
input = "#d0c8b6 None / #d0c8b6 #36342e"
status_error = "#d0c8b6 #c26a4a"
status_job = "#d0c8b6 #36342e"
status_normal = "#d0c8b6 #1b1a17 / #1b1a17 #36342e"
status_italic = "#6f8fa3 #1b1a17 Italic / #1b1a17 #36342e"
status_bold = "#6f8fa3 #1b1a17 Bold / #1b1a17 #36342e"
status_code = "#d0c8b6 #1b1a17 / #1b1a17 #36342e"
status_ellipsis = "#878276 #1b1a17 / #1b1a17 #36342e"
purpose_normal = "#d0c8b6 #36342e"
purpose_italic = "#6f8fa3 #36342e Italic"
purpose_bold = "#6f8fa3 #36342e Bold"
purpose_ellipsis = "#878276 #36342e"
scrollbar_track = "#1b1a17 None / #1b1a17 None"
scrollbar_thumb = "#514e46 None / #36342e None"
help_paragraph = "#d0c8b6 None"
help_bold = "#6f8fa3 None Bold"
help_italic = "#6f8fa3 None Italic"
help_code = "#d0c8b6 #36342e"
help_headers = "#6f8fa3 None Bold"
help_table_border = "#514e46 None"
preview_title = "#d0c8b6 None Bold / #6f8fa3 None"
preview = "#d0c8b6 #1b1a17 / #6f8fa3 #36342e"
preview_separator = "#514e46 None / #36342e None"
preview_line_number = "#514e46 #1b1a17"
preview_match = "None #514e46"
hex_null = "#36342e None"
hex_ascii_graphic = "#d0c8b6 None"
hex_ascii_whitespace = "#6f8fa3 None"
hex_ascii_other = "#6f8fa3 None"
hex_non_ascii = "#6f8fa3 None"
staging_area_title = "#d0c8b6 None Bold / #6f8fa3 None"
mode_command_mark = "#1b1a17 #6f8fa3 Bold"
good_to_bad_0 = "#8a9a7b"
good_to_bad_1 = "#8a9a7b"
good_to_bad_2 = "#8a9a7b"
good_to_bad_3 = "#878276"
good_to_bad_4 = "#878276"
good_to_bad_5 = "#514e46"
good_to_bad_6 = "#c2a46a"
good_to_bad_7 = "#c2a46a"
good_to_bad_8 = "#c26a4a"
good_to_bad_9 = "#c26a4a"
