[skin]
default = "#CECDC3 #100F0F / #CECDC3 #2c2b2a"
tree = "#494845 None / #2c2b2a None"
parent = "#205EA6 None / #82817b None"
file = "#CECDC3 None / #205EA6 None"
directory = "#205EA6 None Bold / #205EA6 None Bold"
exe = "#205EA6 None Bold"
link = "#205EA6 None Italic"
pruning = "#494845 None Italic"
perm__ = "#2c2b2a None"
perm_r = "#205EA6 None"
perm_w = "#205EA6 None"
perm_x = "#205EA6 None"
owner = "#82817b None"
group = "#494845 None"
count = "#205EA6 #100F0F"
dates = "#494845 None"
sparse = "#205EA6 None"
content_extract = "#82817b None Italic"
content_match = "#CECDC3 None Bold"
device_id_major = "#205EA6 None"
device_id_sep = "#494845 None"
device_id_minor = "#205EA6 None"
git_branch = "#CECDC3 None Bold"
git_insertions = "#205EA6 None"
git_deletions = "#205EA6 None"
git_status_current = "#2c2b2a None"
git_status_modified = "#205EA6 None"
git_status_new = "#CECDC3 None Bold"
git_status_ignored = "#2c2b2a None"
git_status_conflicted = "#205EA6 None Bold"
git_status_other = "#205EA6 None"
selected_line = "None #2c2b2a / None #494845"
char_match = "#CECDC3 None Bold"
file_error = "#AF3029 None Bold"
flag_label = "#82817b None"
flag_value = "#CECDC3 None Bold"
input = "#CECDC3 None / #CECDC3 #2c2b2a"
status_error = "#CECDC3 #AF3029"
status_job = "#CECDC3 #2c2b2a"
status_normal = "#CECDC3 #100F0F / #CECDC3 #2c2b2a"
status_italic = "#205EA6 #100F0F Italic / #CECDC3 #2c2b2a"
status_bold = "#205EA6 #100F0F Bold / #CECDC3 #2c2b2a"
status_code = "#CECDC3 #100F0F / #CECDC3 #2c2b2a"
status_ellipsis = "#82817b #100F0F / #CECDC3 #2c2b2a"
purpose_normal = "#CECDC3 #2c2b2a"
purpose_italic = "#205EA6 #2c2b2a Italic"
purpose_bold = "#205EA6 #2c2b2a Bold"
purpose_ellipsis = "#82817b #2c2b2a"
scrollbar_track = "#100F0F None / #100F0F None"
scrollbar_thumb = "#494845 None / #2c2b2a None"
help_paragraph = "#CECDC3 None"
help_bold = "#205EA6 None Bold"
help_italic = "#205EA6 None Italic"
help_code = "#CECDC3 #2c2b2a"
help_headers = "#205EA6 None Bold"
help_table_border = "#494845 None"
preview_title = "#CECDC3 None Bold / #205EA6 None"
preview = "#CECDC3 #100F0F / #205EA6 #2c2b2a"
preview_separator = "#494845 None / #2c2b2a None"
preview_line_number = "#494845 #100F0F"
preview_match = "None #494845"
hex_null = "#2c2b2a None"
hex_ascii_graphic = "#CECDC3 None"
hex_ascii_whitespace = "#205EA6 None"
hex_ascii_other = "#205EA6 None"
hex_non_ascii = "#205EA6 None"
staging_area_title = "#CECDC3 None Bold / #205EA6 None"
mode_command_mark = "#CECDC3 #205EA6 Bold"
good_to_bad_0 = "#66800B"
good_to_bad_1 = "#66800B"
good_to_bad_2 = "#66800B"
good_to_bad_3 = "#82817b"
good_to_bad_4 = "#82817b"
good_to_bad_5 = "#494845"
good_to_bad_6 = "#AD8301"
good_to_bad_7 = "#AD8301"
good_to_bad_8 = "#AF3029"
good_to_bad_9 = "#AF3029"
