$background = rgb(100F0F)
$foreground = rgb(CECDC3)
$accent     = rgb(205EA6)
$bg_subtle  = rgb(2c2b2a)
$bg_muted   = rgb(494845)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
