-- noir.lua
vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "noir"
vim.o.termguicolors = true
vim.o.background = "dark"

local c = {
  bg          = "#080909",
  bg_subtle   = "#111312",
  bg_muted    = "#2B2D2B",
  bg_sel      = "#1C1E1C",
  fg          = "#D0D0CA",
  fg_dim      = "#858983",
  fg_faint    = "#444743",
  silver      = "#E4E3DC",
  light       = "#B8BAB4",
  mid         = "#9FA29C",
  warm_grey   = "#A19369",
  olive       = "#87917B",
  sage        = "#A6B197",
  slate       = "#707D82",
  teal        = "#708684",
  mauve       = "#86747B",
  red         = "#A64A40",
  bright_red  = "#C45D52",
  sel_bg      = "#3D403C",
  sel_fg      = "#E8E7E0",
  none        = "NONE",
}

local hi = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

hi("Normal",           { fg = c.fg,        bg = c.bg })
hi("NormalFloat",      { fg = c.fg,        bg = c.bg_subtle })
hi("NormalNC",         { fg = c.fg_dim,    bg = c.bg })
hi("SignColumn",       { fg = c.fg_faint,  bg = c.bg })
hi("ColorColumn",      {                   bg = c.bg_subtle })
hi("CursorLine",       {                   bg = c.bg_subtle })
hi("CursorLineNr",     { fg = c.light,     bg = c.bg_subtle, bold = true })
hi("CursorColumn",     {                   bg = c.bg_subtle })
hi("LineNr",           { fg = c.fg_faint })
hi("Cursor",           { fg = c.bg,        bg = c.light })
hi("TermCursor",       { fg = c.bg,        bg = c.light })
hi("Visual",           { fg = c.sel_fg,    bg = c.sel_bg })
hi("VisualNOS",        { fg = c.sel_fg,    bg = c.sel_bg })
hi("IncSearch",        { fg = c.bg,        bg = c.silver,    bold = true })
hi("Search",           { fg = c.bg,        bg = c.light })
hi("Substitute",       { fg = c.bg,        bg = c.mid })
hi("MatchParen",       { fg = c.silver,    bg = c.none,      bold = true, underline = true })
hi("StatusLine",       { fg = c.fg_dim,    bg = c.bg_muted })
hi("StatusLineNC",     { fg = c.fg_faint,  bg = c.bg_subtle })
hi("WinSeparator",     { fg = c.bg_muted })
hi("VertSplit",        { fg = c.bg_muted })
hi("TabLine",          { fg = c.fg_faint,  bg = c.bg_subtle })
hi("TabLineFill",      {                   bg = c.bg })
hi("TabLineSel",       { fg = c.light,     bg = c.bg_muted,  bold = true })
hi("Pmenu",            { fg = c.fg,        bg = c.bg_subtle })
hi("PmenuSel",         { fg = c.bg,        bg = c.fg_dim,    bold = true })
hi("PmenuSbar",        {                   bg = c.bg_muted })
hi("PmenuThumb",       {                   bg = c.fg_faint })
hi("WildMenu",         { fg = c.bg,        bg = c.light })
hi("Folded",           { fg = c.fg_dim,    bg = c.bg_subtle, italic = true })
hi("FoldColumn",       { fg = c.fg_faint,  bg = c.bg })
hi("EndOfBuffer",      { fg = c.bg_subtle })
hi("NonText",          { fg = c.bg_muted })
hi("SpecialKey",       { fg = c.bg_muted })
hi("Whitespace",       { fg = c.bg_muted })
hi("Directory",        { fg = c.light })
hi("Title",            { fg = c.silver,    bold = true })
hi("Question",         { fg = c.fg_dim })
hi("MoreMsg",          { fg = c.fg_dim })
hi("ModeMsg",          { fg = c.light,     bold = true })
hi("MsgArea",          { fg = c.fg_dim })
hi("ErrorMsg",         { fg = c.bright_red, bold = true })
hi("WarningMsg",       { fg = c.warm_grey })
hi("QuickFixLine",     { fg = c.bg,        bg = c.fg_dim })
hi("SpellBad",         { undercurl = true, sp = c.red })
hi("SpellCap",         { undercurl = true, sp = c.slate })
hi("SpellLocal",       { undercurl = true, sp = c.teal })
hi("SpellRare",        { undercurl = true, sp = c.fg_dim })

hi("Comment",          { fg = c.fg_faint,  italic = true })
hi("Constant",         { fg = c.silver })
hi("String",           { fg = c.fg })
hi("Character",        { fg = c.fg })
hi("Number",           { fg = c.warm_grey })
hi("Boolean",          { fg = c.red,       bold = true })
hi("Float",            { fg = c.warm_grey })
hi("Identifier",       { fg = c.fg_dim })
hi("Function",         { fg = c.light,     bold = true })
hi("Statement",        { fg = c.silver,    bold = true })
hi("Conditional",      { fg = c.silver,    bold = true })
hi("Repeat",           { fg = c.silver,    bold = true })
hi("Label",            { fg = c.silver })
hi("Operator",         { fg = c.fg_faint })
hi("Keyword",          { fg = c.silver,    bold = true })
hi("Exception",        { fg = c.red,       bold = true })
hi("PreProc",          { fg = c.mid })
hi("Include",          { fg = c.mid })
hi("Define",           { fg = c.mid })
hi("Macro",            { fg = c.mid })
hi("PreCondit",        { fg = c.mid })
hi("Type",             { fg = c.light,     bold = true })
hi("StorageClass",     { fg = c.light })
hi("Structure",        { fg = c.light })
hi("Typedef",          { fg = c.light,     bold = true })
hi("Special",          { fg = c.olive })
hi("SpecialChar",      { fg = c.olive })
hi("Tag",              { fg = c.mid })
hi("Delimiter",        { fg = c.fg_faint })
hi("SpecialComment",   { fg = c.fg_faint,  italic = true })
hi("Debug",            { fg = c.red })
hi("Underlined",       { underline = true })
hi("Ignore",           { fg = c.bg_muted })
hi("Error",            { fg = c.red,       bold = true })
hi("Todo",             { fg = c.bg,        bg = c.light,     bold = true })

hi("@variable",               { fg = c.fg_dim })
hi("@variable.builtin",       { fg = c.olive,     italic = true })
hi("@variable.parameter",     { fg = c.fg_dim })
hi("@variable.member",        { fg = c.fg_dim })
hi("@constant",               { fg = c.silver })
hi("@constant.builtin",       { fg = c.red,       bold = true })
hi("@constant.macro",         { fg = c.mid })
hi("@module",                 { fg = c.mid })
hi("@string",                 { fg = c.fg })
hi("@string.escape",          { fg = c.olive })
hi("@string.special",         { fg = c.olive })
hi("@character",              { fg = c.fg })
hi("@number",                 { fg = c.warm_grey })
hi("@float",                  { fg = c.warm_grey })
hi("@boolean",                { fg = c.red,       bold = true })
hi("@function",               { fg = c.light,     bold = true })
hi("@function.builtin",       { fg = c.light,     italic = true })
hi("@function.macro",         { fg = c.light })
hi("@function.call",          { fg = c.light })
hi("@function.method",        { fg = c.light,     bold = true })
hi("@function.method.call",   { fg = c.light })
hi("@constructor",            { fg = c.silver,    bold = true })
hi("@operator",               { fg = c.fg_faint })
hi("@keyword",                { fg = c.silver,    bold = true })
hi("@keyword.function",       { fg = c.silver,    bold = true })
hi("@keyword.return",         { fg = c.red,       bold = true })
hi("@keyword.operator",       { fg = c.fg_faint })
hi("@keyword.import",         { fg = c.mid })
hi("@keyword.conditional",    { fg = c.silver,    bold = true })
hi("@keyword.repeat",         { fg = c.silver,    bold = true })
hi("@keyword.exception",      { fg = c.red,       bold = true })
hi("@type",                   { fg = c.light,     bold = true })
hi("@type.builtin",           { fg = c.light })
hi("@type.definition",        { fg = c.light,     bold = true })
hi("@attribute",              { fg = c.mid })
hi("@property",               { fg = c.fg_dim })
hi("@comment",                { fg = c.fg_faint,  italic = true })
hi("@comment.documentation",  { fg = c.fg_faint,  italic = true })
hi("@punctuation",            { fg = c.fg_faint })
hi("@punctuation.bracket",    { fg = c.fg_faint })
hi("@punctuation.delimiter",  { fg = c.fg_faint })
hi("@tag",                    { fg = c.mid })
hi("@tag.attribute",          { fg = c.fg })
hi("@tag.delimiter",          { fg = c.fg_faint })
hi("@markup.heading",         { fg = c.silver,    bold = true })
hi("@markup.link",            { fg = c.light,     underline = true })
hi("@markup.link.label",      { fg = c.light })
hi("@markup.raw",             { fg = c.olive })
hi("@markup.strong",          { bold = true })
hi("@markup.italic",          { italic = true })
hi("@diff.plus",              { fg = c.sage })
hi("@diff.minus",             { fg = c.red })
hi("@diff.delta",             { fg = c.warm_grey })

hi("DiagnosticError",             { fg = c.red })
hi("DiagnosticWarn",              { fg = c.warm_grey })
hi("DiagnosticInfo",              { fg = c.light })
hi("DiagnosticHint",              { fg = c.fg_dim })
hi("DiagnosticOk",                { fg = c.sage })
hi("DiagnosticUnderlineError",    { undercurl = true, sp = c.red })
hi("DiagnosticUnderlineWarn",     { undercurl = true, sp = c.warm_grey })
hi("DiagnosticUnderlineInfo",     { undercurl = true, sp = c.light })
hi("DiagnosticUnderlineHint",     { undercurl = true, sp = c.fg_faint })
hi("DiagnosticVirtualTextError",  { fg = c.red,      italic = true })
hi("DiagnosticVirtualTextWarn",   { fg = c.warm_grey, italic = true })
hi("DiagnosticVirtualTextInfo",   { fg = c.light,    italic = true })
hi("DiagnosticVirtualTextHint",   { fg = c.fg_dim,   italic = true })
hi("LspReferenceText",            { bg = c.bg_sel })
hi("LspReferenceRead",            { bg = c.bg_sel })
hi("LspReferenceWrite",           { bg = c.bg_sel,   underline = true })
hi("LspInlayHint",                { fg = c.fg_faint, italic = true, bg = c.bg_subtle })

hi("CmpItemAbbr",           { fg = c.fg_dim })
hi("CmpItemAbbrMatch",      { fg = c.silver,   bold = true })
hi("CmpItemAbbrMatchFuzzy", { fg = c.light })
hi("CmpItemKind",           { fg = c.mid })
hi("CmpItemMenu",           { fg = c.fg_faint })

hi("TelescopeBorder",         { fg = c.bg_muted })
hi("TelescopeNormal",         { fg = c.fg_dim,   bg = c.bg_subtle })
hi("TelescopePromptBorder",   { fg = c.fg_dim })
hi("TelescopePromptNormal",   { fg = c.fg,       bg = c.bg_subtle })
hi("TelescopePromptPrefix",   { fg = c.light })
hi("TelescopeSelection",      { fg = c.sel_fg,   bg = c.sel_bg })
hi("TelescopeSelectionCaret", { fg = c.light })
hi("TelescopeMatching",       { fg = c.silver,   bold = true })
hi("TelescopePreviewTitle",   { fg = c.bg,       bg = c.fg_dim })
hi("TelescopePromptTitle",    { fg = c.bg,       bg = c.light })
hi("TelescopeResultsTitle",   { fg = c.bg,       bg = c.bg_muted })

hi("GitSignsAdd",    { fg = c.sage })
hi("GitSignsChange", { fg = c.warm_grey })
hi("GitSignsDelete", { fg = c.red })

hi("IblIndent", { fg = c.bg_subtle })
hi("IblScope",  { fg = c.bg_muted })

hi("WhichKey",          { fg = c.light })
hi("WhichKeyDesc",      { fg = c.fg_dim })
hi("WhichKeyGroup",     { fg = c.mid,      bold = true })
hi("WhichKeySeparator", { fg = c.fg_faint })
hi("WhichKeyFloat",     { bg = c.bg_subtle })

hi("DiffAdd",    { fg = c.sage,      bg = "#0b0f0b" })
hi("DiffChange", { fg = c.warm_grey, bg = "#100f0a" })
hi("DiffDelete", { fg = c.red,       bg = "#110806" })
hi("DiffText",   { fg = c.silver,    bg = "#1c1e1c",  bold = true })
hi("Added",      { fg = c.sage })
hi("Changed",    { fg = c.warm_grey })
hi("Removed",    { fg = c.red })

hi("NvimTreeNormal",        { fg = c.fg_dim,  bg = c.bg_subtle })
hi("NvimTreeFolderIcon",    { fg = c.mid })
hi("NvimTreeRootFolder",    { fg = c.light,   bold = true })
hi("NvimTreeGitDirty",      { fg = c.warm_grey })
hi("NvimTreeGitNew",        { fg = c.sage })
hi("NvimTreeGitDeleted",    { fg = c.red })
hi("NeoTreeNormal",         { fg = c.fg_dim,  bg = c.bg_subtle })
hi("NeoTreeRootName",       { fg = c.light,   bold = true })
hi("NeoTreeGitModified",    { fg = c.warm_grey })
hi("NeoTreeGitAdded",       { fg = c.sage })
hi("NeoTreeGitDeleted",     { fg = c.red })
hi("FlashLabel",            { fg = c.bg,      bg = c.silver,  bold = true })
hi("FlashCurrent",          { fg = c.bg,      bg = c.red })
hi("MiniStatuslineFilename",   { fg = c.fg_dim,  bg = c.bg_muted })
hi("MiniStatuslineModeNormal", { fg = c.bg,      bg = c.light,  bold = true })
hi("MiniStatuslineModeInsert", { fg = c.bg,      bg = c.fg_dim, bold = true })
hi("MiniStatuslineModeVisual", { fg = c.bg,      bg = c.mid,    bold = true })
hi("NotifyERRORBorder", { fg = c.red })
hi("NotifyERRORTitle",  { fg = c.red,       bold = true })
hi("NotifyWARNBorder",  { fg = c.warm_grey })
hi("NotifyWARNTitle",   { fg = c.warm_grey, bold = true })
hi("NotifyINFOBorder",  { fg = c.light })
hi("NotifyINFOTitle",   { fg = c.light,     bold = true })
