[skin]
default = "#c2c2b0 #222222 / #c2c2b0 #3a3a37"
tree = "#52524c None / #3a3a37 None"
parent = "#78824b None / #828277 None"
file = "#c2c2b0 None / #78824b None"
directory = "#78824b None Bold / #78824b None Bold"
exe = "#78824b None Bold"
link = "#78824b None Italic"
pruning = "#52524c None Italic"
perm__ = "#3a3a37 None"
perm_r = "#78824b None"
perm_w = "#78824b None"
perm_x = "#78824b None"
owner = "#828277 None"
group = "#52524c None"
count = "#78824b #222222"
dates = "#52524c None"
sparse = "#78824b None"
content_extract = "#828277 None Italic"
content_match = "#c2c2b0 None Bold"
device_id_major = "#78824b None"
device_id_sep = "#52524c None"
device_id_minor = "#78824b None"
git_branch = "#c2c2b0 None Bold"
git_insertions = "#78824b None"
git_deletions = "#78824b None"
git_status_current = "#3a3a37 None"
git_status_modified = "#78824b None"
git_status_new = "#c2c2b0 None Bold"
git_status_ignored = "#3a3a37 None"
git_status_conflicted = "#78824b None Bold"
git_status_other = "#78824b None"
selected_line = "None #3a3a37 / None #52524c"
char_match = "#c2c2b0 None Bold"
file_error = "#685742 None Bold"
flag_label = "#828277 None"
flag_value = "#c2c2b0 None Bold"
input = "#c2c2b0 None / #c2c2b0 #3a3a37"
status_error = "#c2c2b0 #685742"
status_job = "#c2c2b0 #3a3a37"
status_normal = "#c2c2b0 #222222 / #c2c2b0 #3a3a37"
status_italic = "#78824b #222222 Italic / #c2c2b0 #3a3a37"
status_bold = "#78824b #222222 Bold / #c2c2b0 #3a3a37"
status_code = "#c2c2b0 #222222 / #c2c2b0 #3a3a37"
status_ellipsis = "#828277 #222222 / #c2c2b0 #3a3a37"
purpose_normal = "#c2c2b0 #3a3a37"
purpose_italic = "#78824b #3a3a37 Italic"
purpose_bold = "#78824b #3a3a37 Bold"
purpose_ellipsis = "#828277 #3a3a37"
scrollbar_track = "#222222 None / #222222 None"
scrollbar_thumb = "#52524c None / #3a3a37 None"
help_paragraph = "#c2c2b0 None"
help_bold = "#78824b None Bold"
help_italic = "#78824b None Italic"
help_code = "#c2c2b0 #3a3a37"
help_headers = "#78824b None Bold"
help_table_border = "#52524c None"
preview_title = "#c2c2b0 None Bold / #78824b None"
preview = "#c2c2b0 #222222 / #78824b #3a3a37"
preview_separator = "#52524c None / #3a3a37 None"
preview_line_number = "#52524c #222222"
preview_match = "None #52524c"
hex_null = "#3a3a37 None"
hex_ascii_graphic = "#c2c2b0 None"
hex_ascii_whitespace = "#78824b None"
hex_ascii_other = "#78824b None"
hex_non_ascii = "#78824b None"
staging_area_title = "#c2c2b0 None Bold / #78824b None"
mode_command_mark = "#c2c2b0 #78824b Bold"
good_to_bad_0 = "#5f875f"
good_to_bad_1 = "#5f875f"
good_to_bad_2 = "#5f875f"
good_to_bad_3 = "#828277"
good_to_bad_4 = "#828277"
good_to_bad_5 = "#52524c"
good_to_bad_6 = "#b36d43"
good_to_bad_7 = "#b36d43"
good_to_bad_8 = "#685742"
good_to_bad_9 = "#685742"
