$background = rgb(222222)
$foreground = rgb(c2c2b0)
$accent     = rgb(78824b)
$bg_subtle  = rgb(3a3a37)
$bg_muted   = rgb(52524c)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
