[palettes.miasma]
bg               = '#222222'
bg_subtle        = '#3a3a37'
bg_muted         = '#52524c'
fg               = '#c2c2b0'
fg_dim           = '#828277'
sel_bg           = '#78824b'
sel_fg           = '#c2c2b0'
error            = '#685742'
accent           = '#78824b'
fg_on_accent     = '#c2c2b0'
success          = '#5f875f'
warning          = '#b36d43'
cursor           = '#c7c7c7'
