[palettes.miasma]
base             = '#222222'
crust            = '#52524c'
on_sig1          = '#222222'
on_sig2          = '#c2c2b0'
on_sigbg         = '#c2c2b0'
red              = '#685742'
sig1             = '#78824b'
sig2             = '#bb7744'
sig_bg           = '#222222'
sig_surface_high = '#3a3a37'
text             = '#c2c2b0'
