[mgr]
cwd = { fg = "#c2c2b0" }
find_keyword = { fg = "#685742", bold = true, italic = true, underline = true }
find_position = { fg = "#685742", bold = true, italic = true }
marker_copied = { fg = "#bb7744", bg = "#bb7744" }
marker_cut = { fg = "#828277", bg = "#828277" }
marker_marked = { fg = "#78824b", bg = "#78824b" }
marker_selected = { fg = "#5f875f", bg = "#5f875f" }
count_copied = { fg = "#222222", bg = "#828277" }
count_cut = { fg = "#222222", bg = "#828277" }
count_selected = { fg = "#222222", bg = "#5f875f" }
border_symbol = " "
border_style = { fg = "#78824b" }

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }
perm_type = { fg = "#78824b" }
perm_read = { fg = "#c2c2b0" }
perm_write = { fg = "#5f875f" }
perm_exec = { fg = "#bb7744" }
perm_sep = { fg = "#828277" }
progress_label = { bold = true }
progress_normal = { fg = "#78824b", bg = "#3a3a37" }
progress_error = { fg = "#bb7744", bg = "#3a3a37" }

[mode]
normal_main = { bg = "#78824b", fg = "#222222", bold = true }
normal_alt  = { bg = "#3a3a37", fg = "#c2c2b0" }
select_main = { bg = "#828277", fg = "#222222", bold = true }
select_alt  = { bg = "#3a3a37", fg = "#c2c2b0" }
unset_main = { bg = "#5f875f", fg = "#222222", bold = true }
unset_alt  = { bg = "#3a3a37", fg = "#c2c2b0" }

[select]
border = { fg = "#78824b" }
active = { fg = "#5f875f", bold = true }

[input]
border = { fg = "#78824b" }
value = { fg = "#c2c2b0" }

[tabs]
active = { fg = "#78824b", bold = true, bg = "#222222" }
inactive = { fg = "#828277", bg = "#222222" }
sep_inner = { open = "[", close = "]" }

[cmp]
border = { fg = "#78824b", bg = "#3a3a37" }

[tasks]
border = { fg = "#78824b" }
title = {}
hovered = { fg = "#828277", underline = true }

[which]
cols = 3
mask = { bg = "#3a3a37" }
cand = { fg = "#78824b" }
rest = { fg = "#222222" }
desc = { fg = "#c2c2b0" }
separator = " ▶ "
separator_style = { fg = "#c2c2b0" }

[help]
on = { fg = "#c2c2b0" }
run = { fg = "#c2c2b0" }
footer = { fg = "#222222", bg = "#828277" }

[notify]
title_info = { fg = "#5f875f" }
title_warn = { fg = "#78824b" }
title_error = { fg = "#bb7744" }

[filetype]
rules = [
    { mime = "image/*", fg = "#5f875f" },
    { mime = "{audio,video}/*", fg = "#78824b" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#828277" },
    { mime = "application/{pdf,doc,rtf}", fg = "#c2c2b0" },
    { url = "*", is = "orphan", bg = "#bb7744" },
    { url = "*", is = "exec", fg = "#828277" },
    { url = "*", fg = "#c2c2b0" },
    { url = "*/", fg = "#78824b" },
]
