[skin]
default = "#b4d0dd #090d15 / #b4d0dd #222a33"
tree = "#3c4751 None / #222a33 None"
parent = "#97a6bb None / #6f828d None"
file = "#b4d0dd None / #97a6bb None"
directory = "#97a6bb None Bold / #97a6bb None Bold"
exe = "#97a6bb None Bold"
link = "#97a6bb None Italic"
pruning = "#3c4751 None Italic"
perm__ = "#222a33 None"
perm_r = "#97a6bb None"
perm_w = "#97a6bb None"
perm_x = "#97a6bb None"
owner = "#6f828d None"
group = "#3c4751 None"
count = "#97a6bb #090d15"
dates = "#3c4751 None"
sparse = "#97a6bb None"
content_extract = "#6f828d None Italic"
content_match = "#b4d0dd None Bold"
device_id_major = "#97a6bb None"
device_id_sep = "#3c4751 None"
device_id_minor = "#97a6bb None"
git_branch = "#b4d0dd None Bold"
git_insertions = "#97a6bb None"
git_deletions = "#97a6bb None"
git_status_current = "#222a33 None"
git_status_modified = "#97a6bb None"
git_status_new = "#b4d0dd None Bold"
git_status_ignored = "#222a33 None"
git_status_conflicted = "#97a6bb None Bold"
git_status_other = "#97a6bb None"
selected_line = "None #222a33 / None #3c4751"
char_match = "#b4d0dd None Bold"
file_error = "#6e7b91 None Bold"
flag_label = "#6f828d None"
flag_value = "#b4d0dd None Bold"
input = "#b4d0dd None / #b4d0dd #222a33"
status_error = "#b4d0dd #6e7b91"
status_job = "#b4d0dd #222a33"
status_normal = "#b4d0dd #090d15 / #090d15 #222a33"
status_italic = "#97a6bb #090d15 Italic / #090d15 #222a33"
status_bold = "#97a6bb #090d15 Bold / #090d15 #222a33"
status_code = "#b4d0dd #090d15 / #090d15 #222a33"
status_ellipsis = "#6f828d #090d15 / #090d15 #222a33"
purpose_normal = "#b4d0dd #222a33"
purpose_italic = "#97a6bb #222a33 Italic"
purpose_bold = "#97a6bb #222a33 Bold"
purpose_ellipsis = "#6f828d #222a33"
scrollbar_track = "#090d15 None / #090d15 None"
scrollbar_thumb = "#3c4751 None / #222a33 None"
help_paragraph = "#b4d0dd None"
help_bold = "#97a6bb None Bold"
help_italic = "#97a6bb None Italic"
help_code = "#b4d0dd #222a33"
help_headers = "#97a6bb None Bold"
help_table_border = "#3c4751 None"
preview_title = "#b4d0dd None Bold / #97a6bb None"
preview = "#b4d0dd #090d15 / #97a6bb #222a33"
preview_separator = "#3c4751 None / #222a33 None"
preview_line_number = "#3c4751 #090d15"
preview_match = "None #3c4751"
hex_null = "#222a33 None"
hex_ascii_graphic = "#b4d0dd None"
hex_ascii_whitespace = "#97a6bb None"
hex_ascii_other = "#97a6bb None"
hex_non_ascii = "#97a6bb None"
staging_area_title = "#b4d0dd None Bold / #97a6bb None"
mode_command_mark = "#090d15 #97a6bb Bold"
good_to_bad_0 = "#667e8c"
good_to_bad_1 = "#667e8c"
good_to_bad_2 = "#667e8c"
good_to_bad_3 = "#6f828d"
good_to_bad_4 = "#6f828d"
good_to_bad_5 = "#3c4751"
good_to_bad_6 = "#7e96a5"
good_to_bad_7 = "#7e96a5"
good_to_bad_8 = "#6e7b91"
good_to_bad_9 = "#6e7b91"
