[palettes.gojira]
bg               = '#090d15'
bg_subtle        = '#222a33'
bg_muted         = '#3c4751'
fg               = '#b4d0dd'
fg_dim           = '#6f828d'
sel_bg           = '#97a6bb'
sel_fg           = '#090d15'
error            = '#6e7b91'
accent           = '#97a6bb'
fg_on_accent     = '#b4d0dd'
success          = '#667e8c'
warning          = '#7e96a5'
cursor           = '#b4d0dd'
