[mgr]
cwd = { fg = "#b4d0dd" }
find_keyword = { fg = "#6e7b91", bold = true, italic = true, underline = true }
find_position = { fg = "#6e7b91", bold = true, italic = true }
marker_copied = { fg = "#6d7b91", bg = "#6d7b91" }
marker_cut = { fg = "#6f828d", bg = "#6f828d" }
marker_marked = { fg = "#97a6bb", bg = "#97a6bb" }
marker_selected = { fg = "#667e8c", bg = "#667e8c" }
count_copied = { fg = "#090d15", bg = "#6f828d" }
count_cut = { fg = "#090d15", bg = "#6f828d" }
count_selected = { fg = "#090d15", bg = "#667e8c" }
border_symbol = " "
border_style = { fg = "#97a6bb" }

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }
perm_type = { fg = "#97a6bb" }
perm_read = { fg = "#b4d0dd" }
perm_write = { fg = "#667e8c" }
perm_exec = { fg = "#6d7b91" }
perm_sep = { fg = "#6f828d" }
progress_label = { bold = true }
progress_normal = { fg = "#97a6bb", bg = "#222a33" }
progress_error = { fg = "#6d7b91", bg = "#222a33" }

[mode]
normal_main = { bg = "#97a6bb", fg = "#090d15", bold = true }
normal_alt  = { bg = "#222a33", fg = "#b4d0dd" }
select_main = { bg = "#6f828d", fg = "#090d15", bold = true }
select_alt  = { bg = "#222a33", fg = "#b4d0dd" }
unset_main = { bg = "#667e8c", fg = "#090d15", bold = true }
unset_alt  = { bg = "#222a33", fg = "#b4d0dd" }

[select]
border = { fg = "#97a6bb" }
active = { fg = "#667e8c", bold = true }

[input]
border = { fg = "#97a6bb" }
value = { fg = "#b4d0dd" }

[tabs]
active = { fg = "#97a6bb", bold = true, bg = "#090d15" }
inactive = { fg = "#6f828d", bg = "#090d15" }
sep_inner = { open = "[", close = "]" }

[cmp]
border = { fg = "#97a6bb", bg = "#222a33" }

[tasks]
border = { fg = "#97a6bb" }
title = {}
hovered = { fg = "#6f828d", underline = true }

[which]
cols = 3
mask = { bg = "#222a33" }
cand = { fg = "#97a6bb" }
rest = { fg = "#090d15" }
desc = { fg = "#b4d0dd" }
separator = " ▶ "
separator_style = { fg = "#b4d0dd" }

[help]
on = { fg = "#b4d0dd" }
run = { fg = "#b4d0dd" }
footer = { fg = "#090d15", bg = "#6f828d" }

[notify]
title_info = { fg = "#667e8c" }
title_warn = { fg = "#97a6bb" }
title_error = { fg = "#6d7b91" }

[filetype]
rules = [
    { mime = "image/*", fg = "#667e8c" },
    { mime = "{audio,video}/*", fg = "#97a6bb" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#6f828d" },
    { mime = "application/{pdf,doc,rtf}", fg = "#b4d0dd" },
    { url = "*", is = "orphan", bg = "#6d7b91" },
    { url = "*", is = "exec", fg = "#6f828d" },
    { url = "*", fg = "#b4d0dd" },
    { url = "*/", fg = "#97a6bb" },
]
