[skin]
default = "#dcd7ba #1f1f28 / #dcd7ba #3b3a3d"
tree = "#575653 None / #3b3a3d None"
parent = "#7e9cd8 None / #908d7f None"
file = "#dcd7ba None / #7e9cd8 None"
directory = "#7e9cd8 None Bold / #7e9cd8 None Bold"
exe = "#7e9cd8 None Bold"
link = "#7e9cd8 None Italic"
pruning = "#575653 None Italic"
perm__ = "#3b3a3d None"
perm_r = "#7e9cd8 None"
perm_w = "#7e9cd8 None"
perm_x = "#7e9cd8 None"
owner = "#908d7f None"
group = "#575653 None"
count = "#7e9cd8 #1f1f28"
dates = "#575653 None"
sparse = "#7e9cd8 None"
content_extract = "#908d7f None Italic"
content_match = "#dcd7ba None Bold"
device_id_major = "#7e9cd8 None"
device_id_sep = "#575653 None"
device_id_minor = "#7e9cd8 None"
git_branch = "#dcd7ba None Bold"
git_insertions = "#7e9cd8 None"
git_deletions = "#7e9cd8 None"
git_status_current = "#3b3a3d None"
git_status_modified = "#7e9cd8 None"
git_status_new = "#dcd7ba None Bold"
git_status_ignored = "#3b3a3d None"
git_status_conflicted = "#7e9cd8 None Bold"
git_status_other = "#7e9cd8 None"
selected_line = "None #3b3a3d / None #575653"
char_match = "#dcd7ba None Bold"
file_error = "#c34043 None Bold"
flag_label = "#908d7f None"
flag_value = "#dcd7ba None Bold"
input = "#dcd7ba None / #dcd7ba #3b3a3d"
status_error = "#dcd7ba #c34043"
status_job = "#dcd7ba #3b3a3d"
status_normal = "#dcd7ba #1f1f28 / #c8c093 #3b3a3d"
status_italic = "#7e9cd8 #1f1f28 Italic / #c8c093 #3b3a3d"
status_bold = "#7e9cd8 #1f1f28 Bold / #c8c093 #3b3a3d"
status_code = "#dcd7ba #1f1f28 / #c8c093 #3b3a3d"
status_ellipsis = "#908d7f #1f1f28 / #c8c093 #3b3a3d"
purpose_normal = "#dcd7ba #3b3a3d"
purpose_italic = "#7e9cd8 #3b3a3d Italic"
purpose_bold = "#7e9cd8 #3b3a3d Bold"
purpose_ellipsis = "#908d7f #3b3a3d"
scrollbar_track = "#1f1f28 None / #1f1f28 None"
scrollbar_thumb = "#575653 None / #3b3a3d None"
help_paragraph = "#dcd7ba None"
help_bold = "#7e9cd8 None Bold"
help_italic = "#7e9cd8 None Italic"
help_code = "#dcd7ba #3b3a3d"
help_headers = "#7e9cd8 None Bold"
help_table_border = "#575653 None"
preview_title = "#dcd7ba None Bold / #7e9cd8 None"
preview = "#dcd7ba #1f1f28 / #7e9cd8 #3b3a3d"
preview_separator = "#575653 None / #3b3a3d None"
preview_line_number = "#575653 #1f1f28"
preview_match = "None #575653"
hex_null = "#3b3a3d None"
hex_ascii_graphic = "#dcd7ba None"
hex_ascii_whitespace = "#7e9cd8 None"
hex_ascii_other = "#7e9cd8 None"
hex_non_ascii = "#7e9cd8 None"
staging_area_title = "#dcd7ba None Bold / #7e9cd8 None"
mode_command_mark = "#c8c093 #7e9cd8 Bold"
good_to_bad_0 = "#76946a"
good_to_bad_1 = "#76946a"
good_to_bad_2 = "#76946a"
good_to_bad_3 = "#908d7f"
good_to_bad_4 = "#908d7f"
good_to_bad_5 = "#575653"
good_to_bad_6 = "#c0a36e"
good_to_bad_7 = "#c0a36e"
good_to_bad_8 = "#c34043"
good_to_bad_9 = "#c34043"
