$background = rgb(1f1f28)
$foreground = rgb(dcd7ba)
$accent     = rgb(7e9cd8)
$bg_subtle  = rgb(3b3a3d)
$bg_muted   = rgb(575653)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
