[palettes.kanagawa]
bg               = '#1f1f28'
bg_subtle        = '#3b3a3d'
bg_muted         = '#575653'
fg               = '#dcd7ba'
fg_dim           = '#908d7f'
sel_bg           = '#2d4f67'
sel_fg           = '#c8c093'
error            = '#c34043'
accent           = '#7e9cd8'
fg_on_accent     = '#dcd7ba'
success          = '#76946a'
warning          = '#c0a36e'
cursor           = '#c8c093'
