[palettes.kanagawa]
base             = '#1f1f28'
crust            = '#575653'
on_sig1          = '#1f1f28'
on_sig2          = '#dcd7ba'
on_sigbg         = '#dcd7ba'
red              = '#c34043'
sig1             = '#7e9cd8'
sig2             = '#957fb8'
sig_bg           = '#1f1f28'
sig_surface_high = '#3b3a3d'
text             = '#dcd7ba'
