[mgr]
cwd = { fg = "#dcd7ba" }
find_keyword = { fg = "#c34043", bold = true, italic = true, underline = true }
find_position = { fg = "#c34043", bold = true, italic = true }
marker_copied = { fg = "#957fb8", bg = "#957fb8" }
marker_cut = { fg = "#908d7f", bg = "#908d7f" }
marker_marked = { fg = "#7e9cd8", bg = "#7e9cd8" }
marker_selected = { fg = "#76946a", bg = "#76946a" }
count_copied = { fg = "#1f1f28", bg = "#908d7f" }
count_cut = { fg = "#1f1f28", bg = "#908d7f" }
count_selected = { fg = "#1f1f28", bg = "#76946a" }
border_symbol = " "
border_style = { fg = "#7e9cd8" }

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }
perm_type = { fg = "#7e9cd8" }
perm_read = { fg = "#dcd7ba" }
perm_write = { fg = "#76946a" }
perm_exec = { fg = "#957fb8" }
perm_sep = { fg = "#908d7f" }
progress_label = { bold = true }
progress_normal = { fg = "#7e9cd8", bg = "#3b3a3d" }
progress_error = { fg = "#957fb8", bg = "#3b3a3d" }

[mode]
normal_main = { bg = "#7e9cd8", fg = "#1f1f28", bold = true }
normal_alt  = { bg = "#3b3a3d", fg = "#dcd7ba" }
select_main = { bg = "#908d7f", fg = "#1f1f28", bold = true }
select_alt  = { bg = "#3b3a3d", fg = "#dcd7ba" }
unset_main = { bg = "#76946a", fg = "#1f1f28", bold = true }
unset_alt  = { bg = "#3b3a3d", fg = "#dcd7ba" }

[select]
border = { fg = "#7e9cd8" }
active = { fg = "#76946a", bold = true }

[input]
border = { fg = "#7e9cd8" }
value = { fg = "#dcd7ba" }

[tabs]
active = { fg = "#7e9cd8", bold = true, bg = "#1f1f28" }
inactive = { fg = "#908d7f", bg = "#1f1f28" }
sep_inner = { open = "[", close = "]" }

[cmp]
border = { fg = "#7e9cd8", bg = "#3b3a3d" }

[tasks]
border = { fg = "#7e9cd8" }
title = {}
hovered = { fg = "#908d7f", underline = true }

[which]
cols = 3
mask = { bg = "#3b3a3d" }
cand = { fg = "#7e9cd8" }
rest = { fg = "#1f1f28" }
desc = { fg = "#dcd7ba" }
separator = " ▶ "
separator_style = { fg = "#dcd7ba" }

[help]
on = { fg = "#dcd7ba" }
run = { fg = "#dcd7ba" }
footer = { fg = "#1f1f28", bg = "#908d7f" }

[notify]
title_info = { fg = "#76946a" }
title_warn = { fg = "#7e9cd8" }
title_error = { fg = "#957fb8" }

[filetype]
rules = [
    { mime = "image/*", fg = "#76946a" },
    { mime = "{audio,video}/*", fg = "#7e9cd8" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#908d7f" },
    { mime = "application/{pdf,doc,rtf}", fg = "#dcd7ba" },
    { url = "*", is = "orphan", bg = "#957fb8" },
    { url = "*", is = "exec", fg = "#908d7f" },
    { url = "*", fg = "#dcd7ba" },
    { url = "*/", fg = "#7e9cd8" },
]
