# : Manager [[[

[mgr]
cwd = { fg = "#dcd7ba" }

# Find
find_keyword = { fg = "#c34043", bold = true, italic = true, underline = true }
find_position = { fg = "#c34043", bold = true, italic = true }

# Marker
marker_copied = { fg = "#e6c384", bg = "#e6c384" }
marker_cut = { fg = "#dcd7ba", bg = "#dcd7ba" }
marker_marked = { fg = "#7fb4ca", bg = "#7fb4ca" }
marker_selected = { fg = "#8e8d87", bg = "#8e8d87" }

# Count
count_copied = { fg = "#1f1f28", bg = "#dcd7ba" }
count_cut = { fg = "#1f1f28", bg = "#dcd7ba" }
count_selected = { fg = "#16161d", bg = "#8e8d87" }

# Border
border_symbol = " "
border_style = { fg = "#7fb4ca" }

# : ]]]


# : Status [[[

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }

# Permissions
perm_type = { fg = "#7fb4ca" }
perm_read = { fg = "#dcd7ba" }
perm_write = { fg = "#8e8d87" }
perm_exec = { fg = "#e6c384" }
perm_sep = { fg = "#dcd7ba" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#7fb4ca", bg = "#727169" }
progress_error = { fg = "#e6c384", bg = "#727169" }

[mode]
normal_main = { bg = "#7fb4ca", fg = "#16161d", bold = true }
normal_alt  = { bg = "#727169", fg = "#dcd7ba" }

select_main = { bg = "#dcd7ba", fg = "#16161d", bold = true }
select_alt  = { bg = "#727169", fg = "#dcd7ba" }

unset_main = { bg = "#8e8d87", fg = "#16161d", bold = true }
unset_alt  = { bg = "#727169", fg = "#dcd7ba" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#7fb4ca" }
active = { fg = "#8e8d87", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#7fb4ca" }
value = { fg = "#dcd7ba" }

# : ]]]


# : Tabs [[[

[tabs]
active = { fg = "#7fb4ca", bold = true, bg = "#1f1f28" }
inactive = { fg = "#dcd7ba", bg = "#1f1f28" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#7fb4ca", bg = "#727169" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#7fb4ca" }
title = {}
hovered = { fg = "#dcd7ba", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#727169" }
cand = { fg = "#7fb4ca" }
rest = { fg = "#16161d" }
desc = { fg = "#dcd7ba" }
separator = " ▶ "
separator_style = { fg = "#dcd7ba" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dcd7ba" }
run = { fg = "#dcd7ba" }
footer = { fg = "#16161d", bg = "#dcd7ba" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#8e8d87" }
title_warn = { fg = "#7fb4ca" }
title_error = { fg = "#e6c384" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    { mime = "image/*", fg = "#8e8d87" },
    { mime = "{audio,video}/*", fg = "#7fb4ca" },

    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#dcd7ba" },

    { mime = "application/{pdf,doc,rtf}", fg = "#dcd7ba" },

    { url = "*", is = "orphan", bg = "#e6c384" },
    { url = "*", is = "exec", fg = "#dcd7ba" },

    { url = "*", fg = "#dcd7ba" },
    { url = "*/", fg = "#7fb4ca" },
]

# : ]]]
