exec-once = mkdir -p $screenshot_dir
exec-once = mako
exec-once = pavucontrol --hide-window --start-hidden
exec-once = hypridle
exec-once =  swaybg -o "*" -i ~/.config/zorro/current/background -m fill
# exec-once = swayidle -w timeout 300 'swaylock -f' timeout 600 'systemctl suspend'
# exec-once = swayidle -w before-sleep 'swaylock -f -C /home/rey/.config/hypr/swaylock.conf' timeout 300 'swaylock -f -C /home/rey/.config/hypr/swaylock.conf' timeout 600 'systemctl hibernate'
