# =============================================================================
# variables.conf — shared variables
# Override any of these in _variables.conf without touching this file.
# =============================================================================

$mod            = SUPER
$menu           = wofi --show drun
$screenshot_dir = ~/Pictures/screenshots

$opacity  = 0.9
$term     = foot
$term2    = kitty
$launcher = rofi -show drun -theme ~/.config/rofi/launcher.rasi
$browser  = librewolf
$files    = thunar
$fm       = $term -e superb
$tfm      = $term -e yazi
$editor   = $term -e nvim

$menu       = $launcher
$lockscreen = hyprlock
# bind = $mainMod, L, exec, swaylock -f
