[skin]
default = "#FAFCFB #0c0b0c / #FAFCFB #2f2f2f"
tree = "#535353 None / #2f2f2f None"
parent = "#b59790 None / #9a9b9b None"
file = "#FAFCFB None / #b59790 None"
directory = "#b59790 None Bold / #b59790 None Bold"
exe = "#b59790 None Bold"
link = "#b59790 None Italic"
pruning = "#535353 None Italic"
perm__ = "#2f2f2f None"
perm_r = "#b59790 None"
perm_w = "#b59790 None"
perm_x = "#b59790 None"
owner = "#9a9b9b None"
group = "#535353 None"
count = "#b59790 #0c0b0c"
dates = "#535353 None"
sparse = "#b59790 None"
content_extract = "#9a9b9b None Italic"
content_match = "#FAFCFB None Bold"
device_id_major = "#b59790 None"
device_id_sep = "#535353 None"
device_id_minor = "#b59790 None"
git_branch = "#FAFCFB None Bold"
git_insertions = "#b59790 None"
git_deletions = "#b59790 None"
git_status_current = "#2f2f2f None"
git_status_modified = "#b59790 None"
git_status_new = "#FAFCFB None Bold"
git_status_ignored = "#2f2f2f None"
git_status_conflicted = "#b59790 None Bold"
git_status_other = "#b59790 None"
selected_line = "None #2f2f2f / None #535353"
char_match = "#FAFCFB None Bold"
file_error = "#c38b7b None Bold"
flag_label = "#9a9b9b None"
flag_value = "#FAFCFB None Bold"
input = "#FAFCFB None / #FAFCFB #2f2f2f"
status_error = "#FAFCFB #c38b7b"
status_job = "#FAFCFB #2f2f2f"
status_normal = "#FAFCFB #0c0b0c / #0c0b0c #2f2f2f"
status_italic = "#b59790 #0c0b0c Italic / #0c0b0c #2f2f2f"
status_bold = "#b59790 #0c0b0c Bold / #0c0b0c #2f2f2f"
status_code = "#FAFCFB #0c0b0c / #0c0b0c #2f2f2f"
status_ellipsis = "#9a9b9b #0c0b0c / #0c0b0c #2f2f2f"
purpose_normal = "#FAFCFB #2f2f2f"
purpose_italic = "#b59790 #2f2f2f Italic"
purpose_bold = "#b59790 #2f2f2f Bold"
purpose_ellipsis = "#9a9b9b #2f2f2f"
scrollbar_track = "#0c0b0c None / #0c0b0c None"
scrollbar_thumb = "#535353 None / #2f2f2f None"
help_paragraph = "#FAFCFB None"
help_bold = "#b59790 None Bold"
help_italic = "#b59790 None Italic"
help_code = "#FAFCFB #2f2f2f"
help_headers = "#b59790 None Bold"
help_table_border = "#535353 None"
preview_title = "#FAFCFB None Bold / #b59790 None"
preview = "#FAFCFB #0c0b0c / #b59790 #2f2f2f"
preview_separator = "#535353 None / #2f2f2f None"
preview_line_number = "#535353 #0c0b0c"
preview_match = "None #535353"
hex_null = "#2f2f2f None"
hex_ascii_graphic = "#FAFCFB None"
hex_ascii_whitespace = "#b59790 None"
hex_ascii_other = "#b59790 None"
hex_non_ascii = "#b59790 None"
staging_area_title = "#FAFCFB None Bold / #b59790 None"
mode_command_mark = "#0c0b0c #b59790 Bold"
good_to_bad_0 = "#87a9b0"
good_to_bad_1 = "#87a9b0"
good_to_bad_2 = "#87a9b0"
good_to_bad_3 = "#9a9b9b"
good_to_bad_4 = "#9a9b9b"
good_to_bad_5 = "#535353"
good_to_bad_6 = "#6B5E73"
good_to_bad_7 = "#6B5E73"
good_to_bad_8 = "#c38b7b"
good_to_bad_9 = "#c38b7b"
