$background = rgb(0c0b0c)
$foreground = rgb(FAFCFB)
$accent     = rgb(b59790)
$bg_subtle  = rgb(2f2f2f)
$bg_muted   = rgb(535353)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
