[palettes.last-horizon]
bg               = '#0c0b0c'
bg_subtle        = '#2f2f2f'
bg_muted         = '#535353'
fg               = '#FAFCFB'
fg_dim           = '#9a9b9b'
sel_bg           = '#FAFCFB'
sel_fg           = '#0c0b0c'
error            = '#c38b7b'
accent           = '#b59790'
fg_on_accent     = '#FAFCFB'
success          = '#87a9b0'
warning          = '#6B5E73'
cursor           = '#e2dddc'
