# : Manager [[[

[mgr]
cwd = { fg = "#FAFCFB" }

# Tab
tab_active = { fg = "#0c0b0c", bg = "#b59790", bold = true }
tab_inactive = { fg = "#FAFCFB", bg = "#584e51" }
tab_width = 1

# Find
find_keyword = { fg = "#c38b7b", bold = true, italic = true, underline = true }
find_position = { fg = "#c38b7b", bold = true, italic = true }

# Marker
marker_copied = { fg = "#87a9b0", bg = "#87a9b0" }
marker_cut = { fg = "#e2dddc", bg = "#e2dddc" }
marker_marked = { fg = "#b59790", bg = "#b59790" }
marker_selected = { fg = "#3c3b3c", bg = "#3c3b3c" }

# Count
count_copied = { fg = "#0c0b0c", bg = "#e2dddc" }
count_cut = { fg = "#0c0b0c", bg = "#e2dddc" }
count_selected = { fg = "#0c0b0c", bg = "#3c3b3c" }

# Border
border_symbol = " "
border_style  = { fg = "#b59790" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#584e51", fg = "#b59790" }

[mode]
# Mode
normal_main = { bg = "#b59790", fg = "#0c0b0c", bold = true }
normal_alt  = { bg = "#0c0b0c", fg = "#FAFCFB" }

# Select mode
select_main = { bg = "#e2dddc", fg = "#0c0b0c", bold = true }
select_alt  = { bg = "#0c0b0c", fg = "#FAFCFB" }

# Unset mode
unset_main = { bg = "#3c3b3c", fg = "#0c0b0c", bold = true }
unset_alt  = { bg = "#0c0b0c", fg = "#FAFCFB" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#b59790", bg = "#0c0b0c" }
progress_error = { fg = "#87a9b0", bg = "#0c0b0c" }

# Permissions
permissions_t = { fg = "#b59790" }
permissions_w = { fg = "#3c3b3c" }
permissions_x = { fg = "#87a9b0" }
permissions_r = { fg = "#FAFCFB" }
permissions_s = { fg = "#e2dddc" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#b59790" }
active = { fg = "#3c3b3c", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#b59790" }
value = { fg = "#FAFCFB" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#b59790", bold = true, bg = "#0c0b0c" }
inactive = { fg = "#e2dddc", bg = "#0c0b0c" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#b59790", bg = "#584e51" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#b59790" }
title = {}
hovered = { fg = "#e2dddc", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#0c0b0c" }
cand = { fg = "#b59790" }
rest = { fg = "#0c0b0c" }
desc = { fg = "#FAFCFB" }
separator = " ▶ "
separator_style = { fg = "#FAFCFB" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#FAFCFB" }
run = { fg = "#FAFCFB" }
footer = { fg = "#0c0b0c", bg = "#e2dddc" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#3c3b3c" }
title_warn = { fg = "#b59790" }
title_error = { fg = "#87a9b0" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#3c3b3c" },

    # Media
    { mime = "{audio,video}/*", fg = "#b59790" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#e2dddc" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#FAFCFB" },

    # Special files
    { name = "*", is = "orphan", bg = "#87a9b0" },
    { name = "*", is = "exec", fg = "#e2dddc" },

    # Fallback
    { name = "*", fg = "#FAFCFB" },
    { name = "*/", fg = "#b59790" },
]

# : ]]]
