[skin]
default = "#c5c9c5 #181616 / #c5c9c5 #313030"
tree = "#4b4b4a None / #313030 None"
parent = "#8ba4b0 None / #7f817e None"
file = "#c5c9c5 None / #8ba4b0 None"
directory = "#8ba4b0 None Bold / #8ba4b0 None Bold"
exe = "#8ba4b0 None Bold"
link = "#8ba4b0 None Italic"
pruning = "#4b4b4a None Italic"
perm__ = "#313030 None"
perm_r = "#8ba4b0 None"
perm_w = "#8ba4b0 None"
perm_x = "#8ba4b0 None"
owner = "#7f817e None"
group = "#4b4b4a None"
count = "#8ba4b0 #181616"
dates = "#4b4b4a None"
sparse = "#8ba4b0 None"
content_extract = "#7f817e None Italic"
content_match = "#c5c9c5 None Bold"
device_id_major = "#8ba4b0 None"
device_id_sep = "#4b4b4a None"
device_id_minor = "#8ba4b0 None"
git_branch = "#c5c9c5 None Bold"
git_insertions = "#8ba4b0 None"
git_deletions = "#8ba4b0 None"
git_status_current = "#313030 None"
git_status_modified = "#8ba4b0 None"
git_status_new = "#c5c9c5 None Bold"
git_status_ignored = "#313030 None"
git_status_conflicted = "#8ba4b0 None Bold"
git_status_other = "#8ba4b0 None"
selected_line = "None #313030 / None #4b4b4a"
char_match = "#c5c9c5 None Bold"
file_error = "#c4746e None Bold"
flag_label = "#7f817e None"
flag_value = "#c5c9c5 None Bold"
input = "#c5c9c5 None / #c5c9c5 #313030"
status_error = "#c5c9c5 #c4746e"
status_job = "#c5c9c5 #313030"
status_normal = "#c5c9c5 #181616 / #C8C093 #313030"
status_italic = "#8ba4b0 #181616 Italic / #C8C093 #313030"
status_bold = "#8ba4b0 #181616 Bold / #C8C093 #313030"
status_code = "#c5c9c5 #181616 / #C8C093 #313030"
status_ellipsis = "#7f817e #181616 / #C8C093 #313030"
purpose_normal = "#c5c9c5 #313030"
purpose_italic = "#8ba4b0 #313030 Italic"
purpose_bold = "#8ba4b0 #313030 Bold"
purpose_ellipsis = "#7f817e #313030"
scrollbar_track = "#181616 None / #181616 None"
scrollbar_thumb = "#4b4b4a None / #313030 None"
help_paragraph = "#c5c9c5 None"
help_bold = "#8ba4b0 None Bold"
help_italic = "#8ba4b0 None Italic"
help_code = "#c5c9c5 #313030"
help_headers = "#8ba4b0 None Bold"
help_table_border = "#4b4b4a None"
preview_title = "#c5c9c5 None Bold / #8ba4b0 None"
preview = "#c5c9c5 #181616 / #8ba4b0 #313030"
preview_separator = "#4b4b4a None / #313030 None"
preview_line_number = "#4b4b4a #181616"
preview_match = "None #4b4b4a"
hex_null = "#313030 None"
hex_ascii_graphic = "#c5c9c5 None"
hex_ascii_whitespace = "#8ba4b0 None"
hex_ascii_other = "#8ba4b0 None"
hex_non_ascii = "#8ba4b0 None"
staging_area_title = "#c5c9c5 None Bold / #8ba4b0 None"
mode_command_mark = "#C8C093 #8ba4b0 Bold"
good_to_bad_0 = "#8a9a7b"
good_to_bad_1 = "#8a9a7b"
good_to_bad_2 = "#8a9a7b"
good_to_bad_3 = "#7f817e"
good_to_bad_4 = "#7f817e"
good_to_bad_5 = "#4b4b4a"
good_to_bad_6 = "#c4b28a"
good_to_bad_7 = "#c4b28a"
good_to_bad_8 = "#c4746e"
good_to_bad_9 = "#c4746e"
