$background = rgb(181616)
$foreground = rgb(c5c9c5)
$accent     = rgb(8ba4b0)
$bg_subtle  = rgb(313030)
$bg_muted   = rgb(4b4b4a)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
