[palettes.kanagawa-dragon]
bg               = '#181616'
bg_subtle        = '#313030'
bg_muted         = '#4b4b4a'
fg               = '#c5c9c5'
fg_dim           = '#7f817e'
sel_bg           = '#2D4F67'
sel_fg           = '#C8C093'
error            = '#c4746e'
accent           = '#8ba4b0'
fg_on_accent     = '#c5c9c5'
success          = '#8a9a7b'
warning          = '#c4b28a'
cursor           = '#C8C093'
