[palettes.kanagawa-dragon]
base             = '#181616'
crust            = '#4b4b4a'
on_sig1          = '#181616'
on_sig2          = '#c5c9c5'
on_sigbg         = '#c5c9c5'
red              = '#c4746e'
sig1             = '#8ba4b0'
sig2             = '#a292a3'
sig_bg           = '#181616'
sig_surface_high = '#313030'
text             = '#c5c9c5'
