[mgr]
cwd = { fg = "#c5c9c5" }
find_keyword = { fg = "#c4746e", bold = true, italic = true, underline = true }
find_position = { fg = "#c4746e", bold = true, italic = true }
marker_copied = { fg = "#a292a3", bg = "#a292a3" }
marker_cut = { fg = "#7f817e", bg = "#7f817e" }
marker_marked = { fg = "#8ba4b0", bg = "#8ba4b0" }
marker_selected = { fg = "#8a9a7b", bg = "#8a9a7b" }
count_copied = { fg = "#181616", bg = "#7f817e" }
count_cut = { fg = "#181616", bg = "#7f817e" }
count_selected = { fg = "#181616", bg = "#8a9a7b" }
border_symbol = " "
border_style = { fg = "#8ba4b0" }

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }
perm_type = { fg = "#8ba4b0" }
perm_read = { fg = "#c5c9c5" }
perm_write = { fg = "#8a9a7b" }
perm_exec = { fg = "#a292a3" }
perm_sep = { fg = "#7f817e" }
progress_label = { bold = true }
progress_normal = { fg = "#8ba4b0", bg = "#313030" }
progress_error = { fg = "#a292a3", bg = "#313030" }

[mode]
normal_main = { bg = "#8ba4b0", fg = "#181616", bold = true }
normal_alt  = { bg = "#313030", fg = "#c5c9c5" }
select_main = { bg = "#7f817e", fg = "#181616", bold = true }
select_alt  = { bg = "#313030", fg = "#c5c9c5" }
unset_main = { bg = "#8a9a7b", fg = "#181616", bold = true }
unset_alt  = { bg = "#313030", fg = "#c5c9c5" }

[select]
border = { fg = "#8ba4b0" }
active = { fg = "#8a9a7b", bold = true }

[input]
border = { fg = "#8ba4b0" }
value = { fg = "#c5c9c5" }

[tabs]
active = { fg = "#8ba4b0", bold = true, bg = "#181616" }
inactive = { fg = "#7f817e", bg = "#181616" }
sep_inner = { open = "[", close = "]" }

[cmp]
border = { fg = "#8ba4b0", bg = "#313030" }

[tasks]
border = { fg = "#8ba4b0" }
title = {}
hovered = { fg = "#7f817e", underline = true }

[which]
cols = 3
mask = { bg = "#313030" }
cand = { fg = "#8ba4b0" }
rest = { fg = "#181616" }
desc = { fg = "#c5c9c5" }
separator = " ▶ "
separator_style = { fg = "#c5c9c5" }

[help]
on = { fg = "#c5c9c5" }
run = { fg = "#c5c9c5" }
footer = { fg = "#181616", bg = "#7f817e" }

[notify]
title_info = { fg = "#8a9a7b" }
title_warn = { fg = "#8ba4b0" }
title_error = { fg = "#a292a3" }

[filetype]
rules = [
    { mime = "image/*", fg = "#8a9a7b" },
    { mime = "{audio,video}/*", fg = "#8ba4b0" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#7f817e" },
    { mime = "application/{pdf,doc,rtf}", fg = "#c5c9c5" },
    { url = "*", is = "orphan", bg = "#a292a3" },
    { url = "*", is = "exec", fg = "#7f817e" },
    { url = "*", fg = "#c5c9c5" },
    { url = "*/", fg = "#8ba4b0" },
]
