[skin]
default = "#cacccc #101315 / #cacccc #2b2e30"
tree = "#474a4b None / #2b2e30 None"
parent = "#798186 None / #7f8282 None"
file = "#cacccc None / #798186 None"
directory = "#798186 None Bold / #798186 None Bold"
exe = "#798186 None Bold"
link = "#798186 None Italic"
pruning = "#474a4b None Italic"
perm__ = "#2b2e30 None"
perm_r = "#798186 None"
perm_w = "#798186 None"
perm_x = "#798186 None"
owner = "#7f8282 None"
group = "#474a4b None"
count = "#798186 #101315"
dates = "#474a4b None"
sparse = "#798186 None"
content_extract = "#7f8282 None Italic"
content_match = "#cacccc None Bold"
device_id_major = "#798186 None"
device_id_sep = "#474a4b None"
device_id_minor = "#798186 None"
git_branch = "#cacccc None Bold"
git_insertions = "#798186 None"
git_deletions = "#798186 None"
git_status_current = "#2b2e30 None"
git_status_modified = "#798186 None"
git_status_new = "#cacccc None Bold"
git_status_ignored = "#2b2e30 None"
git_status_conflicted = "#798186 None Bold"
git_status_other = "#798186 None"
selected_line = "None #2b2e30 / None #474a4b"
char_match = "#cacccc None Bold"
file_error = "#565d60 None Bold"
flag_label = "#7f8282 None"
flag_value = "#cacccc None Bold"
input = "#cacccc None / #cacccc #2b2e30"
status_error = "#cacccc #565d60"
status_job = "#cacccc #2b2e30"
status_normal = "#cacccc #101315 / #101315 #2b2e30"
status_italic = "#798186 #101315 Italic / #101315 #2b2e30"
status_bold = "#798186 #101315 Bold / #101315 #2b2e30"
status_code = "#cacccc #101315 / #101315 #2b2e30"
status_ellipsis = "#7f8282 #101315 / #101315 #2b2e30"
purpose_normal = "#cacccc #2b2e30"
purpose_italic = "#798186 #2b2e30 Italic"
purpose_bold = "#798186 #2b2e30 Bold"
purpose_ellipsis = "#7f8282 #2b2e30"
scrollbar_track = "#101315 None / #101315 None"
scrollbar_thumb = "#474a4b None / #2b2e30 None"
help_paragraph = "#cacccc None"
help_bold = "#798186 None Bold"
help_italic = "#798186 None Italic"
help_code = "#cacccc #2b2e30"
help_headers = "#798186 None Bold"
help_table_border = "#474a4b None"
preview_title = "#cacccc None Bold / #798186 None"
preview = "#cacccc #101315 / #798186 #2b2e30"
preview_separator = "#474a4b None / #2b2e30 None"
preview_line_number = "#474a4b #101315"
preview_match = "None #474a4b"
hex_null = "#2b2e30 None"
hex_ascii_graphic = "#cacccc None"
hex_ascii_whitespace = "#798186 None"
hex_ascii_other = "#798186 None"
hex_non_ascii = "#798186 None"
staging_area_title = "#cacccc None Bold / #798186 None"
mode_command_mark = "#101315 #798186 Bold"
good_to_bad_0 = "#9fa5a9"
good_to_bad_1 = "#9fa5a9"
good_to_bad_2 = "#9fa5a9"
good_to_bad_3 = "#7f8282"
good_to_bad_4 = "#7f8282"
good_to_bad_5 = "#474a4b"
good_to_bad_6 = "#d9dbdc"
good_to_bad_7 = "#d9dbdc"
good_to_bad_8 = "#565d60"
good_to_bad_9 = "#565d60"
