$background = rgb(101315)
$foreground = rgb(cacccc)
$accent     = rgb(798186)
$bg_subtle  = rgb(2b2e30)
$bg_muted   = rgb(474a4b)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
