# ---------------------------------
# Kitty Theme
# ---------------------------------

# Primary colors
foreground              #cacccc
background              #101315

# Cursor
cursor                  #cacccc
cursor_text_color       #101315

# Selection
selection_foreground    #101315
selection_background    #798186

# Normal colors
color0                  #101315
color1                  #565d60
color2                  #9fa5a9
color3                  #d9dbdc
color4                  #798186
color5                  #aeaeae
color6                  #707070
color7                  #cbc2be

# Bright colors
color8                  #4b4e55
color9                  #de6145
color10                 #343d41
color11                 #c9c2b4
color12                 #5d6367
color13                 #9a9a9a
color14                 #707070
color15                 #a5aeb4

# UI accents
url_color               #798186

# Tabs
active_tab_foreground   #101315
active_tab_background   #798186

inactive_tab_foreground #cbc2be
inactive_tab_background #4b4e55

# Borders
active_border_color     #a8adb0
inactive_border_color   #4b4e55

# Optional transparency
background_opacity      0.90
