[palettes.solitude]
bg               = '#101315'
bg_subtle        = '#2b2e30'
bg_muted         = '#474a4b'
fg               = '#cacccc'
fg_dim           = '#7f8282'
sel_bg           = '#798186'
sel_fg           = '#101315'
error            = '#565d60'
accent           = '#798186'
fg_on_accent     = '#cacccc'
success          = '#9fa5a9'
warning          = '#d9dbdc'
cursor           = '#cacccc'
