# : Manager [[[

[mgr]
cwd = { fg = "#cacccc" }

# Find
find_keyword = { fg = "#565d60", bold = true, italic = true, underline = true }
find_position = { fg = "#565d60", bold = true, italic = true }

# Marker
marker_copied = { fg = "#798186", bg = "#798186" }
marker_cut = { fg = "#a5aeb4", bg = "#a5aeb4" }
marker_marked = { fg = "#de6145", bg = "#de6145" }
marker_selected = { fg = "#6f7177", bg = "#6f7177" }

# Count
count_copied = { fg = "#101315", bg = "#a5aeb4" }
count_cut = { fg = "#101315", bg = "#a5aeb4" }
count_selected = { fg = "#101315", bg = "#6f7177" }

# Border
border_symbol = " "
border_style = { fg = "#de6145" }

# : ]]]


# : Status [[[

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }

# Permissions
perm_type = { fg = "#de6145" }
perm_read = { fg = "#cacccc" }
perm_write = { fg = "#6f7177" }
perm_exec = { fg = "#798186" }
perm_sep = { fg = "#a5aeb4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#de6145", bg = "#4b4e55" }
progress_error = { fg = "#798186", bg = "#4b4e55" }

[mode]
normal_main = { bg = "#de6145", fg = "#101315", bold = true }
normal_alt  = { bg = "#4b4e55", fg = "#cacccc" }

select_main = { bg = "#a5aeb4", fg = "#101315", bold = true }
select_alt  = { bg = "#4b4e55", fg = "#cacccc" }

unset_main = { bg = "#6f7177", fg = "#101315", bold = true }
unset_alt  = { bg = "#4b4e55", fg = "#cacccc" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#de6145" }
active = { fg = "#6f7177", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#de6145" }
value = { fg = "#cacccc" }

# : ]]]


# : Tabs [[[

[tabs]
active = { fg = "#de6145", bold = true, bg = "#101315" }
inactive = { fg = "#a5aeb4", bg = "#101315" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#de6145", bg = "#4b4e55" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#de6145" }
title = {}
hovered = { fg = "#a5aeb4", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#4b4e55" }
cand = { fg = "#de6145" }
rest = { fg = "#101315" }
desc = { fg = "#cacccc" }
separator = " ▶ "
separator_style = { fg = "#cacccc" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#cacccc" }
run = { fg = "#cacccc" }
footer = { fg = "#101315", bg = "#a5aeb4" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#6f7177" }
title_warn = { fg = "#de6145" }
title_error = { fg = "#798186" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    { mime = "image/*", fg = "#6f7177" },
    { mime = "{audio,video}/*", fg = "#de6145" },

    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#a5aeb4" },

    { mime = "application/{pdf,doc,rtf}", fg = "#cacccc" },

    { url = "*", is = "orphan", bg = "#798186" },
    { url = "*", is = "exec", fg = "#a5aeb4" },

    { url = "*", fg = "#cacccc" },
    { url = "*/", fg = "#de6145" },
]

# : ]]]
