[mgr]
cwd = { fg = "#cacccc" }
find_keyword = { fg = "#565d60", bold = true, italic = true, underline = true }
find_position = { fg = "#565d60", bold = true, italic = true }
marker_copied = { fg = "#aeaeae", bg = "#aeaeae" }
marker_cut = { fg = "#7f8282", bg = "#7f8282" }
marker_marked = { fg = "#798186", bg = "#798186" }
marker_selected = { fg = "#9fa5a9", bg = "#9fa5a9" }
count_copied = { fg = "#101315", bg = "#7f8282" }
count_cut = { fg = "#101315", bg = "#7f8282" }
count_selected = { fg = "#101315", bg = "#9fa5a9" }
border_symbol = " "
border_style = { fg = "#798186" }

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }
perm_type = { fg = "#798186" }
perm_read = { fg = "#cacccc" }
perm_write = { fg = "#9fa5a9" }
perm_exec = { fg = "#aeaeae" }
perm_sep = { fg = "#7f8282" }
progress_label = { bold = true }
progress_normal = { fg = "#798186", bg = "#2b2e30" }
progress_error = { fg = "#aeaeae", bg = "#2b2e30" }

[mode]
normal_main = { bg = "#798186", fg = "#101315", bold = true }
normal_alt  = { bg = "#2b2e30", fg = "#cacccc" }
select_main = { bg = "#7f8282", fg = "#101315", bold = true }
select_alt  = { bg = "#2b2e30", fg = "#cacccc" }
unset_main = { bg = "#9fa5a9", fg = "#101315", bold = true }
unset_alt  = { bg = "#2b2e30", fg = "#cacccc" }

[select]
border = { fg = "#798186" }
active = { fg = "#9fa5a9", bold = true }

[input]
border = { fg = "#798186" }
value = { fg = "#cacccc" }

[tabs]
active = { fg = "#798186", bold = true, bg = "#101315" }
inactive = { fg = "#7f8282", bg = "#101315" }
sep_inner = { open = "[", close = "]" }

[cmp]
border = { fg = "#798186", bg = "#2b2e30" }

[tasks]
border = { fg = "#798186" }
title = {}
hovered = { fg = "#7f8282", underline = true }

[which]
cols = 3
mask = { bg = "#2b2e30" }
cand = { fg = "#798186" }
rest = { fg = "#101315" }
desc = { fg = "#cacccc" }
separator = " ▶ "
separator_style = { fg = "#cacccc" }

[help]
on = { fg = "#cacccc" }
run = { fg = "#cacccc" }
footer = { fg = "#101315", bg = "#7f8282" }

[notify]
title_info = { fg = "#9fa5a9" }
title_warn = { fg = "#798186" }
title_error = { fg = "#aeaeae" }

[filetype]
rules = [
    { mime = "image/*", fg = "#9fa5a9" },
    { mime = "{audio,video}/*", fg = "#798186" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#7f8282" },
    { mime = "application/{pdf,doc,rtf}", fg = "#cacccc" },
    { url = "*", is = "orphan", bg = "#aeaeae" },
    { url = "*", is = "exec", fg = "#7f8282" },
    { url = "*", fg = "#cacccc" },
    { url = "*/", fg = "#798186" },
]
