[skin]
default = "#C1C497 #111C18 / #C1C497 #2b352b"
tree = "#454e3e None / #2b352b None"
parent = "#509475 None / #7a8064 None"
file = "#C1C497 None / #509475 None"
directory = "#509475 None Bold / #509475 None Bold"
exe = "#509475 None Bold"
link = "#509475 None Italic"
pruning = "#454e3e None Italic"
perm__ = "#2b352b None"
perm_r = "#509475 None"
perm_w = "#509475 None"
perm_x = "#509475 None"
owner = "#7a8064 None"
group = "#454e3e None"
count = "#509475 #111C18"
dates = "#454e3e None"
sparse = "#509475 None"
content_extract = "#7a8064 None Italic"
content_match = "#C1C497 None Bold"
device_id_major = "#509475 None"
device_id_sep = "#454e3e None"
device_id_minor = "#509475 None"
git_branch = "#C1C497 None Bold"
git_insertions = "#509475 None"
git_deletions = "#509475 None"
git_status_current = "#2b352b None"
git_status_modified = "#509475 None"
git_status_new = "#C1C497 None Bold"
git_status_ignored = "#2b352b None"
git_status_conflicted = "#509475 None Bold"
git_status_other = "#509475 None"
selected_line = "None #2b352b / None #454e3e"
char_match = "#C1C497 None Bold"
file_error = "#FF5345 None Bold"
flag_label = "#7a8064 None"
flag_value = "#C1C497 None Bold"
input = "#C1C497 None / #C1C497 #2b352b"
status_error = "#C1C497 #FF5345"
status_job = "#C1C497 #2b352b"
status_normal = "#C1C497 #111C18 / #111C18 #2b352b"
status_italic = "#509475 #111C18 Italic / #111C18 #2b352b"
status_bold = "#509475 #111C18 Bold / #111C18 #2b352b"
status_code = "#C1C497 #111C18 / #111C18 #2b352b"
status_ellipsis = "#7a8064 #111C18 / #111C18 #2b352b"
purpose_normal = "#C1C497 #2b352b"
purpose_italic = "#509475 #2b352b Italic"
purpose_bold = "#509475 #2b352b Bold"
purpose_ellipsis = "#7a8064 #2b352b"
scrollbar_track = "#111C18 None / #111C18 None"
scrollbar_thumb = "#454e3e None / #2b352b None"
help_paragraph = "#C1C497 None"
help_bold = "#509475 None Bold"
help_italic = "#509475 None Italic"
help_code = "#C1C497 #2b352b"
help_headers = "#509475 None Bold"
help_table_border = "#454e3e None"
preview_title = "#C1C497 None Bold / #509475 None"
preview = "#C1C497 #111C18 / #509475 #2b352b"
preview_separator = "#454e3e None / #2b352b None"
preview_line_number = "#454e3e #111C18"
preview_match = "None #454e3e"
hex_null = "#2b352b None"
hex_ascii_graphic = "#C1C497 None"
hex_ascii_whitespace = "#509475 None"
hex_ascii_other = "#509475 None"
hex_non_ascii = "#509475 None"
staging_area_title = "#C1C497 None Bold / #509475 None"
mode_command_mark = "#111C18 #509475 Bold"
good_to_bad_0 = "#549E6A"
good_to_bad_1 = "#549E6A"
good_to_bad_2 = "#549E6A"
good_to_bad_3 = "#7a8064"
good_to_bad_4 = "#7a8064"
good_to_bad_5 = "#454e3e"
good_to_bad_6 = "#459451"
good_to_bad_7 = "#459451"
good_to_bad_8 = "#FF5345"
good_to_bad_9 = "#FF5345"
