$background = rgb(111C18)
$foreground = rgb(C1C497)
$accent     = rgb(509475)
$bg_subtle  = rgb(2b352b)
$bg_muted   = rgb(454e3e)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
