[palettes.osaka]
bg               = '#111C18'
bg_subtle        = '#2b352b'
bg_muted         = '#454e3e'
fg               = '#C1C497'
fg_dim           = '#7a8064'
sel_bg           = '#C1C497'
sel_fg           = '#111C18'
error            = '#FF5345'
accent           = '#509475'
fg_on_accent     = '#C1C497'
success          = '#549E6A'
warning          = '#459451'
cursor           = '#D7C995'
