[palettes.osaka]
base             = '#111C18'
crust            = '#454e3e'
on_sig1          = '#111C18'
on_sig2          = '#C1C497'
on_sigbg         = '#C1C497'
red              = '#FF5345'
sig1             = '#509475'
sig2             = '#D2689C'
sig_bg           = '#111C18'
sig_surface_high = '#2b352b'
text             = '#C1C497'
