# : Manager [[[

[mgr]
cwd = { fg = "#C1C497" }

# Find
find_keyword = { fg = "#FF5345", bold = true, italic = true, underline = true }
find_position = { fg = "#FF5345", bold = true, italic = true }

# Marker
marker_copied = { fg = "#509475", bg = "#509475" }
marker_cut = { fg = "#9EEBB3", bg = "#9EEBB3" }
marker_marked = { fg = "#549E6A", bg = "#549E6A" }
marker_selected = { fg = "#75867b", bg = "#75867b" }

# Count
count_copied = { fg = "#111C18", bg = "#9EEBB3" }
count_cut = { fg = "#111C18", bg = "#9EEBB3" }
count_selected = { fg = "#23372B", bg = "#75867b" }

# Border
border_symbol = " "
border_style = { fg = "#549E6A" }

# : ]]]


# : Status [[[

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }

# Permissions
perm_type = { fg = "#549E6A" }
perm_read = { fg = "#C1C497" }
perm_write = { fg = "#75867b" }
perm_exec = { fg = "#509475" }
perm_sep = { fg = "#9EEBB3" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#549E6A", bg = "#53685B" }
progress_error = { fg = "#509475", bg = "#53685B" }

[mode]
normal_main = { bg = "#549E6A", fg = "#23372B", bold = true }
normal_alt  = { bg = "#53685B", fg = "#C1C497" }

select_main = { bg = "#9EEBB3", fg = "#23372B", bold = true }
select_alt  = { bg = "#53685B", fg = "#C1C497" }

unset_main = { bg = "#75867b", fg = "#23372B", bold = true }
unset_alt  = { bg = "#53685B", fg = "#C1C497" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#549E6A" }
active = { fg = "#75867b", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#549E6A" }
value = { fg = "#C1C497" }

# : ]]]


# : Tabs [[[

[tabs]
active = { fg = "#549E6A", bold = true, bg = "#111C18" }
inactive = { fg = "#9EEBB3", bg = "#111C18" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#549E6A", bg = "#53685B" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#549E6A" }
title = {}
hovered = { fg = "#9EEBB3", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#53685B" }
cand = { fg = "#549E6A" }
rest = { fg = "#23372B" }
desc = { fg = "#C1C497" }
separator = " ▶ "
separator_style = { fg = "#C1C497" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#C1C497" }
run = { fg = "#C1C497" }
footer = { fg = "#23372B", bg = "#9EEBB3" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#75867b" }
title_warn = { fg = "#549E6A" }
title_error = { fg = "#509475" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    { mime = "image/*", fg = "#75867b" },
    { mime = "{audio,video}/*", fg = "#549E6A" },

    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#9EEBB3" },

    { mime = "application/{pdf,doc,rtf}", fg = "#C1C497" },

    { url = "*", is = "orphan", bg = "#509475" },
    { url = "*", is = "exec", fg = "#9EEBB3" },

    { url = "*", fg = "#C1C497" },
    { url = "*/", fg = "#549E6A" },
]

# : ]]]
