[skin]
default = "#cdcdcd #141415 / #cdcdcd #2f2f30"
tree = "#4b4b4c None / #2f2f30 None"
parent = "#6e94b2 None / #838383 None"
file = "#cdcdcd None / #6e94b2 None"
directory = "#6e94b2 None Bold / #6e94b2 None Bold"
exe = "#6e94b2 None Bold"
link = "#6e94b2 None Italic"
pruning = "#4b4b4c None Italic"
perm__ = "#2f2f30 None"
perm_r = "#6e94b2 None"
perm_w = "#6e94b2 None"
perm_x = "#6e94b2 None"
owner = "#838383 None"
group = "#4b4b4c None"
count = "#6e94b2 #141415"
dates = "#4b4b4c None"
sparse = "#6e94b2 None"
content_extract = "#838383 None Italic"
content_match = "#cdcdcd None Bold"
device_id_major = "#6e94b2 None"
device_id_sep = "#4b4b4c None"
device_id_minor = "#6e94b2 None"
git_branch = "#cdcdcd None Bold"
git_insertions = "#6e94b2 None"
git_deletions = "#6e94b2 None"
git_status_current = "#2f2f30 None"
git_status_modified = "#6e94b2 None"
git_status_new = "#cdcdcd None Bold"
git_status_ignored = "#2f2f30 None"
git_status_conflicted = "#6e94b2 None Bold"
git_status_other = "#6e94b2 None"
selected_line = "None #2f2f30 / None #4b4b4c"
char_match = "#cdcdcd None Bold"
file_error = "#d8647e None Bold"
flag_label = "#838383 None"
flag_value = "#cdcdcd None Bold"
input = "#cdcdcd None / #cdcdcd #2f2f30"
status_error = "#cdcdcd #d8647e"
status_job = "#cdcdcd #2f2f30"
status_normal = "#cdcdcd #141415 / #141415 #2f2f30"
status_italic = "#6e94b2 #141415 Italic / #141415 #2f2f30"
status_bold = "#6e94b2 #141415 Bold / #141415 #2f2f30"
status_code = "#cdcdcd #141415 / #141415 #2f2f30"
status_ellipsis = "#838383 #141415 / #141415 #2f2f30"
purpose_normal = "#cdcdcd #2f2f30"
purpose_italic = "#6e94b2 #2f2f30 Italic"
purpose_bold = "#6e94b2 #2f2f30 Bold"
purpose_ellipsis = "#838383 #2f2f30"
scrollbar_track = "#141415 None / #141415 None"
scrollbar_thumb = "#4b4b4c None / #2f2f30 None"
help_paragraph = "#cdcdcd None"
help_bold = "#6e94b2 None Bold"
help_italic = "#6e94b2 None Italic"
help_code = "#cdcdcd #2f2f30"
help_headers = "#6e94b2 None Bold"
help_table_border = "#4b4b4c None"
preview_title = "#cdcdcd None Bold / #6e94b2 None"
preview = "#cdcdcd #141415 / #6e94b2 #2f2f30"
preview_separator = "#4b4b4c None / #2f2f30 None"
preview_line_number = "#4b4b4c #141415"
preview_match = "None #4b4b4c"
hex_null = "#2f2f30 None"
hex_ascii_graphic = "#cdcdcd None"
hex_ascii_whitespace = "#6e94b2 None"
hex_ascii_other = "#6e94b2 None"
hex_non_ascii = "#6e94b2 None"
staging_area_title = "#cdcdcd None Bold / #6e94b2 None"
mode_command_mark = "#141415 #6e94b2 Bold"
good_to_bad_0 = "#7fa563"
good_to_bad_1 = "#7fa563"
good_to_bad_2 = "#7fa563"
good_to_bad_3 = "#838383"
good_to_bad_4 = "#838383"
good_to_bad_5 = "#4b4b4c"
good_to_bad_6 = "#f3be7c"
good_to_bad_7 = "#f3be7c"
good_to_bad_8 = "#d8647e"
good_to_bad_9 = "#d8647e"
