$background = rgb(141415)
$foreground = rgb(cdcdcd)
$accent     = rgb(6e94b2)
$bg_subtle  = rgb(2f2f30)
$bg_muted   = rgb(4b4b4c)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
