[palettes.vague]
bg               = '#141415'
bg_subtle        = '#2f2f30'
bg_muted         = '#4b4b4c'
fg               = '#cdcdcd'
fg_dim           = '#838383'
sel_bg           = '#6e94b2'
sel_fg           = '#141415'
error            = '#d8647e'
accent           = '#6e94b2'
fg_on_accent     = '#cdcdcd'
success          = '#7fa563'
warning          = '#f3be7c'
cursor           = '#cdcdcd'
