[palettes.vague]
base             = '#141415'
crust            = '#4b4b4c'
on_sig1          = '#141415'
on_sig2          = '#cdcdcd'
on_sigbg         = '#cdcdcd'
red              = '#d8647e'
sig1             = '#6e94b2'
sig2             = '#bb9dbd'
sig_bg           = '#141415'
sig_surface_high = '#2f2f30'
text             = '#cdcdcd'
