# : Manager [[[

[mgr]
cwd = { fg = "#cdcdcd" }

# Find
find_keyword = { fg = "#d8647e", bold = true, italic = true, underline = true }
find_position = { fg = "#d8647e", bold = true, italic = true }

# Marker
marker_copied = { fg = "#6e94b2", bg = "#6e94b2" }
marker_cut = { fg = "#cdcdcd", bg = "#cdcdcd" }
marker_marked = { fg = "#d8647e", bg = "#d8647e" }
marker_selected = { fg = "#49494f", bg = "#49494f" }

# Count
count_copied = { fg = "#141415", bg = "#cdcdcd" }
count_cut = { fg = "#141415", bg = "#cdcdcd" }
count_selected = { fg = "#1c1c24", bg = "#49494f" }

# Border
border_symbol = " "
border_style = { fg = "#d8647e" }

# : ]]]


# : Status [[[

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }

# Permissions
perm_type = { fg = "#d8647e" }
perm_read = { fg = "#cdcdcd" }
perm_write = { fg = "#49494f" }
perm_exec = { fg = "#6e94b2" }
perm_sep = { fg = "#cdcdcd" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#d8647e", bg = "#1c1c24" }
progress_error = { fg = "#6e94b2", bg = "#1c1c24" }

[mode]
normal_main = { bg = "#d8647e", fg = "#1c1c24", bold = true }
normal_alt  = { bg = "#1c1c24", fg = "#cdcdcd" }

select_main = { bg = "#cdcdcd", fg = "#1c1c24", bold = true }
select_alt  = { bg = "#1c1c24", fg = "#cdcdcd" }

unset_main = { bg = "#49494f", fg = "#1c1c24", bold = true }
unset_alt  = { bg = "#1c1c24", fg = "#cdcdcd" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#d8647e" }
active = { fg = "#49494f", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#d8647e" }
value = { fg = "#cdcdcd" }

# : ]]]


# : Tabs [[[

[tabs]
active = { fg = "#d8647e", bold = true, bg = "#141415" }
inactive = { fg = "#cdcdcd", bg = "#141415" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#d8647e", bg = "#606079" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#d8647e" }
title = {}
hovered = { fg = "#cdcdcd", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#1c1c24" }
cand = { fg = "#d8647e" }
rest = { fg = "#1c1c24" }
desc = { fg = "#cdcdcd" }
separator = " ▶ "
separator_style = { fg = "#cdcdcd" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#cdcdcd" }
run = { fg = "#cdcdcd" }
footer = { fg = "#1c1c24", bg = "#cdcdcd" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#49494f" }
title_warn = { fg = "#d8647e" }
title_error = { fg = "#6e94b2" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    { mime = "image/*", fg = "#49494f" },
    { mime = "{audio,video}/*", fg = "#d8647e" },

    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#cdcdcd" },

    { mime = "application/{pdf,doc,rtf}", fg = "#cdcdcd" },

    { url = "*", is = "orphan", bg = "#6e94b2" },
    { url = "*", is = "exec", fg = "#cdcdcd" },

    { url = "*", fg = "#cdcdcd" },
    { url = "*/", fg = "#d8647e" },
]

# : ]]]
