# : Manager [[[

[mgr]
cwd = { fg = "#cdcdcd" }

# Tab
tab_active = { fg = "#1c1c24", bg = "#d8647e", bold = true }
tab_inactive = { fg = "#cdcdcd", bg = "#606079" }
tab_width = 1

# Find
find_keyword = { fg = "#d8647e", bold = true, italic = true, underline = true }
find_position = { fg = "#d8647e", bold = true, italic = true }

# Marker
marker_copied = { fg = "#6e94b2", bg = "#6e94b2" }
marker_cut = { fg = "#cdcdcd", bg = "#cdcdcd" }
marker_marked = { fg = "#d8647e", bg = "#d8647e" }
marker_selected = { fg = "#49494f", bg = "#49494f" }

# Count
count_copied = { fg = "#141415", bg = "#cdcdcd" }
count_cut = { fg = "#141415", bg = "#cdcdcd" }
count_selected = { fg = "#1c1c24", bg = "#49494f" }

# Border
border_symbol = " "
border_style  = { fg = "#d8647e" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#606079", fg = "#d8647e" }

[mode]
# Mode
normal_main = { bg = "#d8647e", fg = "#1c1c24", bold = true }
normal_alt  = { bg = "#1c1c24", fg = "#cdcdcd" }

# Select mode
select_main = { bg = "#cdcdcd", fg = "#1c1c24", bold = true }
select_alt  = { bg = "#1c1c24", fg = "#cdcdcd" }

# Unset mode
unset_main = { bg = "#49494f", fg = "#1c1c24", bold = true }
unset_alt  = { bg = "#1c1c24", fg = "#cdcdcd" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#d8647e", bg = "#1c1c24" }
progress_error = { fg = "#6e94b2", bg = "#1c1c24" }

# Permissions
permissions_t = { fg = "#d8647e" }
permissions_w = { fg = "#49494f" }
permissions_x = { fg = "#6e94b2" }
permissions_r = { fg = "#cdcdcd" }
permissions_s = { fg = "#cdcdcd" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#d8647e" }
active = { fg = "#49494f", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#d8647e" }
value = { fg = "#cdcdcd" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#d8647e", bold = true, bg = "#141415" }
inactive = { fg = "#cdcdcd", bg = "#141415" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#d8647e", bg = "#606079" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#d8647e" }
title = {}
hovered = { fg = "#cdcdcd", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#1c1c24" }
cand = { fg = "#d8647e" }
rest = { fg = "#1c1c24" }
desc = { fg = "#cdcdcd" }
separator = " ▶ "
separator_style = { fg = "#cdcdcd" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#cdcdcd" }
run = { fg = "#cdcdcd" }
footer = { fg = "#1c1c24", bg = "#cdcdcd" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#49494f" }
title_warn = { fg = "#d8647e" }
title_error = { fg = "#6e94b2" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#49494f" },

    # Media
    { mime = "{audio,video}/*", fg = "#d8647e" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#cdcdcd" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#cdcdcd" },

    # Special files
    { name = "*", is = "orphan", bg = "#6e94b2" },
    { name = "*", is = "exec", fg = "#cdcdcd" },

    # Fallback
    { name = "*", fg = "#cdcdcd" },
    { name = "*/", fg = "#d8647e" },
]

# : ]]]
