[mgr]
cwd = { fg = "#cdcdcd" }
find_keyword = { fg = "#d8647e", bold = true, italic = true, underline = true }
find_position = { fg = "#d8647e", bold = true, italic = true }
marker_copied = { fg = "#bb9dbd", bg = "#bb9dbd" }
marker_cut = { fg = "#838383", bg = "#838383" }
marker_marked = { fg = "#6e94b2", bg = "#6e94b2" }
marker_selected = { fg = "#7fa563", bg = "#7fa563" }
count_copied = { fg = "#141415", bg = "#838383" }
count_cut = { fg = "#141415", bg = "#838383" }
count_selected = { fg = "#141415", bg = "#7fa563" }
border_symbol = " "
border_style = { fg = "#6e94b2" }

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }
perm_type = { fg = "#6e94b2" }
perm_read = { fg = "#cdcdcd" }
perm_write = { fg = "#7fa563" }
perm_exec = { fg = "#bb9dbd" }
perm_sep = { fg = "#838383" }
progress_label = { bold = true }
progress_normal = { fg = "#6e94b2", bg = "#2f2f30" }
progress_error = { fg = "#bb9dbd", bg = "#2f2f30" }

[mode]
normal_main = { bg = "#6e94b2", fg = "#141415", bold = true }
normal_alt  = { bg = "#2f2f30", fg = "#cdcdcd" }
select_main = { bg = "#838383", fg = "#141415", bold = true }
select_alt  = { bg = "#2f2f30", fg = "#cdcdcd" }
unset_main = { bg = "#7fa563", fg = "#141415", bold = true }
unset_alt  = { bg = "#2f2f30", fg = "#cdcdcd" }

[select]
border = { fg = "#6e94b2" }
active = { fg = "#7fa563", bold = true }

[input]
border = { fg = "#6e94b2" }
value = { fg = "#cdcdcd" }

[tabs]
active = { fg = "#6e94b2", bold = true, bg = "#141415" }
inactive = { fg = "#838383", bg = "#141415" }
sep_inner = { open = "[", close = "]" }

[cmp]
border = { fg = "#6e94b2", bg = "#2f2f30" }

[tasks]
border = { fg = "#6e94b2" }
title = {}
hovered = { fg = "#838383", underline = true }

[which]
cols = 3
mask = { bg = "#2f2f30" }
cand = { fg = "#6e94b2" }
rest = { fg = "#141415" }
desc = { fg = "#cdcdcd" }
separator = " ▶ "
separator_style = { fg = "#cdcdcd" }

[help]
on = { fg = "#cdcdcd" }
run = { fg = "#cdcdcd" }
footer = { fg = "#141415", bg = "#838383" }

[notify]
title_info = { fg = "#7fa563" }
title_warn = { fg = "#6e94b2" }
title_error = { fg = "#bb9dbd" }

[filetype]
rules = [
    { mime = "image/*", fg = "#7fa563" },
    { mime = "{audio,video}/*", fg = "#6e94b2" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#838383" },
    { mime = "application/{pdf,doc,rtf}", fg = "#cdcdcd" },
    { url = "*", is = "orphan", bg = "#bb9dbd" },
    { url = "*", is = "exec", fg = "#838383" },
    { url = "*", fg = "#cdcdcd" },
    { url = "*/", fg = "#6e94b2" },
]
