[mgr]
cwd = { fg = "#d0c8b6" }
find_keyword = { fg = "#c26a4a", bold = true, italic = true, underline = true }
find_position = { fg = "#c26a4a", bold = true, italic = true }
marker_copied = { fg = "#a08a9a", bg = "#a08a9a" }
marker_cut = { fg = "#878276", bg = "#878276" }
marker_marked = { fg = "#6f8fa3", bg = "#6f8fa3" }
marker_selected = { fg = "#8a9a7b", bg = "#8a9a7b" }
count_copied = { fg = "#1b1a17", bg = "#878276" }
count_cut = { fg = "#1b1a17", bg = "#878276" }
count_selected = { fg = "#1b1a17", bg = "#8a9a7b" }
border_symbol = " "
border_style = { fg = "#6f8fa3" }

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }
perm_type = { fg = "#6f8fa3" }
perm_read = { fg = "#d0c8b6" }
perm_write = { fg = "#8a9a7b" }
perm_exec = { fg = "#a08a9a" }
perm_sep = { fg = "#878276" }
progress_label = { bold = true }
progress_normal = { fg = "#6f8fa3", bg = "#36342e" }
progress_error = { fg = "#a08a9a", bg = "#36342e" }

[mode]
normal_main = { bg = "#6f8fa3", fg = "#1b1a17", bold = true }
normal_alt  = { bg = "#36342e", fg = "#d0c8b6" }
select_main = { bg = "#878276", fg = "#1b1a17", bold = true }
select_alt  = { bg = "#36342e", fg = "#d0c8b6" }
unset_main = { bg = "#8a9a7b", fg = "#1b1a17", bold = true }
unset_alt  = { bg = "#36342e", fg = "#d0c8b6" }

[select]
border = { fg = "#6f8fa3" }
active = { fg = "#8a9a7b", bold = true }

[input]
border = { fg = "#6f8fa3" }
value = { fg = "#d0c8b6" }

[tabs]
active = { fg = "#6f8fa3", bold = true, bg = "#1b1a17" }
inactive = { fg = "#878276", bg = "#1b1a17" }
sep_inner = { open = "[", close = "]" }

[cmp]
border = { fg = "#6f8fa3", bg = "#36342e" }

[tasks]
border = { fg = "#6f8fa3" }
title = {}
hovered = { fg = "#878276", underline = true }

[which]
cols = 3
mask = { bg = "#36342e" }
cand = { fg = "#6f8fa3" }
rest = { fg = "#1b1a17" }
desc = { fg = "#d0c8b6" }
separator = " ▶ "
separator_style = { fg = "#d0c8b6" }

[help]
on = { fg = "#d0c8b6" }
run = { fg = "#d0c8b6" }
footer = { fg = "#1b1a17", bg = "#878276" }

[notify]
title_info = { fg = "#8a9a7b" }
title_warn = { fg = "#6f8fa3" }
title_error = { fg = "#a08a9a" }

[filetype]
rules = [
    { mime = "image/*", fg = "#8a9a7b" },
    { mime = "{audio,video}/*", fg = "#6f8fa3" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#878276" },
    { mime = "application/{pdf,doc,rtf}", fg = "#d0c8b6" },
    { url = "*", is = "orphan", bg = "#a08a9a" },
    { url = "*", is = "exec", fg = "#878276" },
    { url = "*", fg = "#d0c8b6" },
    { url = "*/", fg = "#6f8fa3" },
]
