[skin]
default = "#f6dcac #05182e / #f6dcac #293540"
tree = "#4d5253 None / #293540 None"
parent = "#faa968 None / #958d79 None"
file = "#f6dcac None / #faa968 None"
directory = "#faa968 None Bold / #faa968 None Bold"
exe = "#faa968 None Bold"
link = "#faa968 None Italic"
pruning = "#4d5253 None Italic"
perm__ = "#293540 None"
perm_r = "#faa968 None"
perm_w = "#faa968 None"
perm_x = "#faa968 None"
owner = "#958d79 None"
group = "#4d5253 None"
count = "#faa968 #05182e"
dates = "#4d5253 None"
sparse = "#faa968 None"
content_extract = "#958d79 None Italic"
content_match = "#f6dcac None Bold"
device_id_major = "#faa968 None"
device_id_sep = "#4d5253 None"
device_id_minor = "#faa968 None"
git_branch = "#f6dcac None Bold"
git_insertions = "#faa968 None"
git_deletions = "#faa968 None"
git_status_current = "#293540 None"
git_status_modified = "#faa968 None"
git_status_new = "#f6dcac None Bold"
git_status_ignored = "#293540 None"
git_status_conflicted = "#faa968 None Bold"
git_status_other = "#faa968 None"
selected_line = "None #293540 / None #4d5253"
char_match = "#f6dcac None Bold"
file_error = "#f85525 None Bold"
flag_label = "#958d79 None"
flag_value = "#f6dcac None Bold"
input = "#f6dcac None / #f6dcac #293540"
status_error = "#f6dcac #f85525"
status_job = "#f6dcac #293540"
status_normal = "#f6dcac #05182e / #00172e #293540"
status_italic = "#faa968 #05182e Italic / #00172e #293540"
status_bold = "#faa968 #05182e Bold / #00172e #293540"
status_code = "#f6dcac #05182e / #00172e #293540"
status_ellipsis = "#958d79 #05182e / #00172e #293540"
purpose_normal = "#f6dcac #293540"
purpose_italic = "#faa968 #293540 Italic"
purpose_bold = "#faa968 #293540 Bold"
purpose_ellipsis = "#958d79 #293540"
scrollbar_track = "#05182e None / #05182e None"
scrollbar_thumb = "#4d5253 None / #293540 None"
help_paragraph = "#f6dcac None"
help_bold = "#faa968 None Bold"
help_italic = "#faa968 None Italic"
help_code = "#f6dcac #293540"
help_headers = "#faa968 None Bold"
help_table_border = "#4d5253 None"
preview_title = "#f6dcac None Bold / #faa968 None"
preview = "#f6dcac #05182e / #faa968 #293540"
preview_separator = "#4d5253 None / #293540 None"
preview_line_number = "#4d5253 #05182e"
preview_match = "None #4d5253"
hex_null = "#293540 None"
hex_ascii_graphic = "#f6dcac None"
hex_ascii_whitespace = "#faa968 None"
hex_ascii_other = "#faa968 None"
hex_non_ascii = "#faa968 None"
staging_area_title = "#f6dcac None Bold / #faa968 None"
mode_command_mark = "#00172e #faa968 Bold"
good_to_bad_0 = "#028391"
good_to_bad_1 = "#028391"
good_to_bad_2 = "#028391"
good_to_bad_3 = "#958d79"
good_to_bad_4 = "#958d79"
good_to_bad_5 = "#4d5253"
good_to_bad_6 = "#e97b3c"
good_to_bad_7 = "#e97b3c"
good_to_bad_8 = "#f85525"
good_to_bad_9 = "#f85525"
