$background = rgb(05182e)
$foreground = rgb(f6dcac)
$accent     = rgb(faa968)
$bg_subtle  = rgb(293540)
$bg_muted   = rgb(4d5253)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
