# ---------------------------------
# Kitty Theme
# ---------------------------------

# Primary colors
foreground              #f6dcac
background              #05182e

# Cursor
cursor                  #f6dcac
cursor_text_color       #00172e

# Selection
selection_foreground    #00172e
selection_background    #faa968

# Normal colors
color0                  #303442
color1                  #f85525
color2                  #028391
color3                  #e97b3c
color4                  #faa968
color5                  #3f8f8a
color6                  #8cbfb8
color7                  #a7c9c6

# Bright colors
color8                  #134e5a
color9                  #f85525
color10                 #028391
color11                 #e97b3c
color12                 #faa968
color13                 #3f8f8a
color14                 #8cbfb8
color15                 #f6dcac

# UI accents
url_color               #faa968

# Tabs
active_tab_foreground   #05182e
active_tab_background   #faa968

inactive_tab_foreground #a7c9c6
inactive_tab_background #303442

# Borders
active_border_color     #faa968
inactive_border_color   #134e5a

# Optional transparency
background_opacity      0.90
