[palettes.retro-82]
bg               = '#05182e'
bg_subtle        = '#293540'
bg_muted         = '#4d5253'
fg               = '#f6dcac'
fg_dim           = '#958d79'
sel_bg           = '#faa968'
sel_fg           = '#00172e'
error            = '#f85525'
accent           = '#faa968'
fg_on_accent     = '#f6dcac'
success          = '#028391'
warning          = '#e97b3c'
cursor           = '#f6dcac'
