[skin]
default = "#e0e0e0 #121212 / #e0e0e0 #303030"
tree = "#4f4f4f None / #303030 None"
parent = "#7ab0df None / #8d8d8d None"
file = "#e0e0e0 None / #7ab0df None"
directory = "#7ab0df None Bold / #7ab0df None Bold"
exe = "#7ab0df None Bold"
link = "#7ab0df None Italic"
pruning = "#4f4f4f None Italic"
perm__ = "#303030 None"
perm_r = "#7ab0df None"
perm_w = "#7ab0df None"
perm_x = "#7ab0df None"
owner = "#8d8d8d None"
group = "#4f4f4f None"
count = "#7ab0df #121212"
dates = "#4f4f4f None"
sparse = "#7ab0df None"
content_extract = "#8d8d8d None Italic"
content_match = "#e0e0e0 None Bold"
device_id_major = "#7ab0df None"
device_id_sep = "#4f4f4f None"
device_id_minor = "#7ab0df None"
git_branch = "#e0e0e0 None Bold"
git_insertions = "#7ab0df None"
git_deletions = "#7ab0df None"
git_status_current = "#303030 None"
git_status_modified = "#7ab0df None"
git_status_new = "#e0e0e0 None Bold"
git_status_ignored = "#303030 None"
git_status_conflicted = "#7ab0df None Bold"
git_status_other = "#7ab0df None"
selected_line = "None #303030 / None #4f4f4f"
char_match = "#e0e0e0 None Bold"
file_error = "#f87070 None Bold"
flag_label = "#8d8d8d None"
flag_value = "#e0e0e0 None Bold"
input = "#e0e0e0 None / #e0e0e0 #303030"
status_error = "#e0e0e0 #f87070"
status_job = "#e0e0e0 #303030"
status_normal = "#e0e0e0 #121212 / #121212 #303030"
status_italic = "#7ab0df #121212 Italic / #121212 #303030"
status_bold = "#7ab0df #121212 Bold / #121212 #303030"
status_code = "#e0e0e0 #121212 / #121212 #303030"
status_ellipsis = "#8d8d8d #121212 / #121212 #303030"
purpose_normal = "#e0e0e0 #303030"
purpose_italic = "#7ab0df #303030 Italic"
purpose_bold = "#7ab0df #303030 Bold"
purpose_ellipsis = "#8d8d8d #303030"
scrollbar_track = "#121212 None / #121212 None"
scrollbar_thumb = "#4f4f4f None / #303030 None"
help_paragraph = "#e0e0e0 None"
help_bold = "#7ab0df None Bold"
help_italic = "#7ab0df None Italic"
help_code = "#e0e0e0 #303030"
help_headers = "#7ab0df None Bold"
help_table_border = "#4f4f4f None"
preview_title = "#e0e0e0 None Bold / #7ab0df None"
preview = "#e0e0e0 #121212 / #7ab0df #303030"
preview_separator = "#4f4f4f None / #303030 None"
preview_line_number = "#4f4f4f #121212"
preview_match = "None #4f4f4f"
hex_null = "#303030 None"
hex_ascii_graphic = "#e0e0e0 None"
hex_ascii_whitespace = "#7ab0df None"
hex_ascii_other = "#7ab0df None"
hex_non_ascii = "#7ab0df None"
staging_area_title = "#e0e0e0 None Bold / #7ab0df None"
mode_command_mark = "#121212 #7ab0df Bold"
good_to_bad_0 = "#79dcaa"
good_to_bad_1 = "#79dcaa"
good_to_bad_2 = "#79dcaa"
good_to_bad_3 = "#8d8d8d"
good_to_bad_4 = "#8d8d8d"
good_to_bad_5 = "#4f4f4f"
good_to_bad_6 = "#ffe16b"
good_to_bad_7 = "#ffe16b"
good_to_bad_8 = "#f87070"
good_to_bad_9 = "#f87070"
