$background = rgb(121212)
$foreground = rgb(e0e0e0)
$accent     = rgb(7ab0df)
$bg_subtle  = rgb(303030)
$bg_muted   = rgb(4f4f4f)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
