background #121212
foreground #e0e0e0
selection_background #7ab0df
selection_foreground #121212
url_color #7ab0df
cursor #e0e0e0
active_tab_background #0d0d0d
active_tab_foreground #e0e0e0
inactive_tab_background #080808
inactive_tab_foreground #a0a0a0
color0 #080808
color1 #f87070
color2 #79dcaa
color3 #ffe16b
color4 #7ab0df
color5 #ae81ff
color6 #70c0ba
color7 #e0e0e0
color8 #4d4d4d
color9 #fb7373
color10 #79dcaa
color11 #ff8f40
color12 #5fb3b3
color13 #c397d8
color14 #70c0ba
color15 #c0c0c0
color16 #ffe16b
color17 #d0d0d0
