[palettes.matte-black]
bg               = '#121212'
bg_subtle        = '#303030'
bg_muted         = '#4f4f4f'
fg               = '#e0e0e0'
fg_dim           = '#8d8d8d'
sel_bg           = '#7ab0df'
sel_fg           = '#121212'
error            = '#f87070'
accent           = '#7ab0df'
fg_on_accent     = '#e0e0e0'
success          = '#79dcaa'
warning          = '#ffe16b'
cursor           = '#e0e0e0'
