[palettes.matte-black]
base             = '#121212'
crust            = '#4f4f4f'
on_sig1          = '#121212'
on_sig2          = '#e0e0e0'
on_sigbg         = '#e0e0e0'
red              = '#f87070'
sig1             = '#7ab0df'
sig2             = '#ae81ff'
sig_bg           = '#121212'
sig_surface_high = '#303030'
text             = '#e0e0e0'
