[mgr]
cwd = { fg = "#e0e0e0" }
find_keyword = { fg = "#f87070", bold = true, italic = true, underline = true }
find_position = { fg = "#f87070", bold = true, italic = true }
marker_copied = { fg = "#ae81ff", bg = "#ae81ff" }
marker_cut = { fg = "#8d8d8d", bg = "#8d8d8d" }
marker_marked = { fg = "#7ab0df", bg = "#7ab0df" }
marker_selected = { fg = "#79dcaa", bg = "#79dcaa" }
count_copied = { fg = "#121212", bg = "#8d8d8d" }
count_cut = { fg = "#121212", bg = "#8d8d8d" }
count_selected = { fg = "#121212", bg = "#79dcaa" }
border_symbol = " "
border_style = { fg = "#7ab0df" }

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }
perm_type = { fg = "#7ab0df" }
perm_read = { fg = "#e0e0e0" }
perm_write = { fg = "#79dcaa" }
perm_exec = { fg = "#ae81ff" }
perm_sep = { fg = "#8d8d8d" }
progress_label = { bold = true }
progress_normal = { fg = "#7ab0df", bg = "#303030" }
progress_error = { fg = "#ae81ff", bg = "#303030" }

[mode]
normal_main = { bg = "#7ab0df", fg = "#121212", bold = true }
normal_alt  = { bg = "#303030", fg = "#e0e0e0" }
select_main = { bg = "#8d8d8d", fg = "#121212", bold = true }
select_alt  = { bg = "#303030", fg = "#e0e0e0" }
unset_main = { bg = "#79dcaa", fg = "#121212", bold = true }
unset_alt  = { bg = "#303030", fg = "#e0e0e0" }

[select]
border = { fg = "#7ab0df" }
active = { fg = "#79dcaa", bold = true }

[input]
border = { fg = "#7ab0df" }
value = { fg = "#e0e0e0" }

[tabs]
active = { fg = "#7ab0df", bold = true, bg = "#121212" }
inactive = { fg = "#8d8d8d", bg = "#121212" }
sep_inner = { open = "[", close = "]" }

[cmp]
border = { fg = "#7ab0df", bg = "#303030" }

[tasks]
border = { fg = "#7ab0df" }
title = {}
hovered = { fg = "#8d8d8d", underline = true }

[which]
cols = 3
mask = { bg = "#303030" }
cand = { fg = "#7ab0df" }
rest = { fg = "#121212" }
desc = { fg = "#e0e0e0" }
separator = " ▶ "
separator_style = { fg = "#e0e0e0" }

[help]
on = { fg = "#e0e0e0" }
run = { fg = "#e0e0e0" }
footer = { fg = "#121212", bg = "#8d8d8d" }

[notify]
title_info = { fg = "#79dcaa" }
title_warn = { fg = "#7ab0df" }
title_error = { fg = "#ae81ff" }

[filetype]
rules = [
    { mime = "image/*", fg = "#79dcaa" },
    { mime = "{audio,video}/*", fg = "#7ab0df" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#8d8d8d" },
    { mime = "application/{pdf,doc,rtf}", fg = "#e0e0e0" },
    { url = "*", is = "orphan", bg = "#ae81ff" },
    { url = "*", is = "exec", fg = "#8d8d8d" },
    { url = "*", fg = "#e0e0e0" },
    { url = "*/", fg = "#7ab0df" },
]
