# : Manager [[[

[mgr]
cwd = { fg = "#e0e0e0" }

# Tab
tab_active = { fg = "#080808", bg = "#7ab0df", bold = true }
tab_inactive = { fg = "#e0e0e0", bg = "#4d4d4d" }
tab_width = 1

# Find
find_keyword = { fg = "#f87070", bold = true, italic = true, underline = true }
find_position = { fg = "#f87070", bold = true, italic = true }

# Marker
marker_copied = { fg = "#79dcaa", bg = "#79dcaa" }
marker_cut = { fg = "#c0c0c0", bg = "#c0c0c0" }
marker_marked = { fg = "#7ab0df", bg = "#7ab0df" }
marker_selected = { fg = "#707070", bg = "#707070" }

# Count
count_copied = { fg = "#121212", bg = "#c0c0c0" }
count_cut = { fg = "#121212", bg = "#c0c0c0" }
count_selected = { fg = "#080808", bg = "#707070" }

# Border
border_symbol = " "
border_style  = { fg = "#7ab0df" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#4d4d4d", fg = "#7ab0df" }

[mode]
# Mode
normal_main = { bg = "#7ab0df", fg = "#080808", bold = true }
normal_alt  = { bg = "#4d4d4d", fg = "#e0e0e0" }

# Select mode
select_main = { bg = "#c0c0c0", fg = "#080808", bold = true }
select_alt  = { bg = "#4d4d4d", fg = "#e0e0e0" }

# Unset mode
unset_main = { bg = "#707070", fg = "#080808", bold = true }
unset_alt  = { bg = "#4d4d4d", fg = "#e0e0e0" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#7ab0df", bg = "#4d4d4d" }
progress_error = { fg = "#79dcaa", bg = "#4d4d4d" }

# Permissions
permissions_t = { fg = "#7ab0df" }
permissions_w = { fg = "#707070" }
permissions_x = { fg = "#79dcaa" }
permissions_r = { fg = "#e0e0e0" }
permissions_s = { fg = "#c0c0c0" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#7ab0df" }
active = { fg = "#707070", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#7ab0df" }
value = { fg = "#e0e0e0" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#7ab0df", bold = true, bg = "#121212" }
inactive = { fg = "#c0c0c0", bg = "#121212" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#7ab0df", bg = "#4d4d4d" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#7ab0df" }
title = {}
hovered = { fg = "#c0c0c0", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#4d4d4d" }
cand = { fg = "#7ab0df" }
rest = { fg = "#080808" }
desc = { fg = "#e0e0e0" }
separator = " ▶ "
separator_style = { fg = "#e0e0e0" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e0e0e0" }
run = { fg = "#e0e0e0" }
footer = { fg = "#080808", bg = "#c0c0c0" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#707070" }
title_warn = { fg = "#7ab0df" }
title_error = { fg = "#79dcaa" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#707070" },

    # Media
    { mime = "{audio,video}/*", fg = "#7ab0df" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#c0c0c0" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#e0e0e0" },

    # Special files
    { name = "*", is = "orphan", bg = "#79dcaa" },
    { name = "*", is = "exec", fg = "#c0c0c0" },

    # Fallback
    { name = "*", fg = "#e0e0e0" },
    { name = "*/", fg = "#7ab0df" },
]

# : ]]]
