[skin]
default = "#bbc2cf #282c34 / #bbc2cf #3e424b"
tree = "#545962 None / #3e424b None"
parent = "#a9a1e1 None / #808691 None"
file = "#bbc2cf None / #a9a1e1 None"
directory = "#a9a1e1 None Bold / #a9a1e1 None Bold"
exe = "#a9a1e1 None Bold"
link = "#a9a1e1 None Italic"
pruning = "#545962 None Italic"
perm__ = "#3e424b None"
perm_r = "#a9a1e1 None"
perm_w = "#a9a1e1 None"
perm_x = "#a9a1e1 None"
owner = "#808691 None"
group = "#545962 None"
count = "#a9a1e1 #282c34"
dates = "#545962 None"
sparse = "#a9a1e1 None"
content_extract = "#808691 None Italic"
content_match = "#bbc2cf None Bold"
device_id_major = "#a9a1e1 None"
device_id_sep = "#545962 None"
device_id_minor = "#a9a1e1 None"
git_branch = "#bbc2cf None Bold"
git_insertions = "#a9a1e1 None"
git_deletions = "#a9a1e1 None"
git_status_current = "#3e424b None"
git_status_modified = "#a9a1e1 None"
git_status_new = "#bbc2cf None Bold"
git_status_ignored = "#3e424b None"
git_status_conflicted = "#a9a1e1 None Bold"
git_status_other = "#a9a1e1 None"
selected_line = "None #3e424b / None #545962"
char_match = "#bbc2cf None Bold"
file_error = "#ff6c6b None Bold"
flag_label = "#808691 None"
flag_value = "#bbc2cf None Bold"
input = "#bbc2cf None / #bbc2cf #3e424b"
status_error = "#bbc2cf #ff6c6b"
status_job = "#bbc2cf #3e424b"
status_normal = "#bbc2cf #282c34 / #bbc2cf #3e424b"
status_italic = "#a9a1e1 #282c34 Italic / #bbc2cf #3e424b"
status_bold = "#a9a1e1 #282c34 Bold / #bbc2cf #3e424b"
status_code = "#bbc2cf #282c34 / #bbc2cf #3e424b"
status_ellipsis = "#808691 #282c34 / #bbc2cf #3e424b"
purpose_normal = "#bbc2cf #3e424b"
purpose_italic = "#a9a1e1 #3e424b Italic"
purpose_bold = "#a9a1e1 #3e424b Bold"
purpose_ellipsis = "#808691 #3e424b"
scrollbar_track = "#282c34 None / #282c34 None"
scrollbar_thumb = "#545962 None / #3e424b None"
help_paragraph = "#bbc2cf None"
help_bold = "#a9a1e1 None Bold"
help_italic = "#a9a1e1 None Italic"
help_code = "#bbc2cf #3e424b"
help_headers = "#a9a1e1 None Bold"
help_table_border = "#545962 None"
preview_title = "#bbc2cf None Bold / #a9a1e1 None"
preview = "#bbc2cf #282c34 / #a9a1e1 #3e424b"
preview_separator = "#545962 None / #3e424b None"
preview_line_number = "#545962 #282c34"
preview_match = "None #545962"
hex_null = "#3e424b None"
hex_ascii_graphic = "#bbc2cf None"
hex_ascii_whitespace = "#a9a1e1 None"
hex_ascii_other = "#a9a1e1 None"
hex_non_ascii = "#a9a1e1 None"
staging_area_title = "#bbc2cf None Bold / #a9a1e1 None"
mode_command_mark = "#bbc2cf #a9a1e1 Bold"
good_to_bad_0 = "#98be65"
good_to_bad_1 = "#98be65"
good_to_bad_2 = "#98be65"
good_to_bad_3 = "#808691"
good_to_bad_4 = "#808691"
good_to_bad_5 = "#545962"
good_to_bad_6 = "#ecbe7b"
good_to_bad_7 = "#ecbe7b"
good_to_bad_8 = "#ff6c6b"
good_to_bad_9 = "#ff6c6b"
