$background = rgb(282c34)
$foreground = rgb(bbc2cf)
$accent     = rgb(a9a1e1)
$bg_subtle  = rgb(3e424b)
$bg_muted   = rgb(545962)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
