# ---------------------------------
# Kitty Theme - Doom One
# ---------------------------------

# Primary colors
foreground              #bbc2cf
background              #282c34

# Cursor
cursor                  #bbc2cf
cursor_text_color       #282c34

# Selection
selection_foreground    #bbc2cf
selection_background    #42444b

# Normal colors
color0                  #000000
color1                  #ff6c6b
color2                  #98be65
color3                  #ecbe7b
color4                  #a9a1e1
color5                  #c678dd
color6                  #51afef
color7                  #bbc2cf

# Bright colors
color8                  #595959
color9                  #ff6655
color10                 #99bb66
color11                 #ecbe7b
color12                 #a9a1e1
color13                 #c678dd
color14                 #51afef
color15                 #bfbfbf

# UI accents
url_color               #51afef

# Tabs
active_tab_foreground   #282c34
active_tab_background   #a9a1e1

inactive_tab_foreground #bbc2cf
inactive_tab_background #42444b

# Borders
active_border_color     #a9a1e1
inactive_border_color   #595959
