[palettes.doom-one]
bg               = '#282c34'
bg_subtle        = '#3e424b'
bg_muted         = '#545962'
fg               = '#bbc2cf'
fg_dim           = '#808691'
sel_bg           = '#42444b'
sel_fg           = '#bbc2cf'
error            = '#ff6c6b'
accent           = '#a9a1e1'
fg_on_accent     = '#bbc2cf'
success          = '#98be65'
warning          = '#ecbe7b'
cursor           = '#bbc2cf'
