[mgr]
cwd = { fg = "#bbc2cf" }
find_keyword = { fg = "#ff6c6b", bold = true, italic = true, underline = true }
find_position = { fg = "#ff6c6b", bold = true, italic = true }
marker_copied = { fg = "#c678dd", bg = "#c678dd" }
marker_cut = { fg = "#808691", bg = "#808691" }
marker_marked = { fg = "#a9a1e1", bg = "#a9a1e1" }
marker_selected = { fg = "#98be65", bg = "#98be65" }
count_copied = { fg = "#282c34", bg = "#808691" }
count_cut = { fg = "#282c34", bg = "#808691" }
count_selected = { fg = "#282c34", bg = "#98be65" }
border_symbol = " "
border_style = { fg = "#a9a1e1" }

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }
perm_type = { fg = "#a9a1e1" }
perm_read = { fg = "#bbc2cf" }
perm_write = { fg = "#98be65" }
perm_exec = { fg = "#c678dd" }
perm_sep = { fg = "#808691" }
progress_label = { bold = true }
progress_normal = { fg = "#a9a1e1", bg = "#3e424b" }
progress_error = { fg = "#c678dd", bg = "#3e424b" }

[mode]
normal_main = { bg = "#a9a1e1", fg = "#282c34", bold = true }
normal_alt  = { bg = "#3e424b", fg = "#bbc2cf" }
select_main = { bg = "#808691", fg = "#282c34", bold = true }
select_alt  = { bg = "#3e424b", fg = "#bbc2cf" }
unset_main = { bg = "#98be65", fg = "#282c34", bold = true }
unset_alt  = { bg = "#3e424b", fg = "#bbc2cf" }

[select]
border = { fg = "#a9a1e1" }
active = { fg = "#98be65", bold = true }

[input]
border = { fg = "#a9a1e1" }
value = { fg = "#bbc2cf" }

[tabs]
active = { fg = "#a9a1e1", bold = true, bg = "#282c34" }
inactive = { fg = "#808691", bg = "#282c34" }
sep_inner = { open = "[", close = "]" }

[cmp]
border = { fg = "#a9a1e1", bg = "#3e424b" }

[tasks]
border = { fg = "#a9a1e1" }
title = {}
hovered = { fg = "#808691", underline = true }

[which]
cols = 3
mask = { bg = "#3e424b" }
cand = { fg = "#a9a1e1" }
rest = { fg = "#282c34" }
desc = { fg = "#bbc2cf" }
separator = " ▶ "
separator_style = { fg = "#bbc2cf" }

[help]
on = { fg = "#bbc2cf" }
run = { fg = "#bbc2cf" }
footer = { fg = "#282c34", bg = "#808691" }

[notify]
title_info = { fg = "#98be65" }
title_warn = { fg = "#a9a1e1" }
title_error = { fg = "#c678dd" }

[filetype]
rules = [
    { mime = "image/*", fg = "#98be65" },
    { mime = "{audio,video}/*", fg = "#a9a1e1" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#808691" },
    { mime = "application/{pdf,doc,rtf}", fg = "#bbc2cf" },
    { url = "*", is = "orphan", bg = "#c678dd" },
    { url = "*", is = "exec", fg = "#808691" },
    { url = "*", fg = "#bbc2cf" },
    { url = "*/", fg = "#a9a1e1" },
]
