# : Manager [[[

[mgr]
cwd = { fg = "#bbc2cf" }

# Find
find_keyword = { fg = "#ff6c6b", bold = true, italic = true, underline = true }
find_position = { fg = "#ff6c6b", bold = true, italic = true }

# Marker
marker_copied = { fg = "#51afef", bg = "#51afef" }
marker_cut = { fg = "#bfbfbf", bg = "#bfbfbf" }
marker_marked = { fg = "#a9a1e1", bg = "#a9a1e1" }
marker_selected = { fg = "#7a7a7a", bg = "#7a7a7a" }

# Count
count_copied = { fg = "#282c34", bg = "#bfbfbf" }
count_cut = { fg = "#282c34", bg = "#bfbfbf" }
count_selected = { fg = "#000000", bg = "#7a7a7a" }

# Border
border_symbol = " "
border_style = { fg = "#a9a1e1" }

# : ]]]


# : Status [[[

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }

# Permissions
perm_type = { fg = "#a9a1e1" }
perm_read = { fg = "#bbc2cf" }
perm_write = { fg = "#7a7a7a" }
perm_exec = { fg = "#51afef" }
perm_sep = { fg = "#bfbfbf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#a9a1e1", bg = "#595959" }
progress_error = { fg = "#51afef", bg = "#595959" }

[mode]
normal_main = { bg = "#a9a1e1", fg = "#000000", bold = true }
normal_alt  = { bg = "#595959", fg = "#bbc2cf" }

select_main = { bg = "#bfbfbf", fg = "#000000", bold = true }
select_alt  = { bg = "#595959", fg = "#bbc2cf" }

unset_main = { bg = "#7a7a7a", fg = "#000000", bold = true }
unset_alt  = { bg = "#595959", fg = "#bbc2cf" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#a9a1e1" }
active = { fg = "#7a7a7a", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#a9a1e1" }
value = { fg = "#bbc2cf" }

# : ]]]


# : Tabs [[[

[tabs]
active = { fg = "#a9a1e1", bold = true, bg = "#282c34" }
inactive = { fg = "#bfbfbf", bg = "#282c34" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#a9a1e1", bg = "#595959" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#a9a1e1" }
title = {}
hovered = { fg = "#bfbfbf", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#595959" }
cand = { fg = "#a9a1e1" }
rest = { fg = "#000000" }
desc = { fg = "#bbc2cf" }
separator = " ▶ "
separator_style = { fg = "#bbc2cf" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#bbc2cf" }
run = { fg = "#bbc2cf" }
footer = { fg = "#000000", bg = "#bfbfbf" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#7a7a7a" }
title_warn = { fg = "#a9a1e1" }
title_error = { fg = "#51afef" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    { mime = "image/*", fg = "#7a7a7a" },
    { mime = "{audio,video}/*", fg = "#a9a1e1" },

    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#bfbfbf" },

    { mime = "application/{pdf,doc,rtf}", fg = "#bbc2cf" },

    { url = "*", is = "orphan", bg = "#51afef" },
    { url = "*", is = "exec", fg = "#bfbfbf" },

    { url = "*", fg = "#bbc2cf" },
    { url = "*/", fg = "#a9a1e1" },
]

# : ]]]
