[skin]
default = "#f8f8f2 #282a36 / #f8f8f2 #474852"
tree = "#66676e None / #474852 None"
parent = "#bd93f9 None / #a4a5a6 None"
file = "#f8f8f2 None / #bd93f9 None"
directory = "#bd93f9 None Bold / #bd93f9 None Bold"
exe = "#bd93f9 None Bold"
link = "#bd93f9 None Italic"
pruning = "#66676e None Italic"
perm__ = "#474852 None"
perm_r = "#bd93f9 None"
perm_w = "#bd93f9 None"
perm_x = "#bd93f9 None"
owner = "#a4a5a6 None"
group = "#66676e None"
count = "#bd93f9 #282a36"
dates = "#66676e None"
sparse = "#bd93f9 None"
content_extract = "#a4a5a6 None Italic"
content_match = "#f8f8f2 None Bold"
device_id_major = "#bd93f9 None"
device_id_sep = "#66676e None"
device_id_minor = "#bd93f9 None"
git_branch = "#f8f8f2 None Bold"
git_insertions = "#bd93f9 None"
git_deletions = "#bd93f9 None"
git_status_current = "#474852 None"
git_status_modified = "#bd93f9 None"
git_status_new = "#f8f8f2 None Bold"
git_status_ignored = "#474852 None"
git_status_conflicted = "#bd93f9 None Bold"
git_status_other = "#bd93f9 None"
selected_line = "None #474852 / None #66676e"
char_match = "#f8f8f2 None Bold"
file_error = "#ff5555 None Bold"
flag_label = "#a4a5a6 None"
flag_value = "#f8f8f2 None Bold"
input = "#f8f8f2 None / #f8f8f2 #474852"
status_error = "#f8f8f2 #ff5555"
status_job = "#f8f8f2 #474852"
status_normal = "#f8f8f2 #282a36 / #ffffff #474852"
status_italic = "#bd93f9 #282a36 Italic / #ffffff #474852"
status_bold = "#bd93f9 #282a36 Bold / #ffffff #474852"
status_code = "#f8f8f2 #282a36 / #ffffff #474852"
status_ellipsis = "#a4a5a6 #282a36 / #ffffff #474852"
purpose_normal = "#f8f8f2 #474852"
purpose_italic = "#bd93f9 #474852 Italic"
purpose_bold = "#bd93f9 #474852 Bold"
purpose_ellipsis = "#a4a5a6 #474852"
scrollbar_track = "#282a36 None / #282a36 None"
scrollbar_thumb = "#66676e None / #474852 None"
help_paragraph = "#f8f8f2 None"
help_bold = "#bd93f9 None Bold"
help_italic = "#bd93f9 None Italic"
help_code = "#f8f8f2 #474852"
help_headers = "#bd93f9 None Bold"
help_table_border = "#66676e None"
preview_title = "#f8f8f2 None Bold / #bd93f9 None"
preview = "#f8f8f2 #282a36 / #bd93f9 #474852"
preview_separator = "#66676e None / #474852 None"
preview_line_number = "#66676e #282a36"
preview_match = "None #66676e"
hex_null = "#474852 None"
hex_ascii_graphic = "#f8f8f2 None"
hex_ascii_whitespace = "#bd93f9 None"
hex_ascii_other = "#bd93f9 None"
hex_non_ascii = "#bd93f9 None"
staging_area_title = "#f8f8f2 None Bold / #bd93f9 None"
mode_command_mark = "#ffffff #bd93f9 Bold"
good_to_bad_0 = "#50fa7b"
good_to_bad_1 = "#50fa7b"
good_to_bad_2 = "#50fa7b"
good_to_bad_3 = "#a4a5a6"
good_to_bad_4 = "#a4a5a6"
good_to_bad_5 = "#66676e"
good_to_bad_6 = "#f1fa8c"
good_to_bad_7 = "#f1fa8c"
good_to_bad_8 = "#ff5555"
good_to_bad_9 = "#ff5555"
