$background = rgb(282a36)
$foreground = rgb(f8f8f2)
$accent     = rgb(bd93f9)
$bg_subtle  = rgb(474852)
$bg_muted   = rgb(66676e)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
