[palettes.dracula]
bg               = '#282a36'
bg_subtle        = '#474852'
bg_muted         = '#66676e'
fg               = '#f8f8f2'
fg_dim           = '#a4a5a6'
sel_bg           = '#44475a'
sel_fg           = '#ffffff'
error            = '#ff5555'
accent           = '#bd93f9'
fg_on_accent     = '#f8f8f2'
success          = '#50fa7b'
warning          = '#f1fa8c'
cursor           = '#f8f8f2'
