format = """
[](#bcaaa4)\
$os\
[](bg:#bcaaa4 fg:#090c0c)\
[](bg:#d7ccc8 fg:#bcaaa4)\
$directory\
[](fg:#d7ccc8 bg:#543f3b)\
$git_branch\
$git_status\
[](fg:#543f3b bg:#6b5854)\
$nodejs\
$rust\
$golang\
$zsh\
$vscode\
$python\
$php\
[](fg:#6b5854 bg:#3e2723)\
$time\
[ ](fg:#3e2723)\
\n$character"""

[directory]
style = "fg:#3e2723 bg:#d7ccc8"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music"     = " "
"Pictures"  = " "

[git_branch]
style = "bg:#543f3b"
format = '[[ $symbol $branch ](fg:#d7ccc8 bg:#543f3b)]($style)'

[git_status]
style = "fg:#d7ccc8 bg:#543f3b"
format = '[[($all_status$ahead_behind )](fg:#d7ccc8 bg:#543f3b)]($style)'
conflicted = "‼"
ahead      = "⇡"
behind     = "⇣"
diverged   = "↕"
up_to_date = "✓"
untracked  = ""
stashed    = " "
modified   = "●"
staged     = "[++\\($count\\)](fg:#bcaaa4)"
renamed    = "➜"
deleted    = "✖"

[character]
success_symbol = "[✔](fg:#bcaaa4)"
error_symbol   = "[✖](fg:#bcaaa4)"

[nodejs]
symbol = ""
style  = "bg:#6b5854"
format = '[[ $symbol ($version) ](fg:#998a86 bg:#6b5854)]($style)'

[rust]
symbol = ""
style  = "bg:#6b5854"
format = '[[ $symbol ($version) ](fg:#998a86 bg:#6b5854)]($style)'

[golang]
symbol = ""
style  = "bg:#6b5854"
format = '[[ $symbol ($version) ](fg:#998a86 bg:#6b5854)]($style)'

[python]
symbol = ""
style  = "bg:#6b5854"
format = '[[ $symbol ($version) ](fg:#998a86 bg:#6b5854)]($style)'

[php]
symbol = ""
style  = "bg:#6b5854"
format = '[[ $symbol ($version) ](fg:#998a86 bg:#6b5854)]($style)'

[time]
disabled    = false
time_format = "%R"
style       = "bg:#3e2723"
format      = '[[ $time ](fg:#d7ccc8 bg:#3e2723)]($style)'

[os]
disabled = false
style    = "fg:#090c0c bg:#bcaaa4"

[os.symbols]
Windows           = "󰍲"
Ubuntu            = "󰌽 "
SUSE              = ""
Raspbian          = "󰐿"
Mint              = "󰣭"
Macos             = ""
Manjaro           = ""
Linux             = "󰌽"
Gentoo            = "󰣨"
Fedora            = "󰣛"
Alpine            = ""
Amazon            = ""
Android           = ""
Arch              = "󰣇"
Artix             = "󰣇"
CentOS            = ""
Debian            = "󰣚"
Redhat            = "󱄛"
RedHatEnterprise  = "󱄛"
