format = """
[](#6f8fa3)\
$os\
[](bg:#6f8fa3 fg:#1b1a17)\
[](bg:#8a9a7b fg:#6f8fa3)\
$directory\
[](fg:#8a9a7b bg:#36342e)\
$git_branch\
$git_status\
[](fg:#36342e bg:#514e46)\
$nodejs\
$rust\
$golang\
$zsh\
$vscode\
$python\
$php\
[](fg:#514e46 bg:#1b1a17)\
$time\
[ ](fg:#1b1a17)\
\n$character"""

[directory]
style = "fg:#1b1a17 bg:#8a9a7b"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music"     = " "
"Pictures"  = " "

[git_branch]
style = "bg:#36342e"
format = '[[ $symbol $branch ](fg:#d0c8b6 bg:#36342e)]($style)'

[git_status]
style = "fg:#d0c8b6 bg:#36342e"
format = '[[($all_status$ahead_behind )](fg:#d0c8b6 bg:#36342e)]($style)'
conflicted = "‼"
ahead      = "⇡"
behind     = "⇣"
diverged   = "↕"
up_to_date = "✓"
untracked  = ""
stashed    = " "
modified   = "●"
staged     = "[++\\($count\\)](fg:#6f8fa3)"
renamed    = "➜"
deleted    = "✖"

[character]
success_symbol = "[✔](fg:#6f8fa3)"
error_symbol   = "[✖](fg:#c26a4a)"

[nodejs]
symbol = ""
style  = "bg:#514e46"
format = '[[ $symbol ($version) ](fg:#878276 bg:#514e46)]($style)'

[rust]
symbol = ""
style  = "bg:#514e46"
format = '[[ $symbol ($version) ](fg:#878276 bg:#514e46)]($style)'

[golang]
symbol = ""
style  = "bg:#514e46"
format = '[[ $symbol ($version) ](fg:#878276 bg:#514e46)]($style)'

[python]
symbol = ""
style  = "bg:#514e46"
format = '[[ $symbol ($version) ](fg:#878276 bg:#514e46)]($style)'

[php]
symbol = ""
style  = "bg:#514e46"
format = '[[ $symbol ($version) ](fg:#878276 bg:#514e46)]($style)'

[time]
disabled    = false
time_format = "%R"
style       = "bg:#1b1a17"
format      = '[[ $time ](fg:#d0c8b6 bg:#1b1a17)]($style)'

[os]
disabled = false
style    = "fg:#1b1a17 bg:#6f8fa3"

[os.symbols]
Windows           = "󰍲"
Ubuntu            = "󰌽 "
SUSE              = ""
Raspbian          = "󰐿"
Mint              = "󰣭"
Macos             = ""
Manjaro           = ""
Linux             = "󰌽"
Gentoo            = "󰣨"
Fedora            = "󰣛"
Alpine            = ""
Amazon            = ""
Android           = ""
Arch              = "󰣇"
Artix             = "󰣇"
CentOS            = ""
Debian            = "󰣚"
Redhat            = "󱄛"
RedHatEnterprise  = "󱄛"
