$background = rgb({{bg:rgb}})
$foreground = rgb({{fg:rgb}})
$accent     = rgb({{accent:rgb}})

$bg_subtle  = rgb({{bg_subtle:rgb}})
$bg_muted   = rgb({{bg_muted:rgb}})

$active_border   = $accent
$inactive_border = $bg_muted

$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
