[palettes.zorro]
bg               = '{{bg}}'
bg_subtle        = '{{bg_subtle}}'
bg_muted         = '{{bg_muted}}'
fg               = '{{fg}}'
fg_dim           = '{{fg_dim}}'
sel_bg           = '{{sel_bg}}'
sel_fg           = '{{sel_fg}}'
error            = '{{error}}'
accent           = '{{accent}}'
fg_on_accent     = '{{fg_on_accent}}'
success          = '{{success}}'
warning          = '{{warning}}'
cursor           = '{{cursor}}'
