[palettes.zorro]
base             = '{{bg}}'
crust            = '{{bg_muted}}'
on_sig1          = '{{bg}}'
on_sig2          = '{{fg}}'
on_sigbg         = '{{fg}}'
red              = '{{error}}'
sig1             = '{{accent}}'
sig2             = '{{color5}}'
sig_bg           = '{{bg}}'
sig_surface_high = '{{bg_subtle}}'
text             = '{{fg}}'
