[mgr]
cwd = { fg = "{{fg}}" }
find_keyword = { fg = "{{error}}", bold = true, italic = true, underline = true }
find_position = { fg = "{{error}}", bold = true, italic = true }
marker_copied = { fg = "{{color5}}", bg = "{{color5}}" }
marker_cut = { fg = "{{fg_dim}}", bg = "{{fg_dim}}" }
marker_marked = { fg = "{{accent}}", bg = "{{accent}}" }
marker_selected = { fg = "{{color2}}", bg = "{{color2}}" }
count_copied = { fg = "{{bg}}", bg = "{{fg_dim}}" }
count_cut = { fg = "{{bg}}", bg = "{{fg_dim}}" }
count_selected = { fg = "{{bg}}", bg = "{{color2}}" }
border_symbol = " "
border_style = { fg = "{{accent}}" }

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }
perm_type = { fg = "{{accent}}" }
perm_read = { fg = "{{fg}}" }
perm_write = { fg = "{{color2}}" }
perm_exec = { fg = "{{color5}}" }
perm_sep = { fg = "{{fg_dim}}" }
progress_label = { bold = true }
progress_normal = { fg = "{{accent}}", bg = "{{bg_subtle}}" }
progress_error = { fg = "{{color5}}", bg = "{{bg_subtle}}" }

[mode]
normal_main = { bg = "{{accent}}", fg = "{{bg}}", bold = true }
normal_alt  = { bg = "{{bg_subtle}}", fg = "{{fg}}" }
select_main = { bg = "{{fg_dim}}", fg = "{{bg}}", bold = true }
select_alt  = { bg = "{{bg_subtle}}", fg = "{{fg}}" }
unset_main = { bg = "{{color2}}", fg = "{{bg}}", bold = true }
unset_alt  = { bg = "{{bg_subtle}}", fg = "{{fg}}" }

[select]
border = { fg = "{{accent}}" }
active = { fg = "{{color2}}", bold = true }

[input]
border = { fg = "{{accent}}" }
value = { fg = "{{fg}}" }

[tabs]
active = { fg = "{{accent}}", bold = true, bg = "{{bg}}" }
inactive = { fg = "{{fg_dim}}", bg = "{{bg}}" }
sep_inner = { open = "[", close = "]" }

[cmp]
border = { fg = "{{accent}}", bg = "{{bg_subtle}}" }

[tasks]
border = { fg = "{{accent}}" }
title = {}
hovered = { fg = "{{fg_dim}}", underline = true }

[which]
cols = 3
mask = { bg = "{{bg_subtle}}" }
cand = { fg = "{{accent}}" }
rest = { fg = "{{bg}}" }
desc = { fg = "{{fg}}" }
separator = " ▶ "
separator_style = { fg = "{{fg}}" }

[help]
on = { fg = "{{fg}}" }
run = { fg = "{{fg}}" }
footer = { fg = "{{bg}}", bg = "{{fg_dim}}" }

[notify]
title_info = { fg = "{{color2}}" }
title_warn = { fg = "{{accent}}" }
title_error = { fg = "{{color5}}" }

[filetype]
rules = [
    { mime = "image/*", fg = "{{color2}}" },
    { mime = "{audio,video}/*", fg = "{{accent}}" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "{{fg_dim}}" },
    { mime = "application/{pdf,doc,rtf}", fg = "{{fg}}" },
    { url = "*", is = "orphan", bg = "{{color5}}" },
    { url = "*", is = "exec", fg = "{{fg_dim}}" },
    { url = "*", fg = "{{fg}}" },
    { url = "*/", fg = "{{accent}}" },
]
