[skin]
default = "#D8DEE9 #2E3440 / #D8DEE9 #474d59"
tree = "#616772 None / #474d59 None"
parent = "#81A1C1 None / #949aa5 None"
file = "#D8DEE9 None / #81A1C1 None"
directory = "#81A1C1 None Bold / #81A1C1 None Bold"
exe = "#81A1C1 None Bold"
link = "#81A1C1 None Italic"
pruning = "#616772 None Italic"
perm__ = "#474d59 None"
perm_r = "#81A1C1 None"
perm_w = "#81A1C1 None"
perm_x = "#81A1C1 None"
owner = "#949aa5 None"
group = "#616772 None"
count = "#81A1C1 #2E3440"
dates = "#616772 None"
sparse = "#81A1C1 None"
content_extract = "#949aa5 None Italic"
content_match = "#D8DEE9 None Bold"
device_id_major = "#81A1C1 None"
device_id_sep = "#616772 None"
device_id_minor = "#81A1C1 None"
git_branch = "#D8DEE9 None Bold"
git_insertions = "#81A1C1 None"
git_deletions = "#81A1C1 None"
git_status_current = "#474d59 None"
git_status_modified = "#81A1C1 None"
git_status_new = "#D8DEE9 None Bold"
git_status_ignored = "#474d59 None"
git_status_conflicted = "#81A1C1 None Bold"
git_status_other = "#81A1C1 None"
selected_line = "None #474d59 / None #616772"
char_match = "#D8DEE9 None Bold"
file_error = "#BF616A None Bold"
flag_label = "#949aa5 None"
flag_value = "#D8DEE9 None Bold"
input = "#D8DEE9 None / #D8DEE9 #474d59"
status_error = "#D8DEE9 #BF616A"
status_job = "#D8DEE9 #474d59"
status_normal = "#D8DEE9 #2E3440 / #000000 #474d59"
status_italic = "#81A1C1 #2E3440 Italic / #000000 #474d59"
status_bold = "#81A1C1 #2E3440 Bold / #000000 #474d59"
status_code = "#D8DEE9 #2E3440 / #000000 #474d59"
status_ellipsis = "#949aa5 #2E3440 / #000000 #474d59"
purpose_normal = "#D8DEE9 #474d59"
purpose_italic = "#81A1C1 #474d59 Italic"
purpose_bold = "#81A1C1 #474d59 Bold"
purpose_ellipsis = "#949aa5 #474d59"
scrollbar_track = "#2E3440 None / #2E3440 None"
scrollbar_thumb = "#616772 None / #474d59 None"
help_paragraph = "#D8DEE9 None"
help_bold = "#81A1C1 None Bold"
help_italic = "#81A1C1 None Italic"
help_code = "#D8DEE9 #474d59"
help_headers = "#81A1C1 None Bold"
help_table_border = "#616772 None"
preview_title = "#D8DEE9 None Bold / #81A1C1 None"
preview = "#D8DEE9 #2E3440 / #81A1C1 #474d59"
preview_separator = "#616772 None / #474d59 None"
preview_line_number = "#616772 #2E3440"
preview_match = "None #616772"
hex_null = "#474d59 None"
hex_ascii_graphic = "#D8DEE9 None"
hex_ascii_whitespace = "#81A1C1 None"
hex_ascii_other = "#81A1C1 None"
hex_non_ascii = "#81A1C1 None"
staging_area_title = "#D8DEE9 None Bold / #81A1C1 None"
mode_command_mark = "#000000 #81A1C1 Bold"
good_to_bad_0 = "#A3BE8C"
good_to_bad_1 = "#A3BE8C"
good_to_bad_2 = "#A3BE8C"
good_to_bad_3 = "#949aa5"
good_to_bad_4 = "#949aa5"
good_to_bad_5 = "#616772"
good_to_bad_6 = "#EBCB8B"
good_to_bad_7 = "#EBCB8B"
good_to_bad_8 = "#BF616A"
good_to_bad_9 = "#BF616A"
