$background = rgb(2E3440)
$foreground = rgb(D8DEE9)
$accent     = rgb(81A1C1)
$bg_subtle  = rgb(474d59)
$bg_muted   = rgb(616772)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
