[palettes.nord]
bg               = '#2E3440'
bg_subtle        = '#474d59'
bg_muted         = '#616772'
fg               = '#D8DEE9'
fg_dim           = '#949aa5'
sel_bg           = '#FFFACD'
sel_fg           = '#000000'
error            = '#BF616A'
accent           = '#81A1C1'
fg_on_accent     = '#D8DEE9'
success          = '#A3BE8C'
warning          = '#EBCB8B'
cursor           = '#81A1C1'
