#!/bin/sh

# Get a list of all executable scripts in ~/scripts, following symlinks
scripts=$(find -L ~/dotfiles/home/scripts -maxdepth 1 -type f -executable -exec basename {} \;)

# Check if there are any scripts
if [ -z "$scripts" ]; then
    notify-send "Script Execution" "No executable scripts found in ~/dotfiles/home/scripts."
    exit 1
fi

# Let the user select a script using wofi
selected_script=$(echo "$scripts" | wofi --dmenu --prompt "Select a script to run")

# Check if a script was selected
if [ -n "$selected_script" ]; then
    # Run the selected script
    ~/dotfiles/home/scripts/"$selected_script"
else
    notify-send "Script Execution" "No script selected. Exiting."
    exit 1
fi

