#!/bin/sh

# Paths - customize these!
ISO="$HOME/Downloads/tiny-xp.iso"       # Path to your ISO
DISK_IMG="$HOME/Downloads/tinyxp.qcow2" # Path to virtual disk
SIZE="10G"                             # Disk size

# Create disk image if it doesn't exist
if [ ! -f "$DISK_IMG" ]; then
    qemu-img create -f qcow2 "$DISK_IMG" "$SIZE" || exit 1
fi

# Run QEMU with all arguments on one line
exec qemu-system-x86_64 \
    -enable-kvm \
    -m 1G \
    -smp 2 \
    -cdrom "$ISO" \
    -boot d \
    -hda "$DISK_IMG" \
    -vga std \
    -net nic,model=e1000 \
    -net user
