#!/bin/sh

# Paths - customize these!
WIN_ISO="$HOME/Downloads/tiny-xp.iso"       # Windows XP ISO
DISK_IMG="$HOME/Downloads/tinyxp.qcow2"     # Virtual disk
GAME_ISO="$HOME/Downloads/games/Lula/lula.iso" # Game ISO
SIZE="10G"                                  # Disk size

# Create disk image if it doesn't exist
if [ ! -f "$DISK_IMG" ]; then
    qemu-img create -f qcow2 "$DISK_IMG" "$SIZE" || exit 1
fi

# Build the QEMU command
exec qemu-system-x86_64 \
    -enable-kvm \
    -m 1G \
    -smp 2 \
    -drive "file=$WIN_ISO,media=cdrom,index=0" \
    -drive "file=$DISK_IMG,index=1" \
    -drive "file=$GAME_ISO,media=cdrom,index=2" \
    -boot d \
    -vga vmware \
    -device ac97 \
    -net nic,model=e1000 \
    -net user
