# ╔══════════════════════════════════════════════════════════════════╗
# ║                       alacritty.toml                            ║
# ╚══════════════════════════════════════════════════════════════════╝


# ════════════════════════════════════════════════════════════════════
# IMPORTS
# ════════════════════════════════════════════════════════════════════
[general]

import = [
    "~/.config/alacritty/colors.toml"
]

# ════════════════════════════════════════════════════════════════════
# FONT
# ════════════════════════════════════════════════════════════════════

[font]

size = 20

[font.normal]
family = "FantasqueSansM Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FantasqueSansM Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Italic"


# ════════════════════════════════════════════════════════════════════
# FONT METRICS
# ════════════════════════════════════════════════════════════════════

[font.offset]

x = 0
y = 0


[font.glyph_offset]

x = 0
y = 0


# ════════════════════════════════════════════════════════════════════
# WINDOW
# ════════════════════════════════════════════════════════════════════

[window]

opacity = 0.41

decorations = "full"

dynamic_padding = false

padding = { 
    x = 14,
    y = 5
}


# ════════════════════════════════════════════════════════════════════
# CURSOR
# ════════════════════════════════════════════════════════════════════

[cursor]
unfocused_hollow = true


[cursor.style]
shape = "Underline"
blinking = "Off"

# ════════════════════════════════════════════════════════════════════
# TERMINAL
# ════════════════════════════════════════════════════════════════════

[scrolling]

history = 10000


[terminal]

shell = { program = "/usr/bin/zsh" }


# ════════════════════════════════════════════════════════════════════
# PERFORMANCE
# ════════════════════════════════════════════════════════════════════

[debug]

persistent_logging = false


# ════════════════════════════════════════════════════════════════════
# MOUSE
# ════════════════════════════════════════════════════════════════════

[mouse]
hide_when_typing = false


# ════════════════════════════════════════════════════════════════════
# SELECTION
# ════════════════════════════════════════════════════════════════════

[selection]
save_to_clipboard = true


# ════════════════════════════════════════════════════════════════════
# KEYBINDS
# ════════════════════════════════════════════════════════════════════

[keyboard]

bindings = [
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" },

    { key = "Insert", mods = "Control", action = "Copy" },
    { key = "Insert", mods = "Shift", action = "Paste" }
]
