[skin]
default = "#00ca7d #00060f / #00ca7d #00231f"
tree = "#004030 None / #00231f None"
parent = "#004cf1 None / #007b51 None"
file = "#00ca7d None / #004cf1 None"
directory = "#004cf1 None Bold / #004cf1 None Bold"
exe = "#004cf1 None Bold"
link = "#004cf1 None Italic"
pruning = "#004030 None Italic"
perm__ = "#00231f None"
perm_r = "#004cf1 None"
perm_w = "#004cf1 None"
perm_x = "#004cf1 None"
owner = "#007b51 None"
group = "#004030 None"
count = "#004cf1 #00060f"
dates = "#004030 None"
sparse = "#004cf1 None"
content_extract = "#007b51 None Italic"
content_match = "#00ca7d None Bold"
device_id_major = "#004cf1 None"
device_id_sep = "#004030 None"
device_id_minor = "#004cf1 None"
git_branch = "#00ca7d None Bold"
git_insertions = "#004cf1 None"
git_deletions = "#004cf1 None"
git_status_current = "#00231f None"
git_status_modified = "#004cf1 None"
git_status_new = "#00ca7d None Bold"
git_status_ignored = "#00231f None"
git_status_conflicted = "#004cf1 None Bold"
git_status_other = "#004cf1 None"
selected_line = "None #00231f / None #004030"
char_match = "#00ca7d None Bold"
file_error = "#c00e0e None Bold"
flag_label = "#007b51 None"
flag_value = "#00ca7d None Bold"
input = "#00ca7d None / #00ca7d #00231f"
status_error = "#00ca7d #c00e0e"
status_job = "#00ca7d #00231f"
status_normal = "#00ca7d #00060f / #00ca7d #00231f"
status_italic = "#004cf1 #00060f Italic / #00ca7d #00231f"
status_bold = "#004cf1 #00060f Bold / #00ca7d #00231f"
status_code = "#00ca7d #00060f / #00ca7d #00231f"
status_ellipsis = "#007b51 #00060f / #00ca7d #00231f"
purpose_normal = "#00ca7d #00231f"
purpose_italic = "#004cf1 #00231f Italic"
purpose_bold = "#004cf1 #00231f Bold"
purpose_ellipsis = "#007b51 #00231f"
scrollbar_track = "#00060f None / #00060f None"
scrollbar_thumb = "#004030 None / #00231f None"
help_paragraph = "#00ca7d None"
help_bold = "#004cf1 None Bold"
help_italic = "#004cf1 None Italic"
help_code = "#00ca7d #00231f"
help_headers = "#004cf1 None Bold"
help_table_border = "#004030 None"
preview_title = "#00ca7d None Bold / #004cf1 None"
preview = "#00ca7d #00060f / #004cf1 #00231f"
preview_separator = "#004030 None / #00231f None"
preview_line_number = "#004030 #00060f"
preview_match = "None #004030"
hex_null = "#00231f None"
hex_ascii_graphic = "#00ca7d None"
hex_ascii_whitespace = "#004cf1 None"
hex_ascii_other = "#004cf1 None"
hex_non_ascii = "#004cf1 None"
staging_area_title = "#00ca7d None Bold / #004cf1 None"
mode_command_mark = "#00ca7d #004cf1 Bold"
good_to_bad_0 = "#0059ff"
good_to_bad_1 = "#0059ff"
good_to_bad_2 = "#0059ff"
good_to_bad_3 = "#007b51"
good_to_bad_4 = "#007b51"
good_to_bad_5 = "#004030"
good_to_bad_6 = "#1a1b03"
good_to_bad_7 = "#1a1b03"
good_to_bad_8 = "#c00e0e"
good_to_bad_9 = "#c00e0e"
