$background = rgb(00060f)
$foreground = rgb(00ca7d)
$accent     = rgb(004cf1)
$bg_subtle  = rgb(00231f)
$bg_muted   = rgb(004030)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
