# ---------------------------------
# Hackerman Kitty Theme
# ---------------------------------

foreground              #00ca7d
background              #00060f

selection_foreground    #00ca7d
selection_background    #5900ff

cursor                  #00ca7d
cursor_text_color       #002b25

# Normal colors
color0                  #10d4b0
color1                  #c00e0e
color2                  #0059ff
color3                  #1a1b03
color4                  #004cf1
color5                  #94058a
color6                  #029790
color7                  #311b92

# Bright colors
color8                  #02adf1
color9                  #ff0000
color10                 #00ff9c
color11                 #ffdd00
color12                 #00a2ff
color13                 #e215d4
color14                 #08e1d7
color15                 #2eb8f8

# URL color
url_color               #00a2ff

# Tabs
active_tab_foreground   #00060f
active_tab_background   #00d482

inactive_tab_foreground #00d483
inactive_tab_background #08080c

# Window border
active_border_color     #00ff9c
inactive_border_color   #00d483
bell_border_color       #ff0000

# Transparency
background_opacity      0.90
