[palettes.hackerman]
bg               = '#00060f'
bg_subtle        = '#00231f'
bg_muted         = '#004030'
fg               = '#00ca7d'
fg_dim           = '#007b51'
sel_bg           = '#5900ff'
sel_fg           = '#00ca7d'
error            = '#c00e0e'
accent           = '#004cf1'
fg_on_accent     = '#00ca7d'
success          = '#0059ff'
warning          = '#1a1b03'
cursor           = '#00ca7d'
