[skin]
default = "#d3c6aa #272e33 / #d3c6aa #404444"
tree = "#5a5b56 None / #404444 None"
parent = "#7fbbb3 None / #8e897a None"
file = "#d3c6aa None / #7fbbb3 None"
directory = "#7fbbb3 None Bold / #7fbbb3 None Bold"
exe = "#7fbbb3 None Bold"
link = "#7fbbb3 None Italic"
pruning = "#5a5b56 None Italic"
perm__ = "#404444 None"
perm_r = "#7fbbb3 None"
perm_w = "#7fbbb3 None"
perm_x = "#7fbbb3 None"
owner = "#8e897a None"
group = "#5a5b56 None"
count = "#7fbbb3 #272e33"
dates = "#5a5b56 None"
sparse = "#7fbbb3 None"
content_extract = "#8e897a None Italic"
content_match = "#d3c6aa None Bold"
device_id_major = "#7fbbb3 None"
device_id_sep = "#5a5b56 None"
device_id_minor = "#7fbbb3 None"
git_branch = "#d3c6aa None Bold"
git_insertions = "#7fbbb3 None"
git_deletions = "#7fbbb3 None"
git_status_current = "#404444 None"
git_status_modified = "#7fbbb3 None"
git_status_new = "#d3c6aa None Bold"
git_status_ignored = "#404444 None"
git_status_conflicted = "#7fbbb3 None Bold"
git_status_other = "#7fbbb3 None"
selected_line = "None #404444 / None #5a5b56"
char_match = "#d3c6aa None Bold"
file_error = "#e67e80 None Bold"
flag_label = "#8e897a None"
flag_value = "#d3c6aa None Bold"
input = "#d3c6aa None / #d3c6aa #404444"
status_error = "#d3c6aa #e67e80"
status_job = "#d3c6aa #404444"
status_normal = "#d3c6aa #272e33 / #9da9a0 #404444"
status_italic = "#7fbbb3 #272e33 Italic / #9da9a0 #404444"
status_bold = "#7fbbb3 #272e33 Bold / #9da9a0 #404444"
status_code = "#d3c6aa #272e33 / #9da9a0 #404444"
status_ellipsis = "#8e897a #272e33 / #9da9a0 #404444"
purpose_normal = "#d3c6aa #404444"
purpose_italic = "#7fbbb3 #404444 Italic"
purpose_bold = "#7fbbb3 #404444 Bold"
purpose_ellipsis = "#8e897a #404444"
scrollbar_track = "#272e33 None / #272e33 None"
scrollbar_thumb = "#5a5b56 None / #404444 None"
help_paragraph = "#d3c6aa None"
help_bold = "#7fbbb3 None Bold"
help_italic = "#7fbbb3 None Italic"
help_code = "#d3c6aa #404444"
help_headers = "#7fbbb3 None Bold"
help_table_border = "#5a5b56 None"
preview_title = "#d3c6aa None Bold / #7fbbb3 None"
preview = "#d3c6aa #272e33 / #7fbbb3 #404444"
preview_separator = "#5a5b56 None / #404444 None"
preview_line_number = "#5a5b56 #272e33"
preview_match = "None #5a5b56"
hex_null = "#404444 None"
hex_ascii_graphic = "#d3c6aa None"
hex_ascii_whitespace = "#7fbbb3 None"
hex_ascii_other = "#7fbbb3 None"
hex_non_ascii = "#7fbbb3 None"
staging_area_title = "#d3c6aa None Bold / #7fbbb3 None"
mode_command_mark = "#9da9a0 #7fbbb3 Bold"
good_to_bad_0 = "#a7c080"
good_to_bad_1 = "#a7c080"
good_to_bad_2 = "#a7c080"
good_to_bad_3 = "#8e897a"
good_to_bad_4 = "#8e897a"
good_to_bad_5 = "#5a5b56"
good_to_bad_6 = "#dbbc7f"
good_to_bad_7 = "#dbbc7f"
good_to_bad_8 = "#e67e80"
good_to_bad_9 = "#e67e80"
