$background = rgb(272e33)
$foreground = rgb(d3c6aa)
$accent     = rgb(7fbbb3)
$bg_subtle  = rgb(404444)
$bg_muted   = rgb(5a5b56)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
