[palettes.everforest]
base             = '#272e33'
crust            = '#5a5b56'
on_sig1          = '#272e33'
on_sig2          = '#d3c6aa'
on_sigbg         = '#d3c6aa'
red              = '#e67e80'
sig1             = '#7fbbb3'
sig2             = '#d699b6'
sig_bg           = '#272e33'
sig_surface_high = '#404444'
text             = '#d3c6aa'
