[skin]
default = "#ffffff #000000 / #ffffff #262626"
tree = "#4c4c4c None / #262626 None"
parent = "#8d8d8d None / #999999 None"
file = "#ffffff None / #8d8d8d None"
directory = "#8d8d8d None Bold / #8d8d8d None Bold"
exe = "#8d8d8d None Bold"
link = "#8d8d8d None Italic"
pruning = "#4c4c4c None Italic"
perm__ = "#262626 None"
perm_r = "#8d8d8d None"
perm_w = "#8d8d8d None"
perm_x = "#8d8d8d None"
owner = "#999999 None"
group = "#4c4c4c None"
count = "#8d8d8d #000000"
dates = "#4c4c4c None"
sparse = "#8d8d8d None"
content_extract = "#999999 None Italic"
content_match = "#ffffff None Bold"
device_id_major = "#8d8d8d None"
device_id_sep = "#4c4c4c None"
device_id_minor = "#8d8d8d None"
git_branch = "#ffffff None Bold"
git_insertions = "#8d8d8d None"
git_deletions = "#8d8d8d None"
git_status_current = "#262626 None"
git_status_modified = "#8d8d8d None"
git_status_new = "#ffffff None Bold"
git_status_ignored = "#262626 None"
git_status_conflicted = "#8d8d8d None Bold"
git_status_other = "#8d8d8d None"
selected_line = "None #262626 / None #4c4c4c"
char_match = "#ffffff None Bold"
file_error = "#a4a4a4 None Bold"
flag_label = "#999999 None"
flag_value = "#ffffff None Bold"
input = "#ffffff None / #ffffff #262626"
status_error = "#ffffff #a4a4a4"
status_job = "#ffffff #262626"
status_normal = "#ffffff #000000 / #000000 #262626"
status_italic = "#8d8d8d #000000 Italic / #000000 #262626"
status_bold = "#8d8d8d #000000 Bold / #000000 #262626"
status_code = "#ffffff #000000 / #000000 #262626"
status_ellipsis = "#999999 #000000 / #000000 #262626"
purpose_normal = "#ffffff #262626"
purpose_italic = "#8d8d8d #262626 Italic"
purpose_bold = "#8d8d8d #262626 Bold"
purpose_ellipsis = "#999999 #262626"
scrollbar_track = "#000000 None / #000000 None"
scrollbar_thumb = "#4c4c4c None / #262626 None"
help_paragraph = "#ffffff None"
help_bold = "#8d8d8d None Bold"
help_italic = "#8d8d8d None Italic"
help_code = "#ffffff #262626"
help_headers = "#8d8d8d None Bold"
help_table_border = "#4c4c4c None"
preview_title = "#ffffff None Bold / #8d8d8d None"
preview = "#ffffff #000000 / #8d8d8d #262626"
preview_separator = "#4c4c4c None / #262626 None"
preview_line_number = "#4c4c4c #000000"
preview_match = "None #4c4c4c"
hex_null = "#262626 None"
hex_ascii_graphic = "#ffffff None"
hex_ascii_whitespace = "#8d8d8d None"
hex_ascii_other = "#8d8d8d None"
hex_non_ascii = "#8d8d8d None"
staging_area_title = "#ffffff None Bold / #8d8d8d None"
mode_command_mark = "#000000 #8d8d8d Bold"
good_to_bad_0 = "#b6b6b6"
good_to_bad_1 = "#b6b6b6"
good_to_bad_2 = "#b6b6b6"
good_to_bad_3 = "#999999"
good_to_bad_4 = "#999999"
good_to_bad_5 = "#4c4c4c"
good_to_bad_6 = "#cecece"
good_to_bad_7 = "#cecece"
good_to_bad_8 = "#a4a4a4"
good_to_bad_9 = "#a4a4a4"
