$background = rgb(000000)
$foreground = rgb(ffffff)
$accent     = rgb(8d8d8d)
$bg_subtle  = rgb(262626)
$bg_muted   = rgb(4c4c4c)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
