[palettes.vantablack]
bg               = '#000000'
bg_subtle        = '#262626'
bg_muted         = '#4c4c4c'
fg               = '#ffffff'
fg_dim           = '#999999'
sel_bg           = '#ffffff'
sel_fg           = '#000000'
error            = '#a4a4a4'
accent           = '#8d8d8d'
fg_on_accent     = '#ffffff'
success          = '#b6b6b6'
warning          = '#cecece'
cursor           = '#ffffff'
