[mgr]
cwd = { fg = "#ffffff" }
find_keyword = { fg = "#a4a4a4", bold = true, italic = true, underline = true }
find_position = { fg = "#a4a4a4", bold = true, italic = true }
marker_copied = { fg = "#9b9b9b", bg = "#9b9b9b" }
marker_cut = { fg = "#999999", bg = "#999999" }
marker_marked = { fg = "#8d8d8d", bg = "#8d8d8d" }
marker_selected = { fg = "#b6b6b6", bg = "#b6b6b6" }
count_copied = { fg = "#000000", bg = "#999999" }
count_cut = { fg = "#000000", bg = "#999999" }
count_selected = { fg = "#000000", bg = "#b6b6b6" }
border_symbol = " "
border_style = { fg = "#8d8d8d" }

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }
perm_type = { fg = "#8d8d8d" }
perm_read = { fg = "#ffffff" }
perm_write = { fg = "#b6b6b6" }
perm_exec = { fg = "#9b9b9b" }
perm_sep = { fg = "#999999" }
progress_label = { bold = true }
progress_normal = { fg = "#8d8d8d", bg = "#262626" }
progress_error = { fg = "#9b9b9b", bg = "#262626" }

[mode]
normal_main = { bg = "#8d8d8d", fg = "#000000", bold = true }
normal_alt  = { bg = "#262626", fg = "#ffffff" }
select_main = { bg = "#999999", fg = "#000000", bold = true }
select_alt  = { bg = "#262626", fg = "#ffffff" }
unset_main = { bg = "#b6b6b6", fg = "#000000", bold = true }
unset_alt  = { bg = "#262626", fg = "#ffffff" }

[select]
border = { fg = "#8d8d8d" }
active = { fg = "#b6b6b6", bold = true }

[input]
border = { fg = "#8d8d8d" }
value = { fg = "#ffffff" }

[tabs]
active = { fg = "#8d8d8d", bold = true, bg = "#000000" }
inactive = { fg = "#999999", bg = "#000000" }
sep_inner = { open = "[", close = "]" }

[cmp]
border = { fg = "#8d8d8d", bg = "#262626" }

[tasks]
border = { fg = "#8d8d8d" }
title = {}
hovered = { fg = "#999999", underline = true }

[which]
cols = 3
mask = { bg = "#262626" }
cand = { fg = "#8d8d8d" }
rest = { fg = "#000000" }
desc = { fg = "#ffffff" }
separator = " ▶ "
separator_style = { fg = "#ffffff" }

[help]
on = { fg = "#ffffff" }
run = { fg = "#ffffff" }
footer = { fg = "#000000", bg = "#999999" }

[notify]
title_info = { fg = "#b6b6b6" }
title_warn = { fg = "#8d8d8d" }
title_error = { fg = "#9b9b9b" }

[filetype]
rules = [
    { mime = "image/*", fg = "#b6b6b6" },
    { mime = "{audio,video}/*", fg = "#8d8d8d" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#999999" },
    { mime = "application/{pdf,doc,rtf}", fg = "#ffffff" },
    { url = "*", is = "orphan", bg = "#9b9b9b" },
    { url = "*", is = "exec", fg = "#999999" },
    { url = "*", fg = "#ffffff" },
    { url = "*/", fg = "#8d8d8d" },
]
