[palette]
bg          = "#090704"
bg_subtle   = "#22201D"
bg_muted    = "#605D57"
fg          = "#DCB39B"
fg_dim      = "#A58674"
fg_faint    = "#725F4D"
accent      = "#A4735B"
fg_on_accent = "#090704"
success     = "#DCBF87"
warning     = "#FFEBA9"
error       = "#B28E6B"
cursor      = "#DCB39B"
sel_bg      = "#DCB39B"
sel_fg      = "#090704"
color0  = "#090704"
color1  = "#B28E6B"
color2  = "#DCBF87"
color3  = "#FFEBA9"
color4  = "#A4735B"
color5  = "#D79E76"
color6  = "#F2D98B"
color7  = "#DCB39B"
color8  = "#605D57"
color9  = "#CEA275"
color10 = "#FAD48A"
color11 = "#FFE996"
color12 = "#C28567"
color13 = "#F8B07C"
color14 = "#FFEF8D"
color15 = "#FCF4EA"

[starship]
os_bg   = "A4735B"
os_fg   = "090704"
dir_bg  = "605D57"
dir_fg  = "DCB39B"

[nvim]
colorscheme = "fire-and-shadow"
