[palette]
bg = "#00060f"
bg_subtle = "#00231f"
bg_muted = "#004030"
fg = "#00ca7d"
fg_dim = "#007b51"
accent = "#004cf1"
fg_on_accent = "#00ca7d"
success = "#0059ff"
warning = "#1a1b03"
error = "#c00e0e"
cursor = "#00ca7d"
sel_bg = "#5900ff"
sel_fg = "#00ca7d"

color0 = "#10d4b0"
color1 = "#c00e0e"
color2 = "#0059ff"
color3 = "#1a1b03"
color4 = "#004cf1"
color5 = "#94058a"
color6 = "#029790"
color7 = "#311b92"
color8 = "#02adf1"
color9 = "#ff0000"
color10 = "#00ff9c"
color11 = "#ffdd00"
color12 = "#00a2ff"
color13 = "#e215d4"
color14 = "#08e1d7"
color15 = "#2eb8f8"

[starship]
os_bg = "004cf1"      # accent - Neon blue for OS icon background
os_fg = "00060f"      # bg - Dark cyber background for contrast
dir_bg = "0059ff"     # success - Bright blue for directory background

[nvim]
colorscheme = "aether"
