[palette]
bg          = "#130D0C"
bg_subtle   = "#231412"
bg_muted    = "#3A1C18"
fg          = "#EFD0C7"
fg_dim      = "#C86C57"
fg_faint    = "#5A2620"
accent      = "#D88A73"
fg_on_accent = "#130D0C"
success     = "#D88A73"
warning     = "#C86C57"
error       = "#D64D44"
cursor      = "#D88A73"
sel_bg      = "#B55B47"
sel_fg      = "#130D0C"
color0  = "#130D0C"
color1  = "#D64D44"
color2  = "#D88A73"
color3  = "#C86C57"
color4  = "#E0A293"
color5  = "#5A2620"
color6  = "#3A1C18"
color7  = "#EFD0C7"
color8  = "#231412"
color9  = "#FF6A58"
color10 = "#E39580"
color11 = "#CF745A"
color12 = "#F0B5A8"
color13 = "#70312A"
color14 = "#4B2520"
color15 = "#F7E1DB"

[starship]
os_bg   = "B55B47"
os_fg   = "130D0C"
dir_bg  = "5A2620"
dir_fg  = "EFD0C7"

[nvim]
colorscheme = "inferno"
