[palette]
bg          = "#0F0C0A"
bg_subtle   = "#2A2422"
bg_muted    = "#463E3A"
fg          = "#E6D5C2"
fg_dim      = "#A09384"
fg_faint    = "#73665B"
accent      = "#EA9875"
fg_on_accent = "#0F0C0A"
success     = "#43B16A"
warning     = "#F4A21C"
error       = "#D25780"
cursor      = "#E6D5C2"
sel_bg      = "#EA9875"
sel_fg      = "#0F0C0A"
color0  = "#201B19"
color1  = "#D1766E"
color2  = "#99AF6B"
color3  = "#FCBA81"
color4  = "#58BDFF"
color5  = "#9480BA"
color6  = "#4E89A2"
color7  = "#A09384"
color8  = "#73665B"
color9  = "#D25780"
color10 = "#43B16A"
color11 = "#F4A21C"
color12 = "#8BCFFF"
color13 = "#A692CD"
color14 = "#20C9CB"
color15 = "#E6D5C2"
[starship]
os_bg   = "EA9875"
os_fg   = "0F0C0A"
dir_bg  = "463E3A"
dir_fg  = "E6D5C2"
[nvim]
colorscheme = "cendre"
