[colors.primary]
background = "16242d"
foreground = "d6e2ee"

[colors.cursor]
text   = "16242d"
cursor = "f2fcff"

[colors.selection]
text       = "1b2d40"
background = "4d9ed3"

[colors.normal]
black   = "1b2d40"
red     = "4d86b0"
green   = "5e95bc"
yellow  = "6fa4c9"
blue    = "6fb8e3"
magenta = "8bc9eb"
cyan    = "b4e4f6"
white   = "d6e2ee"

[colors.bright]
black   = "304860"
red     = "73a6cb"
green   = "86b7d8"
yellow  = "9dcae5"
blue    = "f2fcff"
magenta = "b1d8ee"
cyan    = "d1eef8"
white   = "d6e2ee"

# [window]
# opacity = 0.95
# blur = true

# [font]
# normal = { family = "FiraCode Nerd Font", style = "Regular" }
# bold = { family = "FiraCode Nerd Font", style = "Bold" }
# italic = { family = "FiraCode Nerd Font", style = "Italic" }
# size = 11
