[skin]
default = "#ffcead #060B1E / #ffcead #2b2833"
tree = "#504548 None / #2b2833 None"
parent = "#7d82d9 None / #9b8073 None"
file = "#ffcead None / #7d82d9 None"
directory = "#7d82d9 None Bold / #7d82d9 None Bold"
exe = "#7d82d9 None Bold"
link = "#7d82d9 None Italic"
pruning = "#504548 None Italic"
perm__ = "#2b2833 None"
perm_r = "#7d82d9 None"
perm_w = "#7d82d9 None"
perm_x = "#7d82d9 None"
owner = "#9b8073 None"
group = "#504548 None"
count = "#7d82d9 #060B1E"
dates = "#504548 None"
sparse = "#7d82d9 None"
content_extract = "#9b8073 None Italic"
content_match = "#ffcead None Bold"
device_id_major = "#7d82d9 None"
device_id_sep = "#504548 None"
device_id_minor = "#7d82d9 None"
git_branch = "#ffcead None Bold"
git_insertions = "#7d82d9 None"
git_deletions = "#7d82d9 None"
git_status_current = "#2b2833 None"
git_status_modified = "#7d82d9 None"
git_status_new = "#ffcead None Bold"
git_status_ignored = "#2b2833 None"
git_status_conflicted = "#7d82d9 None Bold"
git_status_other = "#7d82d9 None"
selected_line = "None #2b2833 / None #504548"
char_match = "#ffcead None Bold"
file_error = "#ED5B5A None Bold"
flag_label = "#9b8073 None"
flag_value = "#ffcead None Bold"
input = "#ffcead None / #ffcead #2b2833"
status_error = "#ffcead #ED5B5A"
status_job = "#ffcead #2b2833"
status_normal = "#ffcead #060B1E / #060B1E #2b2833"
status_italic = "#7d82d9 #060B1E Italic / #060B1E #2b2833"
status_bold = "#7d82d9 #060B1E Bold / #060B1E #2b2833"
status_code = "#ffcead #060B1E / #060B1E #2b2833"
status_ellipsis = "#9b8073 #060B1E / #060B1E #2b2833"
purpose_normal = "#ffcead #2b2833"
purpose_italic = "#7d82d9 #2b2833 Italic"
purpose_bold = "#7d82d9 #2b2833 Bold"
purpose_ellipsis = "#9b8073 #2b2833"
scrollbar_track = "#060B1E None / #060B1E None"
scrollbar_thumb = "#504548 None / #2b2833 None"
help_paragraph = "#ffcead None"
help_bold = "#7d82d9 None Bold"
help_italic = "#7d82d9 None Italic"
help_code = "#ffcead #2b2833"
help_headers = "#7d82d9 None Bold"
help_table_border = "#504548 None"
preview_title = "#ffcead None Bold / #7d82d9 None"
preview = "#ffcead #060B1E / #7d82d9 #2b2833"
preview_separator = "#504548 None / #2b2833 None"
preview_line_number = "#504548 #060B1E"
preview_match = "None #504548"
hex_null = "#2b2833 None"
hex_ascii_graphic = "#ffcead None"
hex_ascii_whitespace = "#7d82d9 None"
hex_ascii_other = "#7d82d9 None"
hex_non_ascii = "#7d82d9 None"
staging_area_title = "#ffcead None Bold / #7d82d9 None"
mode_command_mark = "#060B1E #7d82d9 Bold"
good_to_bad_0 = "#92a593"
good_to_bad_1 = "#92a593"
good_to_bad_2 = "#92a593"
good_to_bad_3 = "#9b8073"
good_to_bad_4 = "#9b8073"
good_to_bad_5 = "#504548"
good_to_bad_6 = "#E9BB4F"
good_to_bad_7 = "#E9BB4F"
good_to_bad_8 = "#ED5B5A"
good_to_bad_9 = "#ED5B5A"
