$background = rgb(060B1E)
$foreground = rgb(ffcead)
$accent     = rgb(7d82d9)
$bg_subtle  = rgb(2b2833)
$bg_muted   = rgb(504548)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
