# -----------------------------
# Kitty Color Scheme
# -----------------------------

foreground              #ffcead
background              #060B1E
selection_foreground    #060B1E
selection_background    #ffcead
cursor                  #ffcead

# Black / Gray
color0  #3C486D
color8  #6d7db6

# Red
color1  #ED5B5A
color9  #faaaa9

# Green
color2  #92a593
color10 #c4cfc4

# Yellow
color3  #E9BB4F
color11 #f7dc9c

# Blue
color4  #7d82d9
color12 #c2c4f0

# Magenta
color5  #c89dc1
color13 #ead7e7

# Cyan
color6  #a3bfd1
color14 #dfeaf0

# White
color7  #F99957
color15 #ffcead

# Optional: window border / tab bar
active_tab_foreground   #060B1E
active_tab_background   #7d82d9
inactive_tab_foreground #ffcead
inactive_tab_background #3C486D
