[palettes.ethereal]
bg               = '#060B1E'
bg_subtle        = '#2b2833'
bg_muted         = '#504548'
fg               = '#ffcead'
fg_dim           = '#9b8073'
sel_bg           = '#ffcead'
sel_fg           = '#060B1E'
error            = '#ED5B5A'
accent           = '#7d82d9'
fg_on_accent     = '#ffcead'
success          = '#92a593'
warning          = '#E9BB4F'
cursor           = '#ffcead'
