[palettes.ethereal]
base             = '#060B1E'
crust            = '#504548'
on_sig1          = '#060B1E'
on_sig2          = '#ffcead'
on_sigbg         = '#ffcead'
red              = '#ED5B5A'
sig1             = '#7d82d9'
sig2             = '#c89dc1'
sig_bg           = '#060B1E'
sig_surface_high = '#2b2833'
text             = '#ffcead'
