[mgr]
cwd = { fg = "#ffcead" }
find_keyword = { fg = "#ED5B5A", bold = true, italic = true, underline = true }
find_position = { fg = "#ED5B5A", bold = true, italic = true }
marker_copied = { fg = "#c89dc1", bg = "#c89dc1" }
marker_cut = { fg = "#9b8073", bg = "#9b8073" }
marker_marked = { fg = "#7d82d9", bg = "#7d82d9" }
marker_selected = { fg = "#92a593", bg = "#92a593" }
count_copied = { fg = "#060B1E", bg = "#9b8073" }
count_cut = { fg = "#060B1E", bg = "#9b8073" }
count_selected = { fg = "#060B1E", bg = "#92a593" }
border_symbol = " "
border_style = { fg = "#7d82d9" }

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }
perm_type = { fg = "#7d82d9" }
perm_read = { fg = "#ffcead" }
perm_write = { fg = "#92a593" }
perm_exec = { fg = "#c89dc1" }
perm_sep = { fg = "#9b8073" }
progress_label = { bold = true }
progress_normal = { fg = "#7d82d9", bg = "#2b2833" }
progress_error = { fg = "#c89dc1", bg = "#2b2833" }

[mode]
normal_main = { bg = "#7d82d9", fg = "#060B1E", bold = true }
normal_alt  = { bg = "#2b2833", fg = "#ffcead" }
select_main = { bg = "#9b8073", fg = "#060B1E", bold = true }
select_alt  = { bg = "#2b2833", fg = "#ffcead" }
unset_main = { bg = "#92a593", fg = "#060B1E", bold = true }
unset_alt  = { bg = "#2b2833", fg = "#ffcead" }

[select]
border = { fg = "#7d82d9" }
active = { fg = "#92a593", bold = true }

[input]
border = { fg = "#7d82d9" }
value = { fg = "#ffcead" }

[tabs]
active = { fg = "#7d82d9", bold = true, bg = "#060B1E" }
inactive = { fg = "#9b8073", bg = "#060B1E" }
sep_inner = { open = "[", close = "]" }

[cmp]
border = { fg = "#7d82d9", bg = "#2b2833" }

[tasks]
border = { fg = "#7d82d9" }
title = {}
hovered = { fg = "#9b8073", underline = true }

[which]
cols = 3
mask = { bg = "#2b2833" }
cand = { fg = "#7d82d9" }
rest = { fg = "#060B1E" }
desc = { fg = "#ffcead" }
separator = " ▶ "
separator_style = { fg = "#ffcead" }

[help]
on = { fg = "#ffcead" }
run = { fg = "#ffcead" }
footer = { fg = "#060B1E", bg = "#9b8073" }

[notify]
title_info = { fg = "#92a593" }
title_warn = { fg = "#7d82d9" }
title_error = { fg = "#c89dc1" }

[filetype]
rules = [
    { mime = "image/*", fg = "#92a593" },
    { mime = "{audio,video}/*", fg = "#7d82d9" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#9b8073" },
    { mime = "application/{pdf,doc,rtf}", fg = "#ffcead" },
    { url = "*", is = "orphan", bg = "#c89dc1" },
    { url = "*", is = "exec", fg = "#9b8073" },
    { url = "*", fg = "#ffcead" },
    { url = "*/", fg = "#7d82d9" },
]
