# : Manager [[[

[mgr]
cwd = { fg = "#ffcead" }

# Tab
tab_active = { fg = "#3C486D", bg = "#ead7e7", bold = true }
tab_inactive = { fg = "#ffcead", bg = "#6d7db6" }
tab_width = 1

# Find
find_keyword = { fg = "#ED5B5A", bold = true, italic = true, underline = true }
find_position = { fg = "#ED5B5A", bold = true, italic = true }

# Marker
marker_copied = { fg = "#a3bfd1", bg = "#a3bfd1" }
marker_cut = { fg = "#3C486D", bg = "#3C486D" }
marker_marked = { fg = "#ead7e7", bg = "#ead7e7" }
marker_selected = { fg = "#cecff3", bg = "#cecff3" }

# Count
count_copied = { fg = "#060B1E", bg = "#3C486D" }
count_cut = { fg = "#060B1E", bg = "#3C486D" }
count_selected = { fg = "#3C486D", bg = "#cecff3" }

# Border
border_symbol = " "
border_style  = { fg = "#ead7e7" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#6d7db6", fg = "#ead7e7" }

[mode]
# Mode
normal_main = { bg = "#ead7e7", fg = "#3C486D", bold = true }
normal_alt  = { bg = "#c2c4f0", fg = "#ffcead" }

# Select mode
select_main = { bg = "#3C486D", fg = "#3C486D", bold = true }
select_alt  = { bg = "#c2c4f0", fg = "#ffcead" }

# Unset mode
unset_main = { bg = "#cecff3", fg = "#3C486D", bold = true }
unset_alt  = { bg = "#c2c4f0", fg = "#ffcead" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ead7e7", bg = "#c2c4f0" }
progress_error = { fg = "#a3bfd1", bg = "#c2c4f0" }

# Permissions
permissions_t = { fg = "#ead7e7" }
permissions_w = { fg = "#cecff3" }
permissions_x = { fg = "#a3bfd1" }
permissions_r = { fg = "#ffcead" }
permissions_s = { fg = "#3C486D" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ead7e7" }
active = { fg = "#cecff3", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#ead7e7" }
value = { fg = "#ffcead" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#ead7e7", bold = true, bg = "#060B1E" }
inactive = { fg = "#3C486D", bg = "#060B1E" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ead7e7", bg = "#6d7db6" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ead7e7" }
title = {}
hovered = { fg = "#3C486D", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#c2c4f0" }
cand = { fg = "#ead7e7" }
rest = { fg = "#3C486D" }
desc = { fg = "#ffcead" }
separator = " ▶ "
separator_style = { fg = "#ffcead" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ffcead" }
run = { fg = "#ffcead" }
footer = { fg = "#3C486D", bg = "#3C486D" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#cecff3" }
title_warn = { fg = "#ead7e7" }
title_error = { fg = "#a3bfd1" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#cecff3" },

    # Media
    { mime = "{audio,video}/*", fg = "#ead7e7" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#3C486D" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#ffcead" },

    # Special files
    { name = "*", is = "orphan", bg = "#a3bfd1" },
    { name = "*", is = "exec", fg = "#3C486D" },

    # Fallback
    { name = "*", fg = "#ffcead" },
    { name = "*/", fg = "#ead7e7" },
]

# : ]]]
