[skin]
default = "#e0def4 #191724 / #e0def4 #363443"
tree = "#545262 None / #363443 None"
parent = "#9ccfd8 None / #908ea0 None"
file = "#e0def4 None / #9ccfd8 None"
directory = "#9ccfd8 None Bold / #9ccfd8 None Bold"
exe = "#9ccfd8 None Bold"
link = "#9ccfd8 None Italic"
pruning = "#545262 None Italic"
perm__ = "#363443 None"
perm_r = "#9ccfd8 None"
perm_w = "#9ccfd8 None"
perm_x = "#9ccfd8 None"
owner = "#908ea0 None"
group = "#545262 None"
count = "#9ccfd8 #191724"
dates = "#545262 None"
sparse = "#9ccfd8 None"
content_extract = "#908ea0 None Italic"
content_match = "#e0def4 None Bold"
device_id_major = "#9ccfd8 None"
device_id_sep = "#545262 None"
device_id_minor = "#9ccfd8 None"
git_branch = "#e0def4 None Bold"
git_insertions = "#9ccfd8 None"
git_deletions = "#9ccfd8 None"
git_status_current = "#363443 None"
git_status_modified = "#9ccfd8 None"
git_status_new = "#e0def4 None Bold"
git_status_ignored = "#363443 None"
git_status_conflicted = "#9ccfd8 None Bold"
git_status_other = "#9ccfd8 None"
selected_line = "None #363443 / None #545262"
char_match = "#e0def4 None Bold"
file_error = "#eb6f92 None Bold"
flag_label = "#908ea0 None"
flag_value = "#e0def4 None Bold"
input = "#e0def4 None / #e0def4 #363443"
status_error = "#191724 #eb6f92"
status_job = "#e0def4 #363443"
status_normal = "#e0def4 #191724 / #e0def4 #363443"
status_italic = "#9ccfd8 #191724 Italic / #e0def4 #363443"
status_bold = "#9ccfd8 #191724 Bold / #e0def4 #363443"
status_code = "#e0def4 #191724 / #e0def4 #363443"
status_ellipsis = "#908ea0 #191724 / #e0def4 #363443"
purpose_normal = "#e0def4 #363443"
purpose_italic = "#9ccfd8 #363443 Italic"
purpose_bold = "#9ccfd8 #363443 Bold"
purpose_ellipsis = "#908ea0 #363443"
scrollbar_track = "#191724 None / #191724 None"
scrollbar_thumb = "#545262 None / #363443 None"
help_paragraph = "#e0def4 None"
help_bold = "#9ccfd8 None Bold"
help_italic = "#9ccfd8 None Italic"
help_code = "#e0def4 #363443"
help_headers = "#9ccfd8 None Bold"
help_table_border = "#545262 None"
preview_title = "#e0def4 None Bold / #9ccfd8 None"
preview = "#e0def4 #191724 / #9ccfd8 #363443"
preview_separator = "#545262 None / #363443 None"
preview_line_number = "#545262 #191724"
preview_match = "None #545262"
hex_null = "#363443 None"
hex_ascii_graphic = "#e0def4 None"
hex_ascii_whitespace = "#9ccfd8 None"
hex_ascii_other = "#9ccfd8 None"
hex_non_ascii = "#9ccfd8 None"
staging_area_title = "#e0def4 None Bold / #9ccfd8 None"
mode_command_mark = "#e0def4 #9ccfd8 Bold"
good_to_bad_0 = "#31748f"
good_to_bad_1 = "#31748f"
good_to_bad_2 = "#31748f"
good_to_bad_3 = "#908ea0"
good_to_bad_4 = "#908ea0"
good_to_bad_5 = "#545262"
good_to_bad_6 = "#f6c177"
good_to_bad_7 = "#f6c177"
good_to_bad_8 = "#eb6f92"
good_to_bad_9 = "#eb6f92"
