$background = rgb(191724)
$foreground = rgb(e0def4)
$accent     = rgb(9ccfd8)
$bg_subtle  = rgb(363443)
$bg_muted   = rgb(545262)
$active_border   = $accent
$inactive_border = $bg_muted
$focus_border    = $accent
$shadow_color    = rgba(0 0 0 55)
