[palettes.rosepine-darker]
base             = '#191724'
crust            = '#545262'
on_sig1          = '#191724'
on_sig2          = '#e0def4'
on_sigbg         = '#e0def4'
red              = '#eb6f92'
sig1             = '#9ccfd8'
sig2             = '#c4a7e7'
sig_bg           = '#191724'
sig_surface_high = '#363443'
text             = '#e0def4'
