[palettes.rosepine-darker]
bg               = '#191724'
bg_subtle        = '#363443'
bg_muted         = '#545262'
fg               = '#e0def4'
fg_dim           = '#908ea0'
sel_bg           = '#403d52'
sel_fg           = '#e0def4'
error            = '#eb6f92'
accent           = '#9ccfd8'
fg_on_accent     = '#191724'
success          = '#31748f'
warning          = '#f6c177'
cursor           = '#524f67'
