# : Manager [[[

[mgr]
cwd = { fg = "#e0def4" }

# Tab
tab_active = { fg = "#26233a", bg = "#eb6f92", bold = true }
tab_inactive = { fg = "#e0def4", bg = "#6e6a86" }
tab_width = 1

# Find
find_keyword = { fg = "#eb6f92", bold = true, italic = true, underline = true }
find_position = { fg = "#eb6f92", bold = true, italic = true }

# Marker
marker_copied = { fg = "#31748f", bg = "#31748f" }
marker_cut = { fg = "#e0def4", bg = "#e0def4" }
marker_marked = { fg = "#eb6f92", bg = "#eb6f92" }
marker_selected = { fg = "#514f61", bg = "#514f61" }

# Count
count_copied = { fg = "#191724", bg = "#e0def4" }
count_cut = { fg = "#191724", bg = "#e0def4" }
count_selected = { fg = "#26233a", bg = "#514f61" }

# Border
border_symbol = " "
border_style  = { fg = "#eb6f92" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#6e6a86", fg = "#eb6f92" }

[mode]
# Mode
normal_main = { bg = "#eb6f92", fg = "#26233a", bold = true }
normal_alt  = { bg = "#26233a", fg = "#e0def4" }

# Select mode
select_main = { bg = "#e0def4", fg = "#e0def4", bold = true }
select_alt  = { bg = "#26233a", fg = "#e0def4" }

# Unset mode
unset_main = { bg = "#514f61", fg = "#e0def4", bold = true }
unset_alt  = { bg = "#26233a", fg = "#e0def4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#eb6f92", bg = "#26233a" }
progress_error = { fg = "#31748f", bg = "#26233a" }

# Permissions
permissions_t = { fg = "#eb6f92" }
permissions_w = { fg = "#514f61" }
permissions_x = { fg = "#31748f" }
permissions_r = { fg = "#e0def4" }
permissions_s = { fg = "#e0def4" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#eb6f92" }
active = { fg = "#514f61", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#eb6f92" }
value = { fg = "#e0def4" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#eb6f92", bold = true, bg = "#191724" }
inactive = { fg = "#e0def4", bg = "#191724" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#eb6f92", bg = "#6e6a86" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#eb6f92" }
title = {}
hovered = { fg = "#e0def4", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#26233a" }
cand = { fg = "#eb6f92" }
rest = { fg = "#26233a" }
desc = { fg = "#e0def4" }
separator = " ▶ "
separator_style = { fg = "#e0def4" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e0def4" }
run = { fg = "#e0def4" }
footer = { fg = "#e0def4", bg = "#e0def4" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#514f61" }
title_warn = { fg = "#eb6f92" }
title_error = { fg = "#31748f" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#514f61" },

    # Media
    { mime = "{audio,video}/*", fg = "#eb6f92" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#e0def4" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#e0def4" },

    # Special files
    { name = "*", is = "orphan", bg = "#31748f" },
    { name = "*", is = "exec", fg = "#e0def4" },

    # Fallback
    { name = "*", fg = "#e0def4" },
    { name = "*/", fg = "#eb6f92" },
]

# : ]]]
