[mgr]
cwd = { fg = "#e0def4" }
find_keyword = { fg = "#eb6f92", bold = true, italic = true, underline = true }
find_position = { fg = "#eb6f92", bold = true, italic = true }
marker_copied = { fg = "#c4a7e7", bg = "#c4a7e7" }
marker_cut = { fg = "#908ea0", bg = "#908ea0" }
marker_marked = { fg = "#9ccfd8", bg = "#9ccfd8" }
marker_selected = { fg = "#31748f", bg = "#31748f" }
count_copied = { fg = "#191724", bg = "#908ea0" }
count_cut = { fg = "#191724", bg = "#908ea0" }
count_selected = { fg = "#191724", bg = "#31748f" }
border_symbol = " "
border_style = { fg = "#9ccfd8" }

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }
perm_type = { fg = "#9ccfd8" }
perm_read = { fg = "#e0def4" }
perm_write = { fg = "#31748f" }
perm_exec = { fg = "#c4a7e7" }
perm_sep = { fg = "#908ea0" }
progress_label = { bold = true }
progress_normal = { fg = "#9ccfd8", bg = "#363443" }
progress_error = { fg = "#c4a7e7", bg = "#363443" }

[mode]
normal_main = { bg = "#9ccfd8", fg = "#191724", bold = true }
normal_alt  = { bg = "#363443", fg = "#e0def4" }
select_main = { bg = "#908ea0", fg = "#191724", bold = true }
select_alt  = { bg = "#363443", fg = "#e0def4" }
unset_main = { bg = "#31748f", fg = "#191724", bold = true }
unset_alt  = { bg = "#363443", fg = "#e0def4" }

[select]
border = { fg = "#9ccfd8" }
active = { fg = "#31748f", bold = true }

[input]
border = { fg = "#9ccfd8" }
value = { fg = "#e0def4" }

[tabs]
active = { fg = "#9ccfd8", bold = true, bg = "#191724" }
inactive = { fg = "#908ea0", bg = "#191724" }
sep_inner = { open = "[", close = "]" }

[cmp]
border = { fg = "#9ccfd8", bg = "#363443" }

[tasks]
border = { fg = "#9ccfd8" }
title = {}
hovered = { fg = "#908ea0", underline = true }

[which]
cols = 3
mask = { bg = "#363443" }
cand = { fg = "#9ccfd8" }
rest = { fg = "#191724" }
desc = { fg = "#e0def4" }
separator = " ▶ "
separator_style = { fg = "#e0def4" }

[help]
on = { fg = "#e0def4" }
run = { fg = "#e0def4" }
footer = { fg = "#191724", bg = "#908ea0" }

[notify]
title_info = { fg = "#31748f" }
title_warn = { fg = "#9ccfd8" }
title_error = { fg = "#c4a7e7" }

[filetype]
rules = [
    { mime = "image/*", fg = "#31748f" },
    { mime = "{audio,video}/*", fg = "#9ccfd8" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#908ea0" },
    { mime = "application/{pdf,doc,rtf}", fg = "#e0def4" },
    { url = "*", is = "orphan", bg = "#c4a7e7" },
    { url = "*", is = "exec", fg = "#908ea0" },
    { url = "*", fg = "#e0def4" },
    { url = "*/", fg = "#9ccfd8" },
]
